resolver: lts-13.7
compiler: ghc-8.6.5
packages:
- '.'
# uncomment this, fix the path, and comment out the extra-dep below to do local
# dev with the library
# - '/home/enolan/code/kademlia-bkase'
nix:
  enable: false
  packages: [gmp]
extra-deps:
- git: https://github.com/CodaProtocol/kademlia.git
  commit: bd02de9c5cda6204e881bbc5bbc6e0e445706b1c
flags: {}
extra-package-dbs: []
