(test
 (name test_snark_work_lib)
 (package snark_work_lib)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_jane ppx_mina ppx_version))
 (libraries
  ;; opam libraries
  alcotest
  core
  sexplib0
  ;; local libraries
  currency
  mina_base
  mina_ledger
  mina_state
  signature_lib
  snark_work_lib
  transaction_snark
  transaction_snark_test_helpers
  transaction_witness))
