---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "foundation-delegation.fullname" . }}-backend
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app: {{ template "foundation-delegation.fullname" . }}-backend
  ports:
  - name: delegation-backend
    port: {{ .Values.backend.port }}
    targetPort: backend
    protocol: TCP
