apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    testnet: {{ $.Values.testnetName }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mina.ports.metrics }}
    targetPort: {{ .Values.mina.ports.metrics }}
    protocol: TCP
    name: metrics-port
  selector:
    app: {{ .Values.name }}