apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
        component: aggregator
    spec:
      containers:
        - name: main
          image: {{ .Values.aggregator.image }}
          command: ["mina-aggregator"]
          env:
            - name: CLUSTER_BASE_URL
              value: http://1.k8.openmina.com:{{ index (lookup "v1" "Namespace" "" .Release.Namespace) "metadata" "annotations" "openmina.com/testnet.nodePort" }}
            - name: PLAIN_NODE_COUNT
              value: {{ .Values.plainNodesConfig.count | quote }}
            - name: SEED_NODE_COUNT
              value: {{ len .Values.seedConfigs | quote }}
            - name: SNARKER_NODE_COUNT
              value: {{ .Values.minaSnarkCoordinatorsConfig | len | quote }}
            - name: TRANSACTION_GENERATOR_NODE_COUNT
              value: "0"
            - name: PRODUCER_NODE_COUNT
              value: {{ len .Values.blockProducerConfigs | quote }}
            - name: DATA_PULL_INTERVAL
              value: "5"
            - name: USE_INTERNAL_ENDPOINTS
              value: "1"
            - name: REMOTE_STORAGE_USER
              valueFrom:
                secretKeyRef:
                  name: aggregator-remote-storage
                  key: username
            - name: REMOTE_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aggregator-remote-storage
                  key: password
            - name: REMOTE_STORAGE_PATH
              value: /home/aggregator/{{ .Release.Namespace }}.json
            - name: CI_REPO
              value: {{ .Values.aggregator.ciRepo | default "openmina/mina" }}
            - name: CI_API_URL
              value: {{ .Values.aggregator.ciApiUrl }}
          ports:
            - name: http-aggregator
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-gha-current-test-status
data:
  status: "null"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io