apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: aggregator
  ports:
  - name: http-aggregator
    protocol: TCP
    port: 80
    targetPort: 8000