(library
 (name rosetta_healthcheck_applet)
 (public_name rosetta.healthcheck_applet)
 (modules rosetta_healthcheck_applet health_probes health_output)
 (libraries
  ;; opam libraries
  core
  core_unix.command_unix
  async
  async.async_command
  ppx_deriving_yojson.runtime
  yojson
  ;; local libraries
  interpolator_lib
  logger
  rosetta_client)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_let ppx_deriving_yojson ppx_mina)))

(executable
 (package rosetta)
 (name rosetta_healthcheck)
 (public_name rosetta-healthcheck)
 (modules rosetta_healthcheck)
 (libraries rosetta_healthcheck_applet)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version)))
