(* GENERATED FILE - DO NOT EDIT *)
(* Profile: {PROFILE} *)
[%%define ledger_depth {LEDGER_DEPTH}]
[%%define curve_size {CURVE_SIZE}]
[%%define coinbase "{COINBASE}"]
[%%define consensus_mechanism "{CONSENSUS_MECHANISM}"]
[%%define k {CONSENSUS_K}]
[%%define c {CONSENSUS_C}]
[%%define delta {CONSENSUS_DELTA}]
[%%define scan_state_with_tps_goal {SCAN_STATE_WITH_TPS_GOAL}]
[%%define scan_state_transaction_capacity_log_2 {SCAN_STATE_TRANSACTION_CAPACITY_LOG_2}]
[%%define scan_state_work_delay {SCAN_STATE_WORK_DELAY}]
[%%define scan_state_tps_goal_x10 {SCAN_STATE_TPS_GOAL_X10}]
[%%define debug_logs {DEBUG_LOGS}]
[%%define call_logger {CALL_LOGGER}]
[%%define tracing {TRACING}]
[%%define cache_exceptions {CACHE_EXCEPTIONS}]
[%%define record_async_backtraces {RECORD_ASYNC_BACKTRACES}]
[%%define proof_level "{PROOF_LEVEL}"]
[%%define pool_max_size {POOL_MAX_SIZE}]
[%%define account_creation_fee_int "{ACCOUNT_CREATION_FEE_INT}"]
[%%define default_transaction_fee "{DEFAULT_TRANSACTION_FEE}"]
[%%define default_snark_worker_fee "{DEFAULT_SNARK_WORKER_FEE}"]
[%%define minimum_user_command_fee "{MINIMUM_USER_COMMAND_FEE}"]
[%%define current_protocol_version "{CURRENT_PROTOCOL_VERSION}"]

[%%define time_offsets              {TIME_OFFSETS}]
[%%define fake_hash                 {FAKE_HASH}]
[%%define genesis_ledger           "{GENESIS_LEDGER}"]
[%%define genesis_state_timestamp  "{GENESIS_STATE_TIMESTAMP}"]
[%%define block_window_duration     {BLOCK_WINDOW_DURATION}]
[%%define integration_tests         {INTEGRATION_TESTS}]
[%%define force_updates             {FORCE_UPDATES}]
[%%define mock_frontend_data        {MOCK_FRONTEND_DATA}]
[%%define print_versioned_types     {PRINT_VERSIONED_TYPES}]
[%%define daemon_expiry            "{DAEMON_EXPIRY}"]
[%%define test_full_epoch           {TEST_FULL_EPOCH}]
