---
kind: pipeline
name: build-image
type: docker
clone:
  disable: true

environment:
  OPENMINA_BRANCH: openmina-legacy-snark-workers

steps:

- name: clone
  image: alpine/git
  commands:
  - git clone $${MINA_REPO:-https://github.com/MinaProtocol/mina} --depth 1 -b $${MINA_BRANCH:-develop} .

- name: prepare-dockerfiles
  image: busybox:latest
  commands:
  - wget https://github.com/openmina/mina/raw/$${OPENMINA_BRANCH}/dockerfiles/stages/99-openmina-tail -O dockerfiles/stages/99-openmina-tail
  - sed -i -e "s/zlib1g-dev/zlib1g-dev jq/" dockerfiles/stages/1-build-deps
  - for f in 1-build-deps 2-opam-deps 3-builder 99-openmina-tail; do cat dockerfiles/stages/$$f; done > ./dockerfiles/stages/merged
  - echo "!dockerfiles/scripts/healthcheck-utilities.sh" >> .dockerignore

- name: publish-image
  image: plugins/docker
  settings:
    build_args:
    - MINA_BRANCH=${MINA_BRANCH:-develop}
    - MINA_REPO=${MINA_REPO:-https://github.com/MinaProtocol/mina}
    dockerfile: ./dockerfiles/stages/merged
    password:
      from_secret: docker_hub_password
    repo: openmina/mina
    tags:
    - mina-daily-${MINA_BRANCH:-develop}-${DRONE_BUILD_NUMBER}
    - mina-daily-${MINA_BRANCH:-develop}-latest
    username:
      from_secret: docker_hub_username
    cache_from: ${CACHE_IMAGE}

---
kind: pipeline
name: deploy-to-cluster
type: docker
clone:
  disable: true
depends_on:
- build-image


environment:
  # path to openmina tooling
  OM: helm/openmina-config
  # target height to wait for after deployment
  TARGET_HEIGHT: 8
  # resource to wait for status when deploying Mina seeds
  SEEDS_WAIT_RESOURCE: deployment/seed1
  # timeout to wait when deploying Mina seeds
  SEEDS_WAIT_TIMEOUT: 10m
  # resource to wait for status when deploying Mina nodes
  NODES_WAIT_RESOURCE: deployment/node1
  # timeout to wait when deploying Mina nodes
  NODES_WAIT_TIMEOUT: 15m
  # retries to check all nodes to be at the same level
  HEIGHT_WAIT_RETRIES: 20
  # period to wait before retrying
  HEIGHT_WAIT_PERIOD: 15

defs:
- &log
  image: alpine/k8s:1.26.1
  detach: true
  environment:
    KUBECONFIG: kube-config
  commands:
  - while ! kubectl logs deployment/$${NAME} --container mina --follow; do echo "waiting for $${NAME} to start..."; sleep 10; done

steps:

- name: clone
  image: alpine/git
  commands:
  - git clone $${OPENMINA_REPO:-https://github.com/openmina/mina} --depth 1 -b $${OPENMINA_BRANCH:-openmina-legacy-snark-workers} .

- name: prepare-kubeconfig
  image: alpine/k8s:1.26.1
  environment:
    DRONE_KUBECONFIG:
      from_secret: k8s_config
    KUBECONFIG: kube-config
  commands:
  - umask 0077
  - echo "$DRONE_KUBECONFIG" > $${KUBECONFIG}
  - kubectl config set-context --current --namespace $${NAMESPACE:-testnet}

- name: delete-old-testnet
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - $${OM}/deploy.sh delete --all --force
  - sleep 10
  - |
    PODS="$$($${OM}/kube-utils.sh mina-pods)"
    if [ -n "$${PODS}" ]; then
        echo "Workaround for pods left running, force-delete pods $$PODS"
        kubectl delete --force pods $${PODS} || true
    fi
  - helm delete zkapp-server-continuous --wait --timeout=1m || true
  - helm delete zkapp-send-continuous --wait --timeout=5m || true

- name: prepare-deamon-json
  image: alpine/k8s:1.26.1
  commands:
  - $${OM}/generate-conf-file.sh --slot-duration=$${SLOT_DURATION:-180} $${SLOTS_PER_EPOCH:+--slots-per-epoch=$${SLOTS_PER_EPOCH}} > $${OM}/resources/daemon.json

- name: log-seed
  <<: *log
  environment:
    NAME: seed1

- name: log-node
  <<: *log
  environment:
    NAME: node1

- name: log-producer
  <<: *log
  environment:
    NAME: node1

- name: log-snarker
  <<: *log
  environment:
    NAME: snarker001

- name: deploy-nodes
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - export MINA_IMAGE="openmina/mina:mina-daily-$${MINA_BRANCH:-develop}-${DRONE_BUILD_NUMBER}"
  - HELM_ARGS="--set=healthcheck.failureThreshold=1800 $${HELM_ARGS}"
  - $${OM}/deploy.sh deploy --seeds --force -- $${HELM_ARGS}
  - sleep 30 # handicap to other nodes so seed nodes to be up when they become needed
  - $${OM}/deploy.sh deploy --producers --nodes --force -- $${HELM_ARGS}
  - $${OM}/deploy.sh deploy --snark-workers --force -- $${HELM_ARGS}
  - $${OM}/update-frontend.sh -- --set=isVanilla=true

- name: testnet-is-ready
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - $${OM}/kube-utils.sh mina-testnet-available $${NODES_WAIT_TIMEOUT}
  - $${OM}/kube-utils.sh mina-testnet-same-height $${HEIGHT_WAIT_RETRIES} $${HEIGHT_WAIT_PERIOD}

- name: deployment-info
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - PORT="$$($${OM}/kube-utils.sh frontend-port $${NAMESPACE:-testnet})"
  - 'echo "Frontend: http://1.k8.openmina.com:$PORT"'
  - 'echo "Namespace: $${NAMESPACE:-testnet}"'
  - echo
  - 'echo Seed nodes: $(kubectl get pods -l role=seed -o name | wc -l)'
  - 'echo Producer nodes: $(kubectl get pods -l role=block-producer -o name | wc -l)'
  - 'echo Snark coordinator nodes: $(kubectl get pods -l role=snark-coordinator -o name | wc -l)'
  - 'echo Snark worker nodes: $(kubectl get pods -l role=snark-worker -o name | wc -l)'
  - 'echo Plain nodes: $(kubectl get pods -l role=plain-node -o name | wc -l)'

---

kind: pipeline
name: split-load
type: docker
clone:
  disable: true
depends_on: [ deploy-to-cluster ]

environment:
  SUFFIX: ${DRONE_BUILD_NUMBER}
  NODES: "--nodes=8 --snarkers=4 --prods=3 --prod0s=3 --seeds=2"
  OM: helm/openmina-config

defs:
- &log
  image: alpine/k8s:1.26.1
  detach: true
  environment:
    KUBECONFIG: kube-config
  commands:
  - while ! kubectl logs $${NAME}-$${SUFFIX} --follow; do echo "waiting for $${NAME}-$${SUFFIX} to start..."; sleep 10; done

steps:

- name: clone
  image: alpine/git
  commands:
  - git clone $${OPENMINA_REPO:-https://github.com/openmina/mina} --depth 1 -b $${OPENMINA_BRANCH:-openmina-legacy-snark-workers} .

- name: configure
  image: alpine/k8s:1.26.1
  environment:
    DRONE_KUBECONFIG:
      from_secret: k8s_config
    KUBECONFIG: kube-config
  commands:
  - umask 0077
  - echo "$DRONE_KUBECONFIG" > "$KUBECONFIG"
  - kubectl config set-context --current --namespace $${NAMESPACE:-testnet}

- name: single-component
  image: openmina/mina-network-debugger:latest
  environment:
    URL: http://1.k8.openmina.com:31308
  commands:
  - sleep  10 && topology-tool --url=$URL $$NODES show-graph --expected-components 1 > /dev/null

- name: enable-firewall
  image: openmina/mina-network-debugger:latest
  environment:
    URL: http://1.k8.openmina.com:31308
  commands:
  - sleep  10 && topology-tool --url=$URL $$NODES enable-firewall
  - sleep  240 && topology-tool --url=$URL $$NODES show-graph --expected-components 2 > /dev/null

- name: log-server
  <<: *log
  environment:
    NAME: deploy/zkapp-server

- name: log-generate
  <<: *log
  environment:
    NAME: job/zkapp-generate

- name: log-send
  <<: *log
  environment:
    NAME: job/zkapp-send

- name: send-zkapp-txs
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm install zkapp-server-$${SUFFIX} helm/zkapps/server --set=suffix=$${SUFFIX}
  - kubectl wait deploy/zkapp-server-$${SUFFIX} --for=condition=available --timeout=1m
  - helm install zkapp-generate-$${SUFFIX} helm/zkapps/generate --set=loadKind=$${ZK_JOB:-sign-x4} --set=workers=$${ZK_WORKERS:-8} --set=suffix=$${SUFFIX}
  - kubectl wait job/zkapp-generate-$${SUFFIX} --for=condition=complete --timeout=30m
  - helm install zkapp-send-$${SUFFIX} helm/zkapps/send --set=count=$${ZK_COUNT:-128} --set=workers=$${ZK_WORKERS:-8} --set=suffix=$${SUFFIX}
  - kubectl wait job/zkapp-send-$${SUFFIX} --for=condition=complete --timeout=30m

- name: wait-slot-0-10
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - $${OM}/kube-utils.sh mina-node-wait-for-epoch-slot deploy/prod2 $${NAMESPACE:-testnet} 0 10

- name: blockchain-split
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - $${OM}/kube-utils.sh assert-different-history  deploy/prod2 $${NAMESPACE:-testnet} deploy/prod3 $${NAMESPACE:-testnet}

- name: disable-firewall
  image: openmina/mina-network-debugger:latest
  environment:
    URL: http://1.k8.openmina.com:31308
  commands:
  - topology-tool --url=$URL $$NODES show-graph --expected-components 2 > /dev/null
  - topology-tool --url=$URL $$NODES disable-firewall
  - sleep 240 && topology-tool --url=$URL $$NODES show-graph --expected-components 1 > /dev/null

- name: blockchain-merged
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - $${OM}/kube-utils.sh mina-testnet-same-chain $${SAME_CHAIN_WAIT_RETRIES:-20} $${SAME_CHAIN_WAIT_PERIOD:-60} $${NAMESPACE:-testnet}

- name: log-wait
  <<: *log
  environment:
    NAME: job/zkapp-wait

- name: wait-zkapp-txs
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm install zkapp-wait-$${SUFFIX} helm/zkapps/wait --set=suffix=$${SUFFIX}
  - kubectl wait job/zkapp-wait-$${SUFFIX} --for=condition=complete --timeout=180m

- name: cleanup-zkapp
  image: alpine/k8s:1.26.1
  when:
    status:
    - failure
    - success
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm delete zkapp-server-$${SUFFIX} || true
  - helm delete zkapp-generate-$${SUFFIX} || true
  - helm delete zkapp-send-$${SUFFIX} || true
  - helm delete zkapp-wait-$${SUFFIX} || true

---
kind: pipeline
name: finish
type: docker
clone:
  disable: true
depends_on: [ split-load ]

environment:
  # path to openmina tooling
  OM: helm/openmina-config
  # global slot to wait force
  MAX_HEIGHT: 20

steps:

- name: clone
  image: alpine/git
  commands:
  - git clone $${OPENMINA_REPO:-https://github.com/openmina/mina} --depth 1 -b $${OPENMINA_BRANCH:-openmina-legacy-snark-workers} .

- name: configure
  image: alpine/k8s:1.26.1
  environment:
    DRONE_KUBECONFIG:
      from_secret: k8s_config
    KUBECONFIG: kube-config
  commands:
  - umask 0077
  - echo "$DRONE_KUBECONFIG" > "$KUBECONFIG"
  - kubectl config set-context --current --namespace $${NAMESPACE:-testnet}

- name: wait-for-slot
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - |
    while true; do
      HEIGHT=$$($${OM}/kube-utils.sh mina-node-chain-height deploy/node1)
      if [ -n "$HEIGHT" ] && [ "$HEIGHT" -ge "$MAX_HEIGHT" ]; then
        echo "Reached height $MAX_HEIGHT"
        exit
      fi
      echo "Height $HEIGHT is lower than $MAX_HEIGHT"
      sleep 20
    done

- name: report-finish
  image: busybox
  commands:
  - echo "Done"

---

kind: pipeline
name: continuous-load
type: docker
clone:
  disable: true
depends_on: [ finish ]

environment:
  OM: helm/openmina-config

steps:

- name: clone
  image: alpine/git
  commands:
  - git clone $${OPENMINA_REPO:-https://github.com/openmina/mina} --depth 1 -b $${OPENMINA_BRANCH:-openmina-legacy-snark-workers} .

- name: configure
  image: alpine/k8s:1.26.1
  environment:
    DRONE_KUBECONFIG:
      from_secret: k8s_config
    KUBECONFIG: kube-config
  commands:
  - umask 0077
  - echo "$DRONE_KUBECONFIG" > "$KUBECONFIG"
  - kubectl config set-context --current --namespace $${NAMESPACE:-testnet}

- name: send-zkapp-txs
  image: alpine/k8s:1.26.1
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm install zkapp-server-continuous helm/zkapps/server --set=suffix=continuous
  - kubectl wait deploy/zkapp-server-continuous --for=condition=available --timeout=1m
  - helm install zkapp-generate-continuous helm/zkapps/generate --set=loadKind=$${ZK_JOB:-sign-x4} --set=workers=$${ZK_WORKERS:-8} --set=suffix=continuous
  - kubectl wait job/zkapp-generate-continuous --for=condition=complete --timeout=30m
  - helm delete zkapp-generate-continuous --wait --timeout=5m
  - helm install zkapp-send-continuous helm/zkapps/send --set=count=0 --set=workers=$${ZK_WORKERS:-8} --set=suffix=continuous --set=continuous=true
