pull_request_rules:
    - name: automatically merge approved PRs with the ready-to-merge label
      conditions:
          - "status-success=ci/circleci: test--test_postake_bootstrap"
          - "status-success=ci/circleci: test--fake_hash"
          - "status-success=ci/circleci: test--test_postake_split_snarkless"
          - "status-success=ci/circleci: test--test_postake_catchup"
          - "status-success=ci/circleci: test--test_postake"
          - "status-success=ci/circleci: test--test_postake_snarkless"
          - "status-success=ci/circleci: test-unit--test_posig_snarkless"
          - "status-success=ci/circleci: test-unit--test_postake_snarkless"
          - "status-success=ci/circleci: build-artifacts--testnet_postake"
          - "status-success=ci/circleci: build-artifacts--testnet_postake_snarkless_fake_hash"
          - "status-success=ci/circleci: lint"
          - "status-success=ci/circleci: tracetool"
          - "status-success=ci/circleci: build-wallet"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge
      actions:
          merge:
              method: squash
              strict: smart
          delete_head_branch: {}