FROM gcr.io/o1labs-192920/ocaml407:latest

# Install nix for our haskell deps
RUN sudo mkdir -p /nix
RUN sudo chown opam /nix
RUN sudo mkdir -p /etc/nix
RUN sudo bash  -c 'echo "build-users-group =" > /etc/nix/nix.conf'
ENV USER opam
RUN cd /home/opam && curl https://nixos.org/nix/install | sh

RUN sudo apt-get install --yes cmake
RUN sudo apt-get install --yes libssl-dev
RUN sudo apt-get install --yes libffi-dev
RUN sudo apt-get install --yes libprocps-dev
RUN sudo apt-get install --yes libgmp-dev
RUN sudo apt-get install --yes libgmp3-dev
RUN sudo apt-get install --yes libboost-dev
RUN sudo apt-get install --yes libboost-program-options-dev
RUN sudo apt-get install --yes librocksdb4.5 librocksdb-dev
RUN sudo apt-get install --yes zlib1g-dev libsodium-dev

RUN opam update -y && opam upgrade -y
RUN opam depext -i dune
RUN opam install dune
RUN opam install num
RUN opam install core
RUN opam install async
RUN opam install merlin ocp-indent utop ocamlformat
RUN opam install ctypes-foreign ctypes ppx_deriving
RUN opam install yojson menhir bignum
RUN opam install async_ssl cohttp cohttp-async
RUN opam install extlib rpc_parallel

ADD ./app/kademlia-haskell/prefetch /prefetch
RUN sudo chown -R opam /prefetch
RUN cd /prefetch && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build prefetch.nix
RUN opam install bitstring orocksdb
RUN opam install camlp4
RUN opam install ppx_deriving_yojson
RUN opam install sodium
