FROM gcr.io/o1labs-192920/ocaml-base:6ae82b5f3dabfca604d3e9cf11d7d126030a4026

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

