FROM gcr.io/o1labs-192920/ocaml-base:d84b51cbbf0549bf5df06c89bd14c297553fd9d7

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && jbuilder build

