FROM gcr.io/o1labs-192920/ocaml-base:84caab05b51117a57df2c1d550716f78449ae67b

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && jbuilder build

