FROM gcr.io/o1labs-192920/nanobit:latest

WORKDIR /testbridge
ADD ./lib/testbridge/container/ /testbridge
ADD ./lib/testbridge/container/testbridge.opam.in /testbridge/testbridge.opam
RUN sudo chown -R opam /testbridge
RUN eval `opam config env` && dune build

CMD bash -c "while true; do ./_build/install/default/bin/container; sleep 1; done"

