FROM gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

