FROM gcr.io/o1labs-192920/ocaml-base:2c231a11923259c6fa3a1ea4c1241aec4fc10481

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

