FROM gcr.io/o1labs-192920/ocaml-base:15b442a253cf4a82b564afbf904425988e34e5e2

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

