apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "buildkite-exporter.fullname" . }}
  labels:
    app: {{ template "buildkite-exporter.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "buildkite-exporter.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "buildkite-exporter.fullname" . }}
        pipeline: {{ .Values.exporter.pipeline }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.exporter.ports.metricsPort | quote }}
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: exporter
        resources:
          limits:
            memory: 2.0Gi
          requests:
            memory: 2.0Gi
            cpu: 1000m
        image: {{ .Values.exporter.image }}
        env:
        - name: BUILDKITE_API_KEY
          value: {{ .Values.exporter.buildkiteApiKey }}
        - name: METRICS_PORT
          value: {{ .Values.exporter.ports.metricsPort | quote }}
{{- if .Values.exporter.optionalEnv }}
{{ toYaml .Values.exporter.optionalEnv | indent 10 }}
{{- end }}
        ports:
        - name: metrics-port
          containerPort: {{ .Values.exporter.ports.metricsPort }}
          protocol: TCP
{{- include "healthcheck.buildkite-exporter.healthChecks" .Values | indent 8 }}
        imagePullPolicy: Always
