version: "3.9"

services:
  mina:
    container_name: mina
    image: gcr.io/o1labs-192920/mina-toolchain@sha256:966863de43c72c294e14762ae567404005f99654c54338a9a89b999476a36d1f
    volumes:
      - "..:/mina" # mount the mina folder so that changes are reflected in the container
      - "_opam:/mina/_opam" # exclude any existing local switch
      - "_build:/mina/_build" # exclude any existing local build
      - "opam:/home/opam/.opam" # cache opam stuff
    stdin_open: true # docker run -i
    tty: true # docker run -t

# volumes
volumes:
  opam:
  _opam:
  _build:
