// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var BlockParser$BlockProducers = require("./BlockParser.bs.js");

BlockParser$BlockProducers.parseBlockPages(1, /* array */[]).then((function (creators) {
        creators.forEach((function (creator) {
                var match = Js_dict.get(BlockParser$BlockProducers.supposedBlockProducersList, creator);
                if (match !== undefined) {
                  return Js_dict.unsafeDeleteKey(BlockParser$BlockProducers.supposedBlockProducersList, creator);
                } else {
                  return /* () */0;
                }
              }));
        console.log(BlockParser$BlockProducers.supposedBlockProducersList);
        return Promise.resolve(/* () */0);
      }));

/*  Not a pure module */
