apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-credentials
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: "{{ `{{ .type }}` }}"
        url: "{{ `{{ .url }}` }}"
        sshPrivateKey: |
          {{ `{{ .sshPrivateKey }}` }}
  dataFrom:
    - extract:
        key: argoCdGitHubCredentials # multi-key gcp json secret
      