---
apiVersion: v1
kind: Secret
metadata:
  name: mina
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:MinaProtocol/mina.git
