(** Product: zkapps_examples — Example zkApp smart contracts and tests. *)

open Manifest

let register () =
  (* -- zkapps_examples (library) -------------------------------------- *)
  library "zkapps_examples" ~path:"src/app/zkapps_examples"
    ~deps:
      [ opam "async_kernel"
      ; opam "base"
      ; opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_stdlib"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "tuple_lib"
      ; local "with_hash"
      ]
    ~ppx:(Ppx.custom [ "ppx_let"; "ppx_version" ]) ;

  (* -- zkapps_actions (library) --------------------------------------- *)
  private_library "zkapps_actions" ~path:"src/app/zkapps_examples/actions"
    ~deps:
      [ opam "base"
      ; opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "mina_base"
      ; local "pickles"
      ; local "pickles_types"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "zkapps_examples"
      ]
    ~ppx:Ppx.minimal ;

  (* -- zkapps_add_events (library) ------------------------------------ *)
  private_library "zkapps_add_events" ~path:"src/app/zkapps_examples/add_events"
    ~deps:
      [ opam "base"
      ; opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "mina_base"
      ; local "pickles"
      ; local "pickles_types"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "zkapps_examples"
      ]
    ~ppx:Ppx.minimal ;

  (* -- zkapps_big_circuit (library) ----------------------------------- *)
  private_library "zkapps_big_circuit"
    ~path:"src/app/zkapps_examples/big_circuit"
    ~deps:
      [ opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "kimchi_pasta.constraint_system"
      ; local "mina_base"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "tuple_lib"
      ; local "zkapps_examples"
      ]
    ~ppx:Ppx.minimal ;

  (* -- zkapps_calls (library) ----------------------------------------- *)
  private_library "zkapps_calls" ~path:"src/app/zkapps_examples/calls"
    ~deps:
      [ opam "base"
      ; opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "tuple_lib"
      ; local "with_hash"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "h_list.ppx"; "ppx_version" ]) ;

  (* -- zkapps_empty_update (library) ---------------------------------- *)
  private_library "zkapps_empty_update"
    ~path:"src/app/zkapps_examples/empty_update"
    ~deps:
      [ opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "tuple_lib"
      ; local "zkapps_examples"
      ]
    ~ppx:Ppx.minimal ;

  (* -- zkapps_initialize_state (library) ------------------------------ *)
  private_library "zkapps_initialize_state"
    ~path:"src/app/zkapps_examples/initialize_state"
    ~deps:
      [ opam "base"
      ; opam "core_kernel"
      ; local "crypto_params"
      ; local "currency"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snarky.backendless"
      ; local "snark_params"
      ; local "tuple_lib"
      ; local "zkapps_examples"
      ]
    ~ppx:Ppx.minimal ;

  (* -- zkapps_tokens (library) ---------------------------------------- *)
  private_library "zkapps_tokens" ~path:"src/app/zkapps_examples/tokens"
    ~deps:
      [ opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "crypto_params"
      ; local "currency"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_backend_common"
      ; local "kimchi_pasta"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_base"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "tuple_lib"
      ; local "with_hash"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "h_list.ppx"; "ppx_let"; "ppx_version" ]) ;

  (* -- tokens (test library) ------------------------------------------ *)
  private_library "tokens" ~path:"src/app/zkapps_examples/test/tokens"
    ~inline_tests:true
    ~deps:
      [ opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "ppx_inline_test.config"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "merkle_ledger"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_stdlib"
      ; local "mina_transaction_logic"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_examples"
      ; local "zkapps_tokens"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_snarky"; "ppx_version" ]) ;

  (* -- actions (test) ------------------------------------------------- *)
  test "actions" ~path:"src/app/zkapps_examples/test/actions"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "consensus"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "merkle_ledger"
      ; local "merkle_list_verifier"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_wire_types"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_base"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_actions"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_version" ]) ;

  (* -- add_events (test) ---------------------------------------------- *)
  test "add_events" ~path:"src/app/zkapps_examples/test/add_events"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "core"
      ; opam "core_kernel"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "merkle_ledger"
      ; local "merkle_list_verifier"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_add_events"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_version" ]) ;

  (* -- big_circuit (test) --------------------------------------------- *)
  test "big_circuit" ~path:"src/app/zkapps_examples/test/big_circuit"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_transaction_logic"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_base"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_big_circuit"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_snarky"; "ppx_version" ]) ;

  (* -- calls (test) --------------------------------------------------- *)
  test "calls" ~path:"src/app/zkapps_examples/test/calls"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "merkle_ledger"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_transaction_logic"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_calls"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_snarky"; "ppx_version" ]) ;

  (* -- empty_update (test) -------------------------------------------- *)
  test "empty_update" ~path:"src/app/zkapps_examples/test/empty_update"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_stdlib"
      ; local "mina_transaction_logic"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_base"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_empty_update"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_snarky"; "ppx_version" ]) ;

  (* -- initialize_state (test) ---------------------------------------- *)
  test "initialize_state" ~path:"src/app/zkapps_examples/test/initialize_state"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "yojson"
      ; local "cache_dir"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "kimchi_backend"
      ; local "kimchi_pasta"
      ; local "kimchi_pasta.basic"
      ; local "merkle_ledger"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_state"
      ; local "mina_transaction_logic"
      ; local "pasta_bindings"
      ; local "pickles"
      ; local "pickles.backend"
      ; local "pickles_types"
      ; local "random_oracle"
      ; local "random_oracle_input"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_params"
      ; local "snarky.backendless"
      ; local "transaction_protocol_state"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "with_hash"
      ; local "zkapps_examples"
      ; local "zkapps_initialize_state"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_snarky"; "ppx_version" ]) ;

  (* -- zkapp_optional_custom_gates_tests (test) ----------------------- *)
  test "zkapp_optional_custom_gates_tests"
    ~path:"src/app/zkapps_examples/test/optional_custom_gates"
    ~deps:
      [ opam "alcotest"
      ; opam "async"
      ; opam "async_kernel"
      ; opam "async_unix"
      ; opam "base"
      ; opam "base.caml"
      ; opam "core"
      ; opam "core_kernel"
      ; opam "integers"
      ; opam "result"
      ; opam "sexplib0"
      ; local "currency"
      ; local "data_hash_lib"
      ; local "genesis_constants"
      ; local "mina_base"
      ; local "mina_base.import"
      ; local "mina_generators"
      ; local "mina_ledger"
      ; local "mina_numbers"
      ; local "mina_transaction_logic"
      ; local "pickles"
      ; local "pickles_optional_custom_gates_circuits"
      ; local "pickles_types"
      ; local "sgn"
      ; local "signature_lib"
      ; local "snark_keys_header"
      ; local "snark_params"
      ; local "test_util"
      ; local "transaction_snark"
      ; local "transaction_snark_tests"
      ; local "zkapp_command_builder"
      ; local "zkapps_examples"
      ]
    ~ppx:(Ppx.custom [ "ppx_jane"; "ppx_mina"; "ppx_snarky"; "ppx_version" ]) ;

  ()
