apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "email-cron"
spec:
  schedule: "0 0 */15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: {{ .Values.cron.image }}
              imagePullPolicy: Always
              command:
                - /usr/local/bin/python
                - send_email.py
          {{- if .Values.cron.secret }}
              volumeMounts:
                - name: cron-creds
                  mountPath: /opt/minanet/creds/
          volumes:
            - name: cron-creds
              secret:
                secretName: {{ .Values.cron.secret }}
                items:
                - key: gcs-credential.json
                  path: gcs-credential.json
                - key: config.py
                  path: config.py
                - key: sendgrid.key
                  path: sendgrid.key
          {{- end }}
