(library
 (name mina_healthcheck_applet)
 (public_name mina_healthcheck.applet)
 (modules mina_healthcheck_applet)
 (libraries
  core_unix.command_unix
  ;; opam libraries
  async
  async_kernel
  async_unix
  core
  uri
  yojson
  ;; local libraries
  logger
  sync_status
  mina_graphql_client
  mina_healthcheck_lib)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version ppx_jane ppx_mina)))

(executable
 (name mina_healthcheck)
 (package mina_healthcheck)
 (public_name mina-healthcheck)
 (modules mina_healthcheck)
 (libraries mina_healthcheck_applet)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_version)))
