#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 <input.deb> <session-dir>

Opens a Debian package for modification by extracting it into a session directory.

Arguments:
  <input.deb>    Path to the .deb file to open
  <session-dir>  Directory where the session will be created

Session Structure:
  <session-dir>/
    ├── metadata.env       # Session metadata (compression type, paths, etc.)
    ├── debian-binary      # Debian package version
    ├── control/           # Extracted control.tar.*
    └── data/              # Extracted data.tar.* (modify this)

Example:
  $0 mina-devnet_3.3.0_amd64.deb ./my-session
  # Now you can modify files in ./my-session/data/
  # Then use deb-session-save.sh to create the modified .deb

Notes:
  - Session directory will be created if it doesn't exist
  - If session directory exists, it will be cleaned first
  - All paths in metadata.env are absolute
EOF
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

INPUT_DEB="$1"
SESSION_DIR="$2"

# Validate input
if [[ ! -f "$INPUT_DEB" ]]; then
  echo "ERROR: Input .deb file not found: $INPUT_DEB" >&2
  exit 1
fi

# Convert to absolute paths
INPUT_DEB_ABS=$(readlink -f "$INPUT_DEB")

# Create or clean session directory
if [[ -d "$SESSION_DIR" ]]; then
  echo "Cleaning existing session directory: $SESSION_DIR"
  rm -rf "$SESSION_DIR"/*
else
  mkdir -p "$SESSION_DIR"
fi

SESSION_DIR_ABS=$(readlink -f "$SESSION_DIR")

echo "=== Opening Debian Package ==="
echo "Input:   $INPUT_DEB_ABS"
echo "Session: $SESSION_DIR_ABS"

cd "$SESSION_DIR_ABS"

# Extract .deb structure: debian-binary, control.tar.*, data.tar.*
echo "Extracting package structure..."
ar x "$INPUT_DEB_ABS"

# Find the archives
CONTROL_TAR=$(echo control.tar.* 2>/dev/null || true)
DATA_TAR=$(echo data.tar.* 2>/dev/null || true)

if [[ -z "$CONTROL_TAR" || -z "$DATA_TAR" ]]; then
  echo "ERROR: Could not find control.tar.* or data.tar.* in $INPUT_DEB_ABS" >&2
  exit 1
fi

echo "Found control archive: $CONTROL_TAR"
echo "Found data archive:    $DATA_TAR"

# Detect compression type for data.tar
case "$DATA_TAR" in
  data.tar)     DATA_COMPRESS="none" ;;
  data.tar.gz)  DATA_COMPRESS="gz" ;;
  data.tar.xz)  DATA_COMPRESS="xz" ;;
  data.tar.zst) DATA_COMPRESS="zst" ;;
  *)
    echo "ERROR: Unknown data.tar compression: $DATA_TAR" >&2
    exit 1
    ;;
esac

# Detect compression type for control.tar
case "$CONTROL_TAR" in
  control.tar)     CONTROL_COMPRESS="none" ;;
  control.tar.gz)  CONTROL_COMPRESS="gz" ;;
  control.tar.xz)  CONTROL_COMPRESS="xz" ;;
  control.tar.zst) CONTROL_COMPRESS="zst" ;;
  *)
    echo "ERROR: Unknown control.tar compression: $CONTROL_TAR" >&2
    exit 1
    ;;
esac

# Extract control.tar.* into control/
mkdir -p control
echo "Extracting control archive..."
tar -xf "$CONTROL_TAR" -C control

# Extract data.tar.* into data/
mkdir -p data
echo "Extracting data archive..."
tar -xf "$DATA_TAR" -C data

# Create metadata file
echo "Creating session metadata..."
cat > metadata.env <<METADATA
# Debian Package Session Metadata
# Generated by deb-session-open.sh

INPUT_DEB="$INPUT_DEB_ABS"
SESSION_DIR="$SESSION_DIR_ABS"
DATA_COMPRESS="$DATA_COMPRESS"
CONTROL_COMPRESS="$CONTROL_COMPRESS"
CREATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Original package info
PACKAGE_NAME="$(dpkg-deb --field "$INPUT_DEB_ABS" Package || echo "unknown")"
PACKAGE_VERSION="$(dpkg-deb --field "$INPUT_DEB_ABS" Version || echo "unknown")"
PACKAGE_ARCH="$(dpkg-deb --field "$INPUT_DEB_ABS" Architecture || echo "unknown")"
METADATA

# Clean up the extracted tar files (we only need the unpacked directories)
rm -f "$CONTROL_TAR" "$DATA_TAR"

echo ""
echo "=== Session Opened Successfully ==="
echo "Session directory: $SESSION_DIR_ABS"
echo ""
echo "You can now modify files in:"
echo "  - $SESSION_DIR_ABS/data/        (package contents)"
echo "  - $SESSION_DIR_ABS/control/     (package metadata)"
echo ""
echo "When done, use deb-session-save.sh to create the modified package."
