(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Account_balance_request.t : An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
 *)

type t =
  { network_identifier: Network_identifier.t
  ; account_identifier: Account_identifier.t
  ; block_identifier: Partial_block_identifier.t option [@default None] }
[@@deriving yojson {strict= false}, show]

(** An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed. *)
let create (network_identifier : Network_identifier.t)
    (account_identifier : Account_identifier.t) : t =
  {network_identifier; account_identifier; block_identifier= None}
