(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Account_coins_request.t : AccountCoinsRequest is utilized to make a request on the /account/coins endpoint. 
 *)

type t =
  { network_identifier : Network_identifier.t
  ; account_identifier : Account_identifier.t
  ; (* Include state from the mempool when looking up an account's unspent coins. Note, using this functionality breaks any guarantee of idempotency.  *)
    include_mempool : bool
  ; (* In some cases, the caller may not want to retrieve coins for all currencies for an AccountIdentifier. If the currencies field is populated, only coins for the specified currencies will be returned. If not populated, all unspent coins will be returned.  *)
    currencies : Currency.t list [@default []]
  }
[@@deriving yojson { strict = false }, show, eq]

(** AccountCoinsRequest is utilized to make a request on the /account/coins endpoint.  *)
let create (network_identifier : Network_identifier.t)
    (account_identifier : Account_identifier.t) (include_mempool : bool) : t =
  { network_identifier; account_identifier; include_mempool; currencies = [] }
