(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Block_event.t : BlockEvent represents the addition or removal of a BlockIdentifier from storage. Streaming BlockEvents allows lightweight clients to update their own state without needing to implement their own syncing logic.
 *)

type t =
  { (* sequence is the unique identifier of a BlockEvent within the context of a NetworkIdentifier. *)
    sequence : int64
  ; block_identifier : Block_identifier.t
  ; _type : Enums.blockeventtype [@key "type"]
  }
[@@deriving yojson { strict = false }, show, eq]

(** BlockEvent represents the addition or removal of a BlockIdentifier from storage. Streaming BlockEvents allows lightweight clients to update their own state without needing to implement their own syncing logic. *)
let create (sequence : int64) (block_identifier : Block_identifier.t)
    (_type : Enums.blockeventtype) : t =
  { sequence; block_identifier; _type }
