(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Coin_identifier.t : CoinIdentifier uniquely identifies a Coin.
 *)

type t =
  { (* Identifier should be populated with a globally unique identifier of a Coin. In Bitcoin, this identifier would be transaction_hash:index. *)
    identifier: string }
[@@deriving yojson {strict= false}, show]

(** CoinIdentifier uniquely identifies a Coin. *)
let create (identifier : string) : t = {identifier}
