(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Construction_derive_response.t : ConstructionDeriveResponse is returned by the `/construction/derive` endpoint.
 *)

type t =
  { (* [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format. *)
    address: string option [@default None]
  ; account_identifier: Account_identifier.t option [@default None]
  ; metadata: Yojson.Safe.t option [@default None] }
[@@deriving yojson {strict= false}, show]

(** ConstructionDeriveResponse is returned by the `/construction/derive` endpoint. *)
let create () : t = {address= None; account_identifier= None; metadata= None}
