(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Related_transaction.t : The related_transaction allows implementations to link together multiple transactions. An unpopulated network identifier indicates that the related transaction is on the same network. 
 *)

type t =
  { network_identifier : Network_identifier.t option [@default None]
  ; transaction_identifier : Transaction_identifier.t
  ; direction : Enums.direction
  }
[@@deriving yojson { strict = false }, show, eq]

(** The related_transaction allows implementations to link together multiple transactions. An unpopulated network identifier indicates that the related transaction is on the same network.  *)
let create (transaction_identifier : Transaction_identifier.t)
    (direction : Enums.direction) : t =
  { network_identifier = None; transaction_identifier; direction }
