(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Search_transactions_response.t : SearchTransactionsResponse contains an ordered collection of BlockTransactions that match the query in SearchTransactionsRequest. These BlockTransactions are sorted from most recent block to oldest block.
 *)

type t =
  { (* next_offset is the next offset to use when paginating through transaction results. If this field is not populated, there are no more transactions to query. *)
    next_offset: int64 option [@default None]
  ; (* transactions is an array of BlockTransactions sorted by most recent BlockIdentifier (meaning that transactions in recent blocks appear first). If there are many transactions for a particular search, transactions may not contain all matching transactions. It is up to the caller to paginate these transactions using the max_block field. *)
    transactions: Block_transaction.t list }
[@@deriving yojson {strict= false}, show]

(** SearchTransactionsResponse contains an ordered collection of BlockTransactions that match the query in SearchTransactionsRequest. These BlockTransactions are sorted from most recent block to oldest block. *)
let create (transactions : Block_transaction.t list) : t =
  {next_offset= None; transactions}
