(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sub_network_identifier.t : In blockchains with sharded state, the SubNetworkIdentifier is required to query some object on a specific shard. This identifier is optional for all non-sharded blockchains.
 *)

type t = {network: string; metadata: Yojson.Safe.t option [@default None]}
[@@deriving yojson {strict= false}, show]

(** In blockchains with sharded state, the SubNetworkIdentifier is required to query some object on a specific shard. This identifier is optional for all non-sharded blockchains. *)
let create (network : string) : t = {network; metadata= None}
