(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Sync_status.t : SyncStatus is used to provide additional context about an implementation's sync status. It is often used to indicate that an implementation is healthy when it cannot be queried  until some sync phase occurs. If an implementation is immediately queryable, this model is often not populated.
 *)

type t =
  { (* CurrentIndex is the index of the last synced block in the current stage. *)
    current_index: int64
  ; (* TargetIndex is the index of the block that the implementation is attempting to sync to in the current stage. *)
    target_index: int64 option [@default None]
  ; (* Stage is the phase of the sync process. *)
    stage: string option [@default None] }
[@@deriving yojson {strict= false}, show]

(** SyncStatus is used to provide additional context about an implementation's sync status. It is often used to indicate that an implementation is healthy when it cannot be queried  until some sync phase occurs. If an implementation is immediately queryable, this model is often not populated. *)
let create (current_index : int64) : t =
  {current_index; target_index= None; stage= None}
