#!/bin/bash

# Restore a single freshly-built application binary from the namespaced apps CI
# cache (written by buildkite/scripts/apps/write_to_cache.sh) and install it on
# PATH under a chosen name -- mirroring the layout a .deb would provide, so
# callers invoke the tool identically whether it came from the cache or a
# package.
#
# Usage: restore_app.sh <exe> <install-as>
#   exe        : the .exe filename in the cache, e.g. runtime_genesis_ledger.exe
#   install-as : the name to install it under on PATH, e.g. mina-create-genesis
#
# The cache location is derived from the build identity, so callers don't repeat
# the variant string:
#   apps/<codename>[/<variant>]/<exe>
# with
#   codename : $MINA_DEB_CODENAME (default bullseye)
#   variant  : derived from $APPS_BUILD_FLAG ("instrumented") and $APPS_ARCH
#              ("arm64"). It names only what deviates from the default build, so
#              a standard amd64 build has NO variant segment and its binaries sit
#              directly in apps/<codename>/.
#
# There is deliberately no network or profile in the path. The daemon binary the
# cache holds is src/app/cli/src/mina.exe, which links no mina_signature_kind
# library (see src/app/cli/src/dune) -- signature kind and proof level are
# resolved at runtime from the config, so one binary serves every network and
# profile. Only the compile-time flags (instrumentation) and the target
# architecture actually change the bytes.
#
# Installs to ${MINA_BIN_DIR:-/usr/local/bin}/<install-as> (using sudo when not
# root). Exits non-zero without side effects if not in Buildkite context or the
# binary is not cached, so callers can fall back to installing the .deb.

set -eo pipefail

EXE=$1
INSTALL_AS=$2

if [[ -z "$EXE" || -z "$INSTALL_AS" ]]; then
  echo "Usage: $0 <exe> <install-as>" >&2
  exit 1
fi

if [[ ! -v BUILDKITE_BUILD_ID ]]; then
  echo "restore_app: not in Buildkite context" >&2
  exit 1
fi

CODENAME="${MINA_DEB_CODENAME:-bullseye}"

segments=()
[[ "${APPS_BUILD_FLAG:-}" == "instrumented" ]] && segments+=("instrumented")
[[ "${APPS_ARCH:-amd64}" == "arm64" ]] && segments+=("arm64")
VARIANT=$(IFS=-; echo "${segments[*]}")

SRC="apps/${CODENAME}${VARIANT:+/${VARIANT}}/${EXE}"
BIN_DIR="${MINA_BIN_DIR:-/usr/local/bin}"

SUDO=""
if [[ "$(id -u)" -ne 0 ]] && command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

if ! ./buildkite/scripts/cache/manager.sh read "$SRC" "$TMP_DIR" >&2; then
  echo "restore_app: ${SRC} not found in cache" >&2
  exit 1
fi

# If write_to_cache.sh bundled this binary's shared libraries, install the real
# binary into a private directory beside them and put a wrapper on PATH. That
# makes the restored app independent of whatever the agent image carries, which
# matters whenever a binary grows a runtime dependency the image predates.
#
# The wrapper runs the BUNDLED dynamic loader explicitly rather than exporting
# LD_LIBRARY_PATH. The bundle contains glibc, and a binary's PT_INTERP names the
# HOST loader -- letting a host loader load a foreign libc is undefined and
# fails in confusing ways. Invoking ld-linux with --library-path also keeps the
# override off child processes, which an exported LD_LIBRARY_PATH would not.
LIBS_TARBALL="${EXE}.libs.tar.gz"
LIB_SRC="apps/${CODENAME}${VARIANT:+/${VARIANT}}/${LIBS_TARBALL}"
PRIV_DIR="${MINA_APP_LIB_DIR:-/usr/local/lib/mina-apps}/${INSTALL_AS}"

if ./buildkite/scripts/cache/manager.sh read "$LIB_SRC" "$TMP_DIR" 2>/dev/null >&2 \
   && [[ -f "${TMP_DIR}/${LIBS_TARBALL}" ]]; then
  $SUDO rm -rf "$PRIV_DIR"
  $SUDO install -d -m 0755 "${PRIV_DIR}/lib"
  $SUDO tar -xzf "${TMP_DIR}/${LIBS_TARBALL}" -C "${PRIV_DIR}/lib"
  $SUDO install -D -m 0755 "${TMP_DIR}/${EXE}" "${PRIV_DIR}/${EXE}"

  # shellcheck source=buildkite/scripts/bundle-libs.sh
  source ./buildkite/scripts/bundle-libs.sh
  LOADER="$(bundle_loader_name "${PRIV_DIR}/lib")"

  # bundle_write_wrapper is not reusable here: it emits a wrapper that resolves
  # the bundle relative to itself, whereas this one sits in BIN_DIR and points
  # at a bundle in a different tree, and it has to be written through sudo.
  if [[ -n "$LOADER" ]]; then
    $SUDO tee "${BIN_DIR}/${INSTALL_AS}" >/dev/null <<WRAPPER
#!/bin/sh
# Generated by buildkite/scripts/apps/restore_app.sh -- runs the bundled loader
# against the bundled libraries, so the agent image is irrelevant.
exec "${PRIV_DIR}/lib/${LOADER}" --library-path "${PRIV_DIR}/lib" "${PRIV_DIR}/${EXE}" "\$@"
WRAPPER
    $SUDO chmod 0755 "${BIN_DIR}/${INSTALL_AS}"
    echo "restore_app: installed ${EXE} as ${BIN_DIR}/${INSTALL_AS} (bundled libs via ${LOADER})" >&2
    exit 0
  fi

  # Libraries but no loader. Safe to use LD_LIBRARY_PATH here precisely because
  # a bundle without a loader contains no glibc.
  $SUDO tee "${BIN_DIR}/${INSTALL_AS}" >/dev/null <<WRAPPER
#!/bin/sh
# Generated by buildkite/scripts/apps/restore_app.sh
exec env LD_LIBRARY_PATH="${PRIV_DIR}/lib:\${LD_LIBRARY_PATH}" "${PRIV_DIR}/${EXE}" "\$@"
WRAPPER
  $SUDO chmod 0755 "${BIN_DIR}/${INSTALL_AS}"
  echo "restore_app: installed ${EXE} as ${BIN_DIR}/${INSTALL_AS} (bundled libs)" >&2
  exit 0
fi

# No bundle cached -- an exe written before this change, or one with no
# collectable dependencies. Install exactly as before.
$SUDO install -D -m 0755 "${TMP_DIR}/${EXE}" "${BIN_DIR}/${INSTALL_AS}"
echo "restore_app: installed ${EXE} as ${BIN_DIR}/${INSTALL_AS}" >&2
