apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    category: security
    tool: helm
spec:
  project: default
  info:
  - name: "External Secrets Operator (ESO):"
    value: "Acts as proxy to a Cloud Secrets Store, enabling Kubernetes Secrets creation from secret values stored remotely"
  source:
    repoURL: git@github.com:SanabriaRusso/baseline-templates.git
    targetRevision: HEAD
    path: "external-secrets-operator/infra-canada"
    helm:
      releaseName: external-secrets
      values: |
        external-secrets:
          commonLabels:
            o1labs.org/gcp-cluster: mina.infra.canada
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
