package config

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"time"
)

// WARN: ensure we're always using the same consensus param here and in mina-local-network!
// TODO: make these configurable
const ProtocolK = 10
const ProtocolSlotPerEpoch = 48

// Config represents the application configuration parameters
type Config struct {
	// Executable paths
	MainMinaExe              string
	MainRuntimeGenesisLedger string
	ForkMinaExe              string
	ForkRuntimeGenesisLedger string

	// Root folder for everything generated by `mina-local-network.sh`
	Root string

	SeedStartPort        int
	SnarkCoordinatorPort int
	WhaleStartPort       int
	FishStartPort        int
	NodeStartPort        int

	// Slot configuration
	SlotTxEnd    int
	SlotChainEnd int

	// Best chain query configuration, number of slots
	BestChainQueryFrom int

	// Slot duration in seconds
	MainSlot int
	ForkSlot int

	MainDelayMin int
	HfSlotDelta  int

	// Configuration for network sizes
	NumWhales int
	NumFish   int
	NumNodes  int

	// When set, the seed and/or snark coordinator daemons also run as whale block
	// producers (consuming the leading whale accounts) instead of those whales
	// being spawned as standalone daemons. With both enabled and NumWhales=2 this
	// collapses the topology to 2 Mina nodes (seed+whale, snark-coordinator+whale).
	SeedIsWhale             bool
	SnarkCoordinatorIsWhale bool

	// Interval of sending payments in second
	PaymentInterval int

	// Script directory path
	ScriptDir string

	// Shutdown timeout in minutes before forcing kill
	ShutdownTimeoutMinutes int

	// Timing configuration (in seconds)
	PollingIntervalSeconds        int // Interval for polling height checks
	ForkConfigRetryDelaySeconds   int // Delay between fork config fetch retries
	ForkConfigMaxRetries          int // Max number of retries for fork config fetch
	NoNewBlocksWaitSeconds        int // Wait time to verify no new blocks after chain end
	UserCommandCheckMaxIterations int // Max iterations to check for user commands in blocks
	ForkEarliestBlockMaxRetries   int // Max retries to wait for earliest block in fork network
	HTTPClientTimeoutSeconds      int // HTTP client timeout for GraphQL requests
	ClientMaxRetries              int // Max number of retries for client requests

	ForkMethods ForkMethodSet

	DaemonInfos []DaemonInfo

	// Vesting-account test (see vesting.go). When enabled, a timed account that
	// only starts vesting *after* the hardfork slot is injected into the pre-fork
	// genesis ledger, and its timing is checked after the fork to ensure the Mesa
	// slot-reduction update was applied correctly.
	VestingTestEnabled bool
	// Public key of the injected vesting account (filled in at runtime by
	// SetupVestingAccount).
	VestingAccountPubKey string
	// Path to the temporary JSON file holding the extra genesis account that is
	// passed to mina-local-network.sh (filled in at runtime).
	VestingExtraAccountFile string

	// ---- Archive bug reproduction (#18941 tokens_value_key + element_ids btree
	// overflow) ----
	//
	// When ReproArchiveBugs is set, the test drives a custom-token ITN load on the
	// pre-fork (compatible) network so a real OWNED custom token is archived, then
	// (at the fork transition) migrates the shared archive DB to the Mesa schema,
	// and on the post-fork (Mesa) network drives a max-cost zkApp load and probes
	// the archive for both bugs. With the buggy archive binary + the migration that
	// keeps the element_ids UNIQUE both bugs reproduce and the test FAILS (non-zero
	// exit); with the fixed archive binary + the element_ids-dropping migration
	// neither reproduces and the test passes.
	ReproArchiveBugs bool
	// Postgres connection for the shared archive DB. ArchivePgUri is the full URI
	// used by detection/probes; the host/port/user/db parts are what
	// mina-local-network.sh consumes to wire the live archive node.
	ArchivePgUri  string
	ArchivePgHost string
	ArchivePgPort int
	ArchivePgUser string
	ArchivePgDb   string
	// Archive node wiring: port for the live archive in each phase, and the
	// protocol-appropriate archive binaries (compatible pre-fork, Mesa post-fork).
	ArchivePort      int
	MainArchiveExe   string
	ForkArchiveExe   string
	CreateSchemaFile string
	// Bug A probe: the Mesa mina-archive binary started with the fork genesis config
	// to trigger add_genesis_accounts (defaults to ForkArchiveExe).
	ProbeArchiveExe string
	// Berkeley->Mesa migration SQL applied at the fork transition. The file choice
	// (v0.0.5 keeps the element_ids UNIQUE = buggy; v0.0.6 drops it = fixed) is what
	// makes Bug B reproduce or not.
	MigrationSql string
	// ITN auth: path the ed25519 key PEM is written to (a sibling of Root if empty;
	// the test signs in-process, so the file is for debugging only). ItnPubKey is the
	// base64 public key, filled in at runtime and passed to the daemon via --itn-keys.
	ItnKeyPath string
	ItnPubKey  string
}

// Vesting-account test parameters. All amounts are in nanomina.
//
// The account is "not yet vesting" at the hardfork slot (its cliff is
// VestingCliffOffsetSlots slots *after* the hardfork slot) and fully unlocks at
// its cliff (cliff_amount == initial_minimum_balance). The Mesa slot-reduction
// update therefore must double the vesting period and push the cliff out to
// hardfork_slot + 2*VestingCliffOffsetSlots. See
// src/lib/mina_base/account_timing.ml:actively_vesting_hardfork_adjustment.
//
// VestingCliffOffsetSlots is chosen so that the *buggy* (un-migrated) cliff
// (hardfork_slot + offset) falls before, and the *correct* migrated cliff
// (hardfork_slot + 2*offset) falls after, the slot at which the fork network
// becomes queryable (BestChainQueryFrom + genesisSlot, default 25 + 68 = 93).
// This lets the liquid-balance check observe the account still locked under
// correct migration while it would already be unlocked under the bug.
const (
	VestingBalanceNanomina  = 100 * 1_000_000_000
	VestingCliffOffsetSlots = 15
	VestingPreForkPeriod    = 1
)

// HardforkSlot is the global slot since genesis at which the fork network's
// genesis is set; this is the slot used by the migration to adjust vesting
// parameters. It matches expectedGenesisSlot computed in RunForkNetworkPhase.
func (c *Config) HardforkSlot() int {
	return c.SlotChainEnd + c.HfSlotDelta
}

// VestingPreForkCliffTime is the cliff_time configured for the injected account
// in the pre-fork ledger (before any migration adjustment).
func (c *Config) VestingPreForkCliffTime() int {
	return c.HardforkSlot() + VestingCliffOffsetSlots
}

// DefaultConfig returns the default configuration with values
// matching those in the original shell script
func DefaultConfig() *Config {
	return &Config{
		SlotTxEnd:                     30,
		SlotChainEnd:                  38, // SlotTxEnd + 8
		BestChainQueryFrom:            25,
		MainSlot:                      30,
		ForkSlot:                      30,
		MainDelayMin:                  7,
		HfSlotDelta:                   30, // if this is too small and fork network is spawned after fork genesis, it'll fail to create any block
		NumWhales:                     2,
		NumFish:                       0,
		NumNodes:                      0,
		SeedIsWhale:                   true,
		SnarkCoordinatorIsWhale:       true,
		PaymentInterval:               20,
		ShutdownTimeoutMinutes:        10,
		PollingIntervalSeconds:        8,
		ForkConfigRetryDelaySeconds:   60,
		ForkConfigMaxRetries:          15,
		NoNewBlocksWaitSeconds:        300, // 5 minutes
		UserCommandCheckMaxIterations: 10,
		ForkEarliestBlockMaxRetries:   10,
		HTTPClientTimeoutSeconds:      600,
		// ^ fork config take really long time to complete (2-3 minutes)
		ClientMaxRetries: 5,

		// Archive bug reproduction defaults.
		ArchivePgHost: "localhost",
		ArchivePgPort: 5432,
		ArchivePgUser: "agent",
		ArchivePgDb:   "archive",
		ArchivePort:   3086,

		SeedStartPort:        3000,
		SnarkCoordinatorPort: 7000,
		WhaleStartPort:       4000,
		FishStartPort:        5000,
		NodeStartPort:        6000,

		ForkMethods: make(ForkMethodSet),

		VestingTestEnabled: true,
	}
}

// TODO: ensure integrity of ports in hf-test-go and mina-local-network

type PortType int

const (
	PORT_CLIENT PortType = iota
	PORT_REST
	PORT_EXTERNAL
	PORT_DAEMON_METRICS
	PORT_LIBP2P_METRICS
)
const PORT_PER_NODE = 6

type DaemonInfo struct {
	StartPort  int
	Name       string
	ForkMethod ForkMethod
}

func (d *DaemonInfo) Port(ty PortType) int {
	return d.StartPort + int(ty)
}

func (d *DaemonInfo) NodeDirRel(root string) string {
	return filepath.Join(root, "nodes", d.Name)
}

func (c *Config) InitDaemonInfos() error {
	// Build the daemon slots first (without fork methods); methods are assigned
	// below so that every requested method is guaranteed at least one daemon.
	result := []DaemonInfo{
		{
			StartPort: c.SeedStartPort,
			Name:      "seed",
		},
		{
			StartPort: c.SnarkCoordinatorPort,
			Name:      "snark_coordinator",
		},
	}

	// Whale accounts consumed by the seed / snark coordinator (when they double as
	// block producers) are not spawned as standalone whale daemons; mirror the
	// WHALE_STANDALONE_START logic in mina-local-network.sh.
	standaloneWhaleStart := 0
	if c.SeedIsWhale && standaloneWhaleStart < c.NumWhales {
		standaloneWhaleStart++
	}
	if c.SnarkCoordinatorIsWhale && standaloneWhaleStart < c.NumWhales {
		standaloneWhaleStart++
	}

	for whale_id := standaloneWhaleStart; whale_id < c.NumWhales; whale_id++ {
		result = append(result, DaemonInfo{
			StartPort: c.WhaleStartPort + whale_id*PORT_PER_NODE,
			Name:      fmt.Sprintf("whale_%d", whale_id),
		})
	}

	for fish_id := 0; fish_id < c.NumFish; fish_id++ {
		result = append(result, DaemonInfo{
			StartPort: c.FishStartPort + fish_id*PORT_PER_NODE,
			Name:      fmt.Sprintf("fish_%d", fish_id),
		})
	}

	for node_id := 0; node_id < c.NumNodes; node_id++ {
		result = append(result, DaemonInfo{
			StartPort: c.NodeStartPort + node_id*PORT_PER_NODE,
			Name:      fmt.Sprintf("plain_%d", node_id),
		})
	}

	// Assign fork methods so that every method passed via --allow-fork-method is
	// used by at least one daemon. Mixing migration paths that disagree on a given
	// ledger (e.g. legacy via runtime_genesis_ledger vs auto/advanced via
	// migrate_to_mesa) makes the post-fork nodes compute different genesis ledger
	// hashes and fail to peer, so coverage must be explicit and bounded by the
	// number of daemons rather than left to chance.
	methods := c.ForkMethods.Methods()
	if len(methods) == 0 {
		return fmt.Errorf("no fork method supplied; pass at least one --allow-fork-method")
	}
	if len(methods) > len(result) {
		return fmt.Errorf(
			"requested %d fork method(s) %s but the network only has %d daemon(s); "+
				"each requested method needs its own daemon. Either request fewer methods "+
				"(drop some --allow-fork-method flags) or grow the network with "+
				"--num-whales / --num-fish / --num-nodes.",
			len(methods), c.ForkMethods.String(), len(result))
	}

	// Auto daemons exit at slot-chain-end (migrate-exit), so an all-auto network
	// leaves nothing alive for the post-chain-end checks. Require a non-auto
	// method; `advanced` exercises the same migrate_to_mesa path as auto.
	hasNonAuto := false
	for _, m := range methods {
		if m != Auto {
			hasNonAuto = true
		}
	}
	if !hasNonAuto {
		return fmt.Errorf(
			"only the 'auto' fork method was requested, but auto daemons exit at " +
				"slot-chain-end and the post-fork checks need a still-running daemon. Add a " +
				"non-auto method, e.g. --allow-fork-method advanced (which exercises the same " +
				"migration path as auto).")
	}

	// Give the first len(methods) slots one distinct method each, fill the rest
	// randomly, then shuffle so the assignment isn't tied to daemon position.
	assignment := make([]ForkMethod, len(result))
	copy(assignment, methods)
	for i := len(methods); i < len(assignment); i++ {
		assignment[i] = methods[rand.Intn(len(methods))]
	}
	rand.Shuffle(len(assignment), func(i, j int) {
		assignment[i], assignment[j] = assignment[j], assignment[i]
	})
	for i := range result {
		result[i].ForkMethod = assignment[i]
	}

	c.DaemonInfos = result
	return nil
}

func (c *Config) AllDaemonSatisfying(tag string, pred func(*DaemonInfo) bool) []*DaemonInfo {
	candidates := []*DaemonInfo{}
	for i := range c.DaemonInfos {
		info := &c.DaemonInfos[i]
		if pred(info) {
			candidates = append(candidates, info)
		}
	}
	return candidates
}

func (c *Config) AnyDaemon() *DaemonInfo {
	if len(c.DaemonInfos) == 0 {
		panic(fmt.Sprintf("No daemon is in network!"))
	}
	return &c.DaemonInfos[rand.Intn(len(c.DaemonInfos))]
}

func (c *Config) AnyDaemonSatisfying(tag string, pred func(*DaemonInfo) bool) *DaemonInfo {
	candidates := c.AllDaemonSatisfying(tag, pred)
	if len(candidates) == 0 {
		panic(fmt.Sprintf("No daemon satify condition %s!", tag))
	}
	return candidates[rand.Intn(len(candidates))]
}

func (c *Config) ForkGenesisTsGivenMainGenesisTs(mainGenesisTs int64) int64 {
	forkGenesisSlot := c.SlotChainEnd + c.HfSlotDelta
	return mainGenesisTs + int64(forkGenesisSlot*c.MainSlot)
}

func (c *Config) MainSlotChainEnd(mainGenesisTs int64) time.Time {
	return time.Unix(mainGenesisTs+int64(c.SlotChainEnd*c.MainSlot), 0)
}

// Validate checks if the configuration is valid
func (c *Config) Validate() error {
	// Check if required paths are specified
	if c.MainMinaExe == "" {
		return ErrMissingMainMinaExe
	}
	if c.MainRuntimeGenesisLedger == "" {
		return ErrMissingMainRuntimeGenesisLedger
	}
	if c.ForkMinaExe == "" {
		return ErrMissingForkMinaExe
	}
	if c.ForkRuntimeGenesisLedger == "" {
		return ErrMissingForkRuntimeGenesisLedger
	}
	if c.ScriptDir == "" {
		return ErrMissingScriptDir
	}
	if c.Root == "" {
		return ErrMissingRoot
	}

	// Check if executables exist and have proper permissions
	if err := validateExecutable(c.MainMinaExe); err != nil {
		return FileValidationError(c.MainMinaExe, err)
	}
	if err := validateExecutable(c.MainRuntimeGenesisLedger); err != nil {
		return FileValidationError(c.MainRuntimeGenesisLedger, err)
	}
	if err := validateExecutable(c.ForkMinaExe); err != nil {
		return FileValidationError(c.ForkMinaExe, err)
	}
	if err := validateExecutable(c.ForkRuntimeGenesisLedger); err != nil {
		return FileValidationError(c.ForkRuntimeGenesisLedger, err)
	}

	if err := validateScriptDir(c.ScriptDir); err != nil {
		return FileValidationError(c.ScriptDir, err)
	}

	return nil
}

// FormatTimestamp formats a UNIX timestamp into the format used by the shell script
func FormatTimestamp(unixTs int64) string {
	t := time.Unix(unixTs, 0).UTC()
	return t.Format(time.RFC3339)
}

// validateExecutable checks if a file exists and has executable permissions
func validateExecutable(path string) error {
	// Check if file exists
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return ErrFileNotExists
		}
		return err
	}

	// Check if it's a regular file (not a directory)
	if info.IsDir() {
		return fmt.Errorf("path is a directory, not an executable file")
	}

	// Check executable permission - mode & 0111 is checking for any execution bit (user, group, or others)
	if info.Mode().Perm()&0111 == 0 {
		return ErrNotExecutable
	}

	return nil
}

func validateScriptDir(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return ErrNotADir
	}

	return nil
}
