package config

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"time"

	"github.com/MinaProtocol/mina/src/app/hardfork_test/src/internal/plan"
)

// SlotEndUnset marks SlotTxEnd/SlotChainEnd as not given on the command line,
// so ResolveSlotEnds can tell "leave it to me" from a deliberate choice. Zero is
// safe as the sentinel: a chain that ends at slot 0 has no run in it.
const SlotEndUnset = 0

// SlotChainEndGap is how many slots the chain keeps producing (empty) blocks
// after transactions stop, before it stops entirely.
//
// The fork is cut at the last block before slot_tx_end, and this gap is what
// buries it — the deeper that block is when the chain stops, the less room the
// nodes have to disagree about which block it was.
//
// A real fork wants more than k *blocks* of depth. This is 8 *slots*, which at
// the ~70% slot occupancy this network runs is only ~5-6 blocks against k=10 —
// deliberately short of the real bar, because at 2-3 nodes with no adversary the
// chain does not reorg, and every extra slot costs a slot duration of CI wall
// clock. Good enough here, and nothing rests on the approximation: the test
// checks that the nodes *actually* agree on the fork block
// (ConsensusAcrossNodesAfterSlotChainEnd) rather than trusting depth to make
// them. If this is ever too small, that check fails and names this gap.
const SlotChainEndGap = 8

// slot_tx_end is drawn from [RandomSlotTxEndMin, RandomSlotTxEndMax] inclusive
// when not given, so runs sweep a range of fork points rather than forking at
// the same slot every time.
const (
	RandomSlotTxEndMin = 30
	RandomSlotTxEndMax = 149
)

// Config represents the application configuration parameters
type Config struct {
	// Executable paths
	MainMinaExe              string
	MainRuntimeGenesisLedger string
	ForkMinaExe              string
	ForkRuntimeGenesisLedger string

	// Root folder for everything generated by `mina-local-network.sh`
	Root string

	// Slot configuration. Both are SlotEndUnset until ResolveSlotEnds fills them
	// in, so that "not given" is distinguishable from an explicit value.
	SlotTxEnd    int
	SlotChainEnd int

	// Best chain query configuration, number of slots
	BestChainQueryFrom int

	// Slot duration in seconds
	MainSlot int
	ForkSlot int

	MainDelayMin int

	// HfSlotDelta is how many slots after SlotChainEnd the fork network's genesis
	// falls. It is fixed before the run starts — HardforkSlot() feeds the vesting
	// account injected into the pre-fork genesis ledger — so it cannot adapt to how
	// long the fork actually takes. The daemons' idle wait before fork genesis is
	// therefore a residual: HfSlotDelta*MainSlot minus the work between chain end
	// and the fork network being ready. That residual is also the entire margin: if
	// the work overruns it, the daemons come up after genesis and produce no block.
	//
	// Measured across 12 passing CI runs, that work is 413-446s (mean 430s, sigma
	// ~10s), of which NoNewBlocksWaitSeconds is 300s.
	HfSlotDelta int

	// TopologyFile is the path to the topology preset to run, one of
	// scripts/mina-local-network/presets/hf-test-*.jsonc. It is the source of
	// truth for which daemons exist, what they are called, and what they can do.
	// Resolving a name to a path is the caller's job (see
	// scripts/hardfork/build-and-test.sh), so this is always a path.
	TopologyFile string

	// Interval of sending payments in second
	PaymentInterval int

	// Script directory path
	ScriptDir string

	// Shutdown timeout in minutes before forcing kill
	ShutdownTimeoutMinutes int

	// Timing configuration (in seconds)
	PollingIntervalSeconds        int // Interval for polling height checks
	ForkConfigRetryDelaySeconds   int // Delay between fork config fetch retries
	ForkConfigMaxRetries          int // Max number of retries for fork config fetch
	NoNewBlocksWaitSeconds        int // Wait time to verify no new blocks after chain end
	UserCommandCheckMaxIterations int // Max iterations to check for user commands in blocks
	ForkEarliestBlockMaxRetries   int // Max retries to wait for earliest block in fork network
	HTTPClientTimeoutSeconds      int // HTTP client timeout for GraphQL requests
	ClientMaxRetries              int // Max number of retries for client requests

	ForkMethods ForkMethodSet

	DaemonInfos []DaemonInfo

	// Vesting-account test (see vesting.go). When enabled, the hardfork test
	// injects a timed account into the pre-fork genesis ledger, and checks its
	// timing after the fork to ensure the Mesa slot-reduction update was applied
	// correctly.
	VestingTestEnabled bool
}

// HardforkSlot is the global slot since genesis at which the fork network's
// genesis is set; this is the slot used by the migration to adjust vesting
// parameters. It matches expectedGenesisSlot computed in RunForkNetworkPhase.
func (c *Config) HardforkSlot() int {
	return c.SlotChainEnd + c.HfSlotDelta
}

// DefaultConfig returns the default configuration with values
// matching those in the original shell script
func DefaultConfig() *Config {
	return &Config{
		SlotTxEnd:                     SlotEndUnset, // randomized by ResolveSlotEnds
		SlotChainEnd:                  SlotEndUnset, // derived by ResolveSlotEnds
		BestChainQueryFrom:            25,
		MainSlot:                      30,
		ForkSlot:                      30,
		MainDelayMin:                  4,  // must exceed materialize+spawn time (~2min) or nodes start after chain start time and miss early slots
		HfSlotDelta:                   18, // must exceed the work between chain end and the fork network being ready, or the daemons start after fork genesis and produce no block
		PaymentInterval:               20,
		ShutdownTimeoutMinutes:        10,
		PollingIntervalSeconds:        8,
		ForkConfigRetryDelaySeconds:   60,
		ForkConfigMaxRetries:          15,
		NoNewBlocksWaitSeconds:        300, // 5 minutes
		UserCommandCheckMaxIterations: 10,
		ForkEarliestBlockMaxRetries:   10,
		HTTPClientTimeoutSeconds:      600,
		// ^ a backstop for a hung daemon, not an expected latency: measured across 15
		// CI runs, the fork config query returns in under a second with no retries,
		// and generating it together with the ledgers takes 17-51s.
		ClientMaxRetries: 5,

		ForkMethods: make(ForkMethodSet),

		VestingTestEnabled: true,
	}
}

type PortType int

const (
	PORT_CLIENT PortType = iota
	PORT_REST
	PORT_EXTERNAL
	PORT_DAEMON_METRICS
	PORT_LIBP2P_METRICS
)

// portEndpointNames maps each PortType to its endpoint name in the network
// plan. These names are the planner's, not ours — see mln/topology.py.
var portEndpointNames = map[PortType]string{
	PORT_CLIENT:         "client",
	PORT_REST:           "rest",
	PORT_EXTERNAL:       "external",
	PORT_DAEMON_METRICS: "metrics",
	PORT_LIBP2P_METRICS: "libp2p_metrics",
}

func (ty PortType) String() string {
	if n, ok := portEndpointNames[ty]; ok {
		return n
	}
	return fmt.Sprintf("PortType(%d)", int(ty))
}

type DaemonInfo struct {
	Name       string
	ForkMethod ForkMethod

	// Ports the planner allocated for this daemon, keyed by PortType.
	// Populated by Config.PopulatePortsFromPlan once the plan exists.
	Ports map[PortType]int
}

// Port returns the planner-allocated port for *ty*.
//
// Panics if the ports have not been read from the plan yet: every caller
// queries a live daemon, so an unpopulated port means the plan was never read,
// which is a wiring error rather than a runtime condition.
func (d *DaemonInfo) Port(ty PortType) int {
	port, ok := d.Ports[ty]
	if !ok {
		panic(fmt.Sprintf(
			"daemon %q: %s port not populated from the network plan; "+
				"Config.PopulatePortsFromPlan must run after the planner and before any daemon is queried",
			d.Name, ty))
	}
	return port
}

func (d *DaemonInfo) NodeDirRel(root string) string {
	return filepath.Join(root, "nodes", d.Name)
}

// PopulatePortsFromPlan fills in each daemon's ports from the network plan.
//
// The planner allocates ports, so they are unknowable until it has run: this
// must be called after `plan topology` / `patch topology` writes the plan, and
// before any daemon is queried. Names are the join key, so a daemon the plan
// does not declare is reported rather than silently left portless.
func (c *Config) PopulatePortsFromPlan(p *plan.Plan) error {
	for i := range c.DaemonInfos {
		di := &c.DaemonInfos[i]

		node, ok := p.Node(di.Name)
		if !ok {
			return fmt.Errorf(
				"network plan declares no node %q (plan has: %v); "+
					"the topology generator and InitDaemonInfos disagree on the node set",
				di.Name, p.NodeNames())
		}

		ports := make(map[PortType]int, len(portEndpointNames))
		for ty, name := range portEndpointNames {
			ep, ok := node.Endpoints[name]
			if !ok {
				return fmt.Errorf("network plan node %q has no %q endpoint", di.Name, name)
			}
			ports[ty] = ep.Port
		}
		di.Ports = ports
	}
	return nil
}

// InitDaemonInfos builds the daemon list from *nodeNames*, the nodes declared
// by the topology file, and assigns each a fork method.
//
// *seedName* must name the node carrying the p2p_seed capability; it is
// excluded from the Auto fork method (see the guard below). It is passed in
// rather than inferred from position because nodeNames has no meaningful order.
//
// The topology is the source of truth for which daemons exist, so the two
// cannot disagree. Ports are absent by design: the planner allocates them from
// the topology and PopulatePortsFromPlan fills them in afterwards.
func (c *Config) InitDaemonInfos(nodeNames []string, seedName string) error {
	result := make([]DaemonInfo, 0, len(nodeNames))
	seedIdx := -1
	for _, name := range nodeNames {
		if name == seedName {
			seedIdx = len(result)
		}
		result = append(result, DaemonInfo{Name: name})
	}
	if seedIdx < 0 {
		return fmt.Errorf("seed node %q is not among the topology's nodes (%v)", seedName, nodeNames)
	}

	// Assign fork methods so that every method passed via --allow-fork-method is
	// used by at least one daemon. Mixing migration paths that disagree on a given
	// ledger (e.g. legacy via runtime_genesis_ledger vs auto/advanced via
	// migrate_to_mesa) makes the post-fork nodes compute different genesis ledger
	// hashes and fail to peer, so coverage must be explicit and bounded by the
	// number of daemons rather than left to chance.
	methods := c.ForkMethods.Methods()
	if len(methods) == 0 {
		return fmt.Errorf("no fork method supplied; pass at least one --allow-fork-method")
	}
	if len(methods) > len(result) {
		return fmt.Errorf(
			"requested %d fork method(s) %s but the topology only has %d daemon(s); "+
				"each requested method needs its own daemon. Either request fewer methods "+
				"(drop some --allow-fork-method flags) or select a topology with more "+
				"nodes via --topology-file.",
			len(methods), c.ForkMethods.String(), len(result))
	}

	// Auto daemons exit at slot-chain-end (migrate-exit), so an all-auto network
	// leaves nothing alive for the post-chain-end checks. Require a non-auto
	// method; `advanced` exercises the same migrate_to_mesa path as auto.
	hasNonAuto := false
	for _, m := range methods {
		if m != Auto {
			hasNonAuto = true
		}
	}
	if !hasNonAuto {
		return fmt.Errorf(
			"only the 'auto' fork method was requested, but auto daemons exit at " +
				"slot-chain-end and the post-fork checks need a still-running daemon. Add a " +
				"non-auto method, e.g. --allow-fork-method advanced (which exercises the same " +
				"migration path as auto).")
	}

	// Give the first len(methods) slots one distinct method each, fill the rest
	// randomly, then shuffle so the assignment isn't tied to daemon position.
	assignment := make([]ForkMethod, len(result))
	copy(assignment, methods)
	for i := len(methods); i < len(assignment); i++ {
		assignment[i] = methods[rand.Intn(len(methods))]
	}
	rand.Shuffle(len(assignment), func(i, j int) {
		assignment[i], assignment[j] = assignment[j], assignment[i]
	})
	for i := range result {
		result[i].ForkMethod = assignment[i]
	}

	// Post-shuffle guard: never give the seed daemon the Auto fork method. The
	// seed is the sole P2P hub — if it exits via auto-fork migrate-exit, the
	// remaining nodes lose their seed, diverge onto different forks, and the
	// consensus check fails. Swap with the first non-seed daemon that has a
	// non-Auto method.
	if result[seedIdx].ForkMethod == Auto {
		swapped := false
		for i := range result {
			if i != seedIdx && result[i].ForkMethod != Auto {
				result[seedIdx].ForkMethod, result[i].ForkMethod = result[i].ForkMethod, result[seedIdx].ForkMethod
				swapped = true
				break
			}
		}
		if !swapped {
			// This path is unreachable: the all-auto validation at lines 231-242
			// already rejects a method set consisting only of Auto before the
			// assignment loop. If this ever happens, the assignment invariants are
			// broken and the test must stop instead of running with an auto seed.
			return fmt.Errorf("seed daemon was assigned Auto fork method and no non-Auto daemon exists to swap with")
		}
	}

	c.DaemonInfos = result
	return nil
}

func (c *Config) AllDaemonSatisfying(tag string, pred func(*DaemonInfo) bool) []*DaemonInfo {
	candidates := []*DaemonInfo{}
	for i := range c.DaemonInfos {
		info := &c.DaemonInfos[i]
		if pred(info) {
			candidates = append(candidates, info)
		}
	}
	return candidates
}

func (c *Config) AnyDaemon() *DaemonInfo {
	if len(c.DaemonInfos) == 0 {
		panic(fmt.Sprintf("No daemon is in network!"))
	}
	return &c.DaemonInfos[rand.Intn(len(c.DaemonInfos))]
}

func (c *Config) AnyDaemonSatisfying(tag string, pred func(*DaemonInfo) bool) *DaemonInfo {
	candidates := c.AllDaemonSatisfying(tag, pred)
	if len(candidates) == 0 {
		panic(fmt.Sprintf("No daemon satify condition %s!", tag))
	}
	return candidates[rand.Intn(len(candidates))]
}

// ResolveSlotEnds fills in slot_tx_end and slot_chain_end where they were not
// given, and returns a description of what it settled on.
//
// The caller must log that description. slot_tx_end is randomized when absent,
// so a failing run cannot be reproduced unless the value it ran with is on the
// record — passing the logged value back reproduces the run exactly, as nothing
// else about the slot schedule is random.
func (c *Config) ResolveSlotEnds() (string, error) {
	txOrigin := "given"
	if c.SlotTxEnd == SlotEndUnset {
		c.SlotTxEnd = RandomSlotTxEndMin + rand.Intn(RandomSlotTxEndMax-RandomSlotTxEndMin+1)
		txOrigin = "randomized"
	}

	chainOrigin := "given"
	if c.SlotChainEnd == SlotEndUnset {
		c.SlotChainEnd = c.SlotTxEnd + SlotChainEndGap
		chainOrigin = fmt.Sprintf("derived as slot-tx-end + %d", SlotChainEndGap)
	} else if c.SlotChainEnd <= c.SlotTxEnd {
		// The chain must outlive transactions: the fork is cut at the last block
		// before slot-tx-end, and the blocks between the two are what bury it.
		return "", fmt.Errorf(
			"--slot-chain-end (%d) must be greater than --slot-tx-end (%d)",
			c.SlotChainEnd, c.SlotTxEnd)
	}

	return fmt.Sprintf("slot-tx-end %d (%s), slot-chain-end %d (%s)",
		c.SlotTxEnd, txOrigin, c.SlotChainEnd, chainOrigin), nil
}

func (c *Config) ForkGenesisTsGivenMainGenesisTs(mainGenesisTs int64) int64 {
	forkGenesisSlot := c.SlotChainEnd + c.HfSlotDelta
	return mainGenesisTs + int64(forkGenesisSlot*c.MainSlot)
}

func (c *Config) MainSlotChainEnd(mainGenesisTs int64) time.Time {
	return time.Unix(mainGenesisTs+int64(c.SlotChainEnd*c.MainSlot), 0)
}

// Validate checks if the configuration is valid
func (c *Config) Validate() error {
	// Check if required paths are specified
	if c.MainMinaExe == "" {
		return ErrMissingMainMinaExe
	}
	if c.MainRuntimeGenesisLedger == "" {
		return ErrMissingMainRuntimeGenesisLedger
	}
	if c.ForkMinaExe == "" {
		return ErrMissingForkMinaExe
	}
	if c.ForkRuntimeGenesisLedger == "" {
		return ErrMissingForkRuntimeGenesisLedger
	}
	if c.ScriptDir == "" {
		return ErrMissingScriptDir
	}
	if c.TopologyFile == "" {
		return ErrMissingTopologyFile
	}
	if c.Root == "" {
		return ErrMissingRoot
	}

	// Check if executables exist and have proper permissions
	if err := validateExecutable(c.MainMinaExe); err != nil {
		return FileValidationError(c.MainMinaExe, err)
	}
	if err := validateExecutable(c.MainRuntimeGenesisLedger); err != nil {
		return FileValidationError(c.MainRuntimeGenesisLedger, err)
	}
	if err := validateExecutable(c.ForkMinaExe); err != nil {
		return FileValidationError(c.ForkMinaExe, err)
	}
	if err := validateExecutable(c.ForkRuntimeGenesisLedger); err != nil {
		return FileValidationError(c.ForkRuntimeGenesisLedger, err)
	}

	if err := validateScriptDir(c.ScriptDir); err != nil {
		return FileValidationError(c.ScriptDir, err)
	}

	if err := validateTopologyFile(c.TopologyFile); err != nil {
		return FileValidationError(c.TopologyFile, err)
	}

	return nil
}

// FormatTimestamp formats a UNIX timestamp into the format used by the shell script
func FormatTimestamp(unixTs int64) string {
	t := time.Unix(unixTs, 0).UTC()
	return t.Format(time.RFC3339)
}

// validateExecutable checks if a file exists and has executable permissions
func validateExecutable(path string) error {
	// Check if file exists
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return ErrFileNotExists
		}
		return err
	}

	// Check if it's a regular file (not a directory)
	if info.IsDir() {
		return fmt.Errorf("path is a directory, not an executable file")
	}

	// Check executable permission - mode & 0111 is checking for any execution bit (user, group, or others)
	if info.Mode().Perm()&0111 == 0 {
		return ErrNotExecutable
	}

	return nil
}

func validateScriptDir(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return ErrNotADir
	}

	return nil
}

// validateTopologyFile checks that the topology preset exists and is a file.
func validateTopologyFile(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return ErrFileNotExists
		}
		return err
	}
	if info.IsDir() {
		return ErrNotAFile
	}

	return nil
}
