{
 "title": "Simplified Mainnet Overview",
 "time": { "from": "2021-03-17T00:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "testnet",
    "query": {
     "query": "Coda_Runtime_process_uptime_ms_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_watchdog_nodes_queried{testnet=\"$testnet\"}",
     "legendFormat": "# nodes queried"
    },
    {
     "expr": "Coda_watchdog_nodes_responded{testnet=\"$testnet\"}",
     "legendFormat": "# nodes responded with their statuses"
    },
    {
     "expr": "Coda_watchdog_node_status_errors{testnet=\"$testnet\"}",
     "legendFormat": "Total # errors"
    },
    {
     "expr": "Coda_watchdog_connection_refused{testnet=\"$testnet\"}",
     "legendFormat": "# connection refused errors"
    },
    {
     "expr": "Coda_watchdog_deadline_exceeded{testnet=\"$testnet\"}",
     "legendFormat": "# context deadline exceeded errors"
    },
    {
     "expr": "Coda_watchdog_failed_negotiation{testnet=\"$testnet\"}",
     "legendFormat": "# failed negotiation errors"
    },
    {
     "expr": "Coda_watchdog_size_limit_exceeded{testnet=\"$testnet\"}",
     "legendFormat": "# size limit exceeded errors"
    },
    {
     "expr": "Coda_watchdog_timed_out{testnet=\"$testnet\"}",
     "legendFormat": "# time-out errors"
    },
    {
     "expr": "Coda_watchdog_stream_reset{testnet=\"$testnet\"}",
     "legendFormat": "# stream reset errors"
    },
    {
     "expr": "Coda_watchdog_node_status_other_errors{testnet=\"$testnet\"}",
     "legendFormat": "# other errors"
    }
   ]
  },
  {
   "title": "Block Height by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_max_blocklength_observed{testnet=\"$testnet\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "LowMinWindowDensity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_min_window_density {testnet=\"$testnet\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Hours of Uptime by Node",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Runtime_process_uptime_ms_total{testnet=\"$testnet\", role=\"seed\"} / 1000 / 60 / 60",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Scan State (Snark Work Required for Each Tree)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree0{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree0{testnet=\"$testnet\"})",
     "legendFormat": "Tree 0"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree1{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree1{testnet=\"$testnet\"})",
     "legendFormat": "Tree 1"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree2{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree2{testnet=\"$testnet\"})",
     "legendFormat": "Tree 2"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree3{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree3{testnet=\"$testnet\"})",
     "legendFormat": "Tree 3"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree4{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree4{testnet=\"$testnet\"})",
     "legendFormat": "Tree 4"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree5{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree5{testnet=\"$testnet\"})",
     "legendFormat": "Tree 5"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree6{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree6{testnet=\"$testnet\"})",
     "legendFormat": "Tree 6"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree7{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree7{testnet=\"$testnet\"})",
     "legendFormat": "Tree 7"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree8{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree8{testnet=\"$testnet\"})",
     "legendFormat": "Tree 8"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree9{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree9{testnet=\"$testnet\"})",
     "legendFormat": "Tree 9"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree10{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree10{testnet=\"$testnet\"})",
     "legendFormat": "Tree 10"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree11{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree11{testnet=\"$testnet\"})",
     "legendFormat": "Tree 11"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree12{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree12{testnet=\"$testnet\"})",
     "legendFormat": "Tree 12"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree13{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree13{testnet=\"$testnet\"})",
     "legendFormat": "Tree 13"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree14{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree14{testnet=\"$testnet\"})",
     "legendFormat": "Tree 14"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree15{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree15{testnet=\"$testnet\"})",
     "legendFormat": "Tree 15"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree16{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree16{testnet=\"$testnet\"})",
     "legendFormat": "Tree 16"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree17{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree17{testnet=\"$testnet\"})",
     "legendFormat": "Tree 17"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree18{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree18{testnet=\"$testnet\"})",
     "legendFormat": "Tree 18"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree19{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree19{testnet=\"$testnet\"})",
     "legendFormat": "Tree 19"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree20{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree20{testnet=\"$testnet\"})",
     "legendFormat": "Tree 20"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree21{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree21{testnet=\"$testnet\"})",
     "legendFormat": "Tree 21"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree22{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree22{testnet=\"$testnet\"})",
     "legendFormat": "Tree 22"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree23{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree23{testnet=\"$testnet\"})",
     "legendFormat": "Tree 23"
    },
    {
     "expr": "avg(Coda_Scan_state_base_snarks_required_tree24{testnet=\"$testnet\"}+ Coda_Scan_state_merge_snarks_required_tree24{testnet=\"$testnet\"})",
     "legendFormat": "Tree 24"
    }
   ]
  },
  {
   "title": "Network Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Network_peers{testnet=\"$testnet\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Fees in Blocks (10m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(Coda_Scan_state_transaction_fees_per_block{testnet=\"$testnet\", role=\"seed\"}[10m])) / 1000000000",
     "legendFormat": "Tx Fees Per Block"
    },
    {
     "expr": "avg(avg_over_time(Coda_Scan_state_snark_fees_per_block{testnet=\"$testnet\", role=\"seed\"}[10m])) / 1000000000  ",
     "legendFormat": "Snark Fees Per Block"
    },
    {
     "expr": "avg(avg_over_time(Coda_Scan_state_purchased_snark_work_per_block{testnet=\"$testnet\", role=\"seed\"}[10m])) / 1000000000",
     "legendFormat": "Snark Work Per Block"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$testnet\", pod=~\".*seed.*\"}) by (pod)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$testnet\", pod=~\".*seed.*\"}) ",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Observed Blocks Rate Of Increase (15m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(Coda_Transition_frontier_max_blocklength_observed{testnet=\"$testnet\"}[15m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{namespace=\"$testnet\", pod=~\".*seed.*\"}) by (pod)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "avg(container_fs_usage_bytes{namespace=\"$testnet\", pod=~\".*seed.*\"}) ",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(sum(container_fs_usage_bytes{namespace=\"$testnet\", pod=~\".*$role.*\"}) by (instance))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Block gossip latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Block_latency_gossip_time{testnet=\"$testnet\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "CPU Percent (Top 10)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (rate(container_cpu_user_seconds_total{namespace=\"$testnet\", pod=~\".*seed.*\"}[2m]))) * 100 / 4",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "SNARK Fee Breakdown",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(Coda_Snark_work_snark_fee_bucket{testnet=\"$testnet\"}[10m])) by (testnet, le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(Coda_Snark_work_snark_fee_bucket{testnet=\"$testnet\"}[10m])) by (testnet, le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(Coda_Snark_work_snark_fee_bucket{testnet=\"$testnet\"}[10m])) by (testnet, le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Live Memory Allocated by Node ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Coda_Runtime_ocaml_gc_live_words{testnet=\"$testnet\", role=\"seed\"} * 2 ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Transition Frontier Slot Fill Rate (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_slot_fill_rate{testnet=\"$testnet\", role=\"seed\"} * 100",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Long Async Cycles (90th Percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(Coda_Runtime_long_async_cycle_sum{testnet=\"$testnet\", role=\"seed\"}[5m])\n/\n  rate(Coda_Runtime_long_async_cycle_count{testnet=\"$testnet\", role=\"seed\"}[5m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum without (handler)(\n    rate(Coda_Runtime_long_async_cycle_bucket{testnet=\"$testnet\", role=\"seed\"}[5m])\n  )\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Libp2p Connection Count By Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Coda_active_connections_total{testnet=\"$testnet\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}