FROM ubuntu:18.04
# Run with `docker build --build-arg coda_deb_version=<version>`
ARG coda_deb_version
ARG deb_repo=release
RUN echo "Building image with version $coda_deb_version"

ADD scripts/run-demo.sh /run-demo.sh

ENV DEBIAN_FRONTEND=noninteractive
# Dependencies
RUN apt-get update --yes \
  && apt-get install --yes \
    apt-transport-https \
    curl \
    ca-certificates \
    dnsutils \
    dumb-init \
    jq \
    libffi6 \
    libgmp10 \
    libgomp1 \
    libjemalloc1 \
    libprocps6 \
    libssl1.1 \
    tzdata \
  && rm -rf /var/lib/apt/lists/*

ARG PK=B62qiZfzW27eavtPrnF6DeDSAKEjXuGFdkouC3T5STRa6rrYLiDUP2p
ARG MINA_CONFIG_DIR=/root/.mina-config

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_repo main" > /etc/apt/sources.list.d/o1.list \
  && apt-get update \
  && apt-get install mina-testnet-postake-medium-curves=$coda_deb_version -y --allow-downgrades \
  && mkdir /root/keys \
  && chmod go-rwx /root/keys \
  && mkdir -p --mode=700 ${MINA_CONFIG_DIR}/wallets/store/ \
  && echo "$PK" >  ${MINA_CONFIG_DIR}/wallets/store/$PK.pub \
  && echo '{"box_primitive":"xsalsa20poly1305","pw_primitive":"argon2i","nonce":"6pcvpWSLkMi393dT5VSLR6ft56AWKkCYRqJoYia","pwsalt":"ASoBkV3NsY7ZRuxztyPJdmJCiz3R","pwdiff":[134217728,6],"ciphertext":"Dmq1Qd8uNbZRT1NT7zVbn3eubpn9Myx9Je9ZQGTKDxUv4BoPNmZAGox18qVfbbEUSuhT4ZGDt"}' \
  > ${MINA_CONFIG_DIR}/wallets/store/${PK} \
  && chmod go-rwx ${MINA_CONFIG_DIR}/wallets/store/${PK} \
  && cp ${MINA_CONFIG_DIR}/wallets/store/${PK} /root/keys/demo-block-producer \
  && cp ${MINA_CONFIG_DIR}/wallets/store/${PK}.pub /root/keys/demo-block-producer.pub \
  && echo '{"ledger":{"accounts":[{"pk":"'${PK}'","balance":"66000","sk":null,"delegate":null}]}}' > /config.json \
  && coda-create-genesis --genesis-dir /var/lib/coda --config-file /config.json

ENTRYPOINT ["/usr/bin/dumb-init", "/run-demo.sh"]
