# This dockerfile is part of a temporary hack for integration tests. Do not use
# this dockerfile in a production environment. See `mina_daemon_puppeteer.py`
# for more details.

# This dockerfile needs to be run with `dockerfiles/puppeteer-context` as the
# build context.

ARG MINA_VERSION
FROM codaprotocol/mina-daemon:${MINA_VERSION}

RUN echo '#!/bin/bash\n\
pgrep -f --newest "python3 /root/mina_daemon_puppeteer.py"'\
> find_puppeteer.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR2 $(./find_puppeteer.sh)\n\
while [ ! -f daemon-active ]; do sleep 1; done'\
> start.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR1 $(./find_puppeteer.sh)\n\
while [ -f daemon-active ]; do sleep 1; done'\
> stop.sh

RUN chmod +x find_puppeteer.sh start.sh stop.sh

ADD mina_daemon_puppeteer.py .

ENTRYPOINT ["/usr/bin/dumb-init", "python3", "/root/mina_daemon_puppeteer.py"]
