#################################################################################################
# The "production" Stage
# - sets up the final container with built binaries and a running postgresql archive node setup
#################################################################################################
FROM debian:stretch-slim AS production

ENV DEBIAN_FRONTEND noninteractive

# Dependencies
RUN apt-get update --quiet --yes \
  && apt-get upgrade --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    dnsutils \
    dumb-init \
    libffi6 \
    libgmp10 \
    libgomp1 \
    libprocps6 \
    libjemalloc-dev \
    libssl1.1 \
    tzdata \
  && rm -rf /var/lib/apt/lists/*

# mina keypair package
RUN echo "deb [trusted=yes] http://packages.o1test.net stretch stable" > /etc/apt/sources.list.d/o1.list \
   && apt-get update --quiet --yes \
   && apt-get install --quiet --yes "mina-generate-keypair=1.2.1beta1-45440dc"

WORKDIR /

ENTRYPOINT [ "mina-generate-keypair" ]
