FROM debian:stretch

# Dependencies
RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    strace \
    dumb-init \
    libssl1.1 \
    libprocps6 \
    libgmp10 \
    libgomp1 \
    libffi6 \
    apt-transport-https \
    ca-certificates && \
  rm -rf /var/lib/apt/lists/*

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net unstable main" > /etc/apt/sources.list.d/coda.list \
  && apt-get update \
  && apt-get install --force-yes -t unstable coda-testnet-postake-medium-curves=0.0.1-release-beta-43cb0790 -y

ENTRYPOINT ["/usr/bin/dumb-init", "coda" ]
