FROM ubuntu:18.04
# Run with `docker build --build-arg coda_deb_version=<version>`
ARG coda_deb_version
ARG deb_repo=stable

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $coda_deb_version"

COPY scripts/healthcheck-utilities.sh /healthcheck/utilities.sh

# Dependencies
RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    curl \
    jq \
    strace \
    dumb-init \
    libssl1.1 \
    libprocps6 \
    libgmp10 \
    libgomp1 \
    libffi6 \
    apt-transport-https \
    ca-certificates \
    dnsutils \
    gnupg2 \
    tzdata && \
  rm -rf /var/lib/apt/lists/*

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

RUN apt-get update && apt-get install -y google-cloud-sdk kubectl

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_repo main" > /etc/apt/sources.list.d/o1.list \
  && apt-get update \
  && apt-get install -y --allow-downgrades "mina-dev-noprovingkeys=$coda_deb_version" "mina-dev=$coda_deb_version"

WORKDIR /root

RUN echo '#!/bin/bash -x\n\
mkdir -p .mina-config\n\
touch .mina-config/mina-prover.log\n\
touch .mina-config/mina-verifier.log\n\
touch .mina-config/mina-best-tip.log\n\
while true; do\n\
  rm -f /root/.mina-config/.mina-lock\n\
  mina "$@" 2>&1 >mina.log &\n\
  coda_pid=$!\n\
  tail -q -f mina.log -f .mina-config/mina-prover.log -f .mina-config/mina-verifier.log -f .mina-config/mina-best-tip.log &\n\
  tail_pid=$!\n\
  wait "$coda_pid"\n\
  echo "Mina process exited with status code $?"\n\
  sleep 10\n\
  kill "$tail_pid"\n\
  if [ ! -f stay_alive ]; then\n\
    exit 0\n\
  fi\n\
done'\
> init_mina.sh

RUN chmod +x init_mina.sh

ENV CODA_TIME_OFFSET 0

ENTRYPOINT ["/usr/bin/dumb-init", "/root/init_mina.sh"]
