FROM gcr.io/o1labs-192920/ocaml-base:f487b0862b3d0201a6e46d933afc441e01cf60a3

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd src/app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

