ARG image=debian:bullseye
FROM ${image}

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

COPY scripts/archive-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Dependencies
RUN apt-get update --quiet --yes \
    && apt-get upgrade --quiet --yes \
    && apt-get install --quiet --yes --no-install-recommends \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        libgomp1 \
        libpq-dev \
        apt-transport-https \
        ca-certificates \
        dnsutils \
        tzdata \
        postgresql \
        postgresql-contrib \
        apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

# archive-node package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --quiet --yes "mina-receipt-chain-hash-fix=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

ENV RECEIPT_CHAIN_HASH_TO_B58_APP /usr/local/bin/mina-receipt-chain-hash-to-b58
ENV LAST_VRF_OUTPUT_TO_B64_APP /usr/local/bin/mina-last-vrf-output-to-b64
ENTRYPOINT ["/etc/mina/receipt-chain-hash-fix-script/migrate-itn-data.sh"]