ARG image=debian:bullseye-slim
FROM ${image}

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG deb_profile

ENV MINA_DEB=mina-create-genesis

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

# Dependencies
RUN apt-get update --quiet --yes \
    && apt-get upgrade --quiet --yes \
    && apt-get install --quiet --yes --no-install-recommends \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        libgomp1 \
        libpq-dev \
        gnupg2 \
        apt-transport-https \
        ca-certificates \
        dnsutils \
        tzdata \
        apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

# archive-node package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --quiet --yes "${MINA_DEB}=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["mina-create-genesis"]
