# This will start a build inside a container
FROM codaprotocol/coda:toolchain-7882157f7c6c7bd5def2b0b5a18541bc1b5e0f4f

WORKDIR /app
ADD ./ /app
RUN sudo chown -R opam /app

RUN cd src/app/kademlia-haskell && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build release2.nix

RUN eval `opam config env` && dune build

