FROM nixos/nix:latest

# Simple toolchain & build container that compiles and patches a libp2p_helper binary for coda use

# Add OS tools
RUN apk add patchelf dpkg tar

# Update nixkgs
RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update && \
    nix-env -iA cachix -f https://cachix.org/api/v1/install

# Source tree nix-built haskell kademlia
ADD /src/app/libp2p_helper /src/libp2p

# Generate a unique signature for the source tree path
RUN cd /src ; find . -type f -print0  | xargs -0 sha1sum | sort | sha1sum | cut -f 1 -d ' ' > /tmp/sha1sig ; cat /tmp/sha1sig

# Build
RUN cachix use codaprotocol \
    && cd /src/libp2p ; nix-build default.nix \
    && ls -l /src/libp2p/result/bin

# Adjust elf headers (de-nix)
RUN patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 /src/libp2p/result/bin/libp2p_helper

# Deb staging
RUN mkdir -p /src/build/DEBIAN
# bkase had a hard time finding the DEBIAN/control file, and believes it makes
# sense for that information to live here along with the other logic for
# populating the deb build. And so we can created it via echos
RUN echo "Package: coda-discovery" > /src/build/DEBIAN/control && \
  echo "Version: 0.1.$(date +%Y-%m-%d)-$(cat /tmp/sha1sig)" >> /src/build/DEBIAN/control && \
  echo "Section: base" >> /src/build/DEBIAN/control && \
  echo "Priority: optional" >> /src/build/DEBIAN/control && \
  echo "Architecture: amd64" >> /src/build/DEBIAN/control && \
  echo "License: Apache-2.0" >> /src/build/DEBIAN/control && \
  echo "Homepage: https://codaprotocol.com/" >> /src/build/DEBIAN/control && \
  echo "Maintainer: o\(1\)Labs <build@o1labs.org>" >> /src/build/DEBIAN/control && \
  echo "Description: Coda Protocol Discovery Tools" >> /src/build/DEBIAN/control && \
  echo " Coda Protocol libp2p helper" >> /src/build/DEBIAN/control
RUN mkdir -p /src/build/usr/local/bin
RUN cp /src/libp2p/result/bin/libp2p_helper /src/build//usr/local/bin/coda-libp2p_helper

# Build and copy deb
RUN cd /src ; dpkg-deb --build /src/build ; cp /src/build.deb /src/coda-discovery.deb
