#build with: 
# docker build --build-arg deb_version=<version> 

#or directly run with:
# docker run -v <local keypath>:/keys --entrypoint ./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe txn_burst_util --num-txn-per-acct 10 --origin-sender-sk-path "/keys/<origin key path>" --origin-sender-sk-pw "some password" --returner-sk-path "/keys/<origin key path>" --returner-sk-pw "some password"

ARG image=debian:bullseye-slim
FROM ${image}

ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG network=mainnet

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

# Dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        apt-transport-https \
        ca-certificates \
        dnsutils \
	apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

#install mina and txn burst tool
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" | tee /etc/apt/sources.list.d/mina.list \
  && apt-get update\
  && apt-get install --quiet --yes --allow-downgrades "mina-$network=$deb_version" \
  && apt-get install --quiet --yes --allow-downgrades "mina-batch-txn=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

USER root
# prepare the key directories
RUN mkdir /keys && chmod 700 /keys
ENV MINA_PRIVKEY_PASS ""

ENTRYPOINT ["sleep", "infinity"]

CMD ["./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe"]
