# This dockerfile is part of a temporary hack for integration tests. Do not use
# this dockerfile in a production environment. See `coda_daemon_puppeteer.py`
# for more details.

ARG CODA_VERSION
ARG CODA_BRANCH
FROM codaprotocol/coda-daemon:${CODA_VERSION}

RUN echo '#!/bin/bash\n\
pgrep -f --newest "python3 /root/coda_daemon_puppeteer.py"'\
> find_puppeteer.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR2 $(./find_puppeteer.sh)'\
> start.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR1 $(./find_puppeteer.sh)'\
> stop.sh

RUN chmod +x find_puppeteer.sh start.sh stop.sh

RUN curl -sL "https://raw.githubusercontent.com/CodaProtocol/coda/${CODA_BRANCH}/dockerfiles/coda_daemon_puppeteer.py" \
  /root/coda_daemon_puppeteer.py

ENTRYPOINT ["/usr/bin/dumb-init", "python3", "/root/coda_daemon_puppeteer.py"]
