ARG deb_codename=stretch
FROM debian:${deb_codename}-slim

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=stretch
ARG deb_release=alpha
ARG network=mainnet

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_version"

COPY scripts/archive-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# archive container is not being run under puppeteer atm for the integration tests, so these aren't needed
# COPY --chown=${UID} puppeteer-context/* /
# RUN chmod +x /mina_daemon_puppeteer.py /find_puppeteer.sh /start.sh /stop.sh

# Workaround terrible postgresql package requirements with man
RUN mkdir /usr/share/man/man7 /usr/share/man/man1

#these are necessary to install BEFORE attempting to install psql-11
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
      wget \
      lsb-release \
      gnupg

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && RELEASE=$(lsb_release -cs) \
  && echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | tee /etc/apt/sources.list.d/pgdg.list

# Dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        libgomp1 \
        libjemalloc1 \
        libpq-dev \
        apt-transport-https \
        ca-certificates \
        dnsutils \
        tzdata \
        postgresql-11 \
        postgresql-contrib \
        apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /healthcheck && curl https://raw.githubusercontent.com/MinaProtocol/mina/develop/dockerfiles/scripts/healthcheck-utilities.sh -o /healthcheck/utilities.sh

# archive-node package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get -y update \
  && apt-get install -y "mina-archive-$network=$deb_version"

ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint.sh"]
