FROM debian:9-slim

# Networking and package management tools
RUN apt-get update && apt-get install --yes \
    bzip2 \
    curl \
    jq \
    wget \
    apt-transport-https \
    ca-certificates

# Install dhall tools to local bin PATH
RUN wget https://github.com/dhall-lang/dhall-haskell/releases/download/1.35.0/dhall-json-1.7.2-x86_64-linux.tar.bz2 \
        && tar --extract --bzip2 --file dhall-json-1.7.2-x86_64-linux.tar.bz2
RUN cp ./bin/dhall-to-* /usr/local/bin
