FROM ocaml/opam2:debian-9-ocaml-4.07

# OS package dependancies
RUN sudo apt-get update && sudo apt-get install --yes \
    cmake \
    jq \
    libboost-dev \
    libboost-program-options-dev \
    libffi-dev \
    libgmp-dev \
    libgmp3-dev \
    libprocps-dev \
    librocksdb-dev \
    librocksdb4.5 \
    libsodium-dev \
    libssl-dev \
    lsb \
    m4 \
    pandoc \
    patchelf \
    python \
    perl \
    pkg-config \
    python-jinja2 \
    rubygems \
    zlib1g-dev

RUN sudo gem install deb-s3

# Google Cloud tools
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
    sudo apt-get update -y && sudo apt-get install google-cloud-sdk -y

# Opam dependencies
# Pull freshest repository
RUN git -C /home/opam/opam-repository pull
RUN opam update -y && opam upgrade -y

# Source copy of dune (modified to link rocksdb for test runners)
ADD /src/external/ocaml-dune /ocaml-dune
RUN cd /ocaml-dune && yes | opam pin add .

# Install other OPAM packages
ADD /src/opam.export .
RUN opam switch import opam.export ; rm opam.export

# Source copy of ocaml-sodium (modified for static linking)
ADD /src/external/ocaml-sodium /ocaml-sodium
RUN cd /ocaml-sodium && yes | opam pin add .

# Source copy of ocaml-rocksdb (exposes opaque types)
ADD /src/external/ocaml-rocksdb /ocaml-rocksdb
RUN cd /ocaml-rocksdb && yes | opam pin add .

# Get coda-kademlia from packages repo
RUN sudo apt-get install --yes apt-transport-https ca-certificates && \
      echo "deb [trusted=yes] https://packages.o1test.net unstable main" | sudo tee -a /etc/apt/sources.list.d/coda.list && \
      sudo apt-get update && \
      sudo apt-get install --yes coda-kademlia
