ARG image=debian:bullseye-slim
FROM ${image}

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG deb_profile

# if --build-arg deb_profile is defined, add hypen at beginning.
ENV SUFFIX=${deb_profile:+-${deb_profile}}
# construct mina debian package name based on network and suffix.
# possible values:
# - mina-archive
# - mina-archive-lightnet etc.
ENV MINA_DEB=mina-archive${SUFFIX}

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

COPY scripts/archive-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Dependencies
RUN apt-get update --quiet --yes \
    && apt-get upgrade --quiet --yes \
    && apt-get install --quiet --yes --no-install-recommends \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        libgomp1 \
        libpq-dev \
        apt-transport-https \
        ca-certificates \
        dnsutils \
        tzdata \
        postgresql \
        postgresql-contrib \
        apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /healthcheck && curl https://raw.githubusercontent.com/MinaProtocol/mina/develop/dockerfiles/scripts/healthcheck-utilities.sh -o /healthcheck/utilities.sh

# archive-node package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --quiet --yes "${MINA_DEB}=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint.sh"]
