ARG image=debian:bullseye
FROM ${image} AS production

ARG TARGETARCH

ARG deb_codename=bullseye
ARG deb_version
ARG deb_release=unstable
ARG deb_repo="http://packages.o1test.net"
ARG network=mainnet

ARG psql_version=13

ARG GCLOUD_VERSION=476.0.0
ARG apt_cache_url=""

ENV DEBIAN_FRONTEND noninteractive

# We do not install the below platform-specific dependencies,
# and instead assume that apt will install the proper deps based on the package definition.
# The packages are noted here just for clarity/documentation.
# Bullseye/Focal-only Deps:
#    libffi7
#    libprocps8
#    libjemalloc2

# Optional: configure APT caching proxy (bypass proxy for deb_repo)
RUN if [ -n "$apt_cache_url" ]; then \
  echo "Acquire::http::Proxy \"${apt_cache_url}\";" > /etc/apt/apt.conf.d/01proxy; \
  DEB_REPO_HOST=${deb_repo#*://}; DEB_REPO_HOST=${DEB_REPO_HOST%%[:/]*}; \
  echo "Acquire::http::Proxy::${DEB_REPO_HOST} \"DIRECT\";" >> /etc/apt/apt.conf.d/01proxy; \
fi

# Install ca-certificates using HTTP
RUN apt-get update --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Switch to HTTPS
RUN if [ -f /etc/apt/sources.list ]; then \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list; \
else \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list.d/debian.sources; \
fi

# --- Dependencies across many platforms
RUN apt-get update --quiet --yes \
  && apt-get upgrade --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends \
    apt-utils \
    apt-transport-https \
    curl \
    build-essential \
    dnsutils \
    dumb-init \
    gettext \
    gnupg2 \
    libgmp10 \
    libgomp1 \
    libssl1.1 \
    tzdata \
    jq \
    procps \
    sudo \
    wget \
  && rm -rf /var/lib/apt/lists/*

# Install google-cloud-sdk for GCLOUD_UPLOAD feature
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN case "${TARGETARCH}" in \
        "amd64") GCLOUD_ARCH="x86_64" ;; \
        "arm64") GCLOUD_ARCH="arm" ;; \
        *) echo "Unsupported arch: ${TARGETARCH}"; exit 1 ;; \
    esac; \
    curl -sSfL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${GCLOUD_VERSION}-linux-${GCLOUD_ARCH}.tar.gz" | \
    tar -xz -C /opt/ && \
    /opt/google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin kubectl --quiet

ENV PATH="/opt/google-cloud-sdk/bin:${PATH}"

ENV USE_GKE_GCLOUD_AUTH_PLUGIN=True


# --- Install Postgresql
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && echo deb https://apt-archive.postgresql.org/pub/repos/apt/ "$deb_codename"-pgdg-archive main | tee /etc/apt/sources.list.d/pgdg.list \
    && apt-get update -y \
    && apt-get install --no-install-recommends -y \
       postgresql-"$psql_version" \
       postgresql-client-"$psql_version" \
    && rm -rf /var/lib/apt/lists/*

# --- Generate en_US.UTF-8 locale to allow use of O(1) Labs DB dumps
RUN locale-gen en_US.UTF-8

# jemalloc is also installed automatically here to match the package dependencies for this $deb_codename
RUN echo "Building image with version $deb_version from repo $deb_release $deb_codename " \
  && echo "deb [trusted=yes] ${deb_repo} $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --no-install-recommends --quiet --yes --allow-downgrades -o Dpkg::Options::="--force-overwrite" "mina-test-suite=$deb_version" "mina-$network-instrumented=$deb_version" "mina-archive-$network-instrumented=$deb_version" "mina-rosetta-$network=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["sleep","infinity"]
