#build with: 
# docker build --build-arg deb_version=<version> 

#or directly run with:
# docker run -v <local keypath>:/keys --entrypoint ./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe txn_burst_util --num-txn-per-acct 10 --origin-sender-sk-path "/keys/<origin key path>" --origin-sender-sk-pw "some password" --returner-sk-path "/keys/<origin key path>" --returner-sk-pw "some password"

ARG image=europe-west3-docker.pkg.dev/o1labs-192920/euro-docker-repo/debian:bullseye-slim
FROM ${image}

ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG network=mainnet
ARG deb_repo="http://packages.o1test.net"
ARG apt_cache_url=""

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

# Optional: configure APT caching proxy (bypass proxy for deb_repo); install ca-certificates
RUN if [ -n "$apt_cache_url" ]; then \
  echo "Acquire::http::Proxy \"${apt_cache_url}\";" > /etc/apt/apt.conf.d/01proxy; \
  DEB_REPO_HOST=$(echo "$deb_repo" | sed -E 's|https?://([^:/]+).*|\1|'); \
  echo "Acquire::http::Proxy::${DEB_REPO_HOST} \"DIRECT\";" >> /etc/apt/apt.conf.d/01proxy; \
fi \
  && apt-get update --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Switch to HTTPS
RUN if [ -f /etc/apt/sources.list ]; then \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list; \
else \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list.d/debian.sources; \
fi

# Dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        apt-transport-https \
        dnsutils \
	apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

#install mina and txn burst tool
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN echo "deb [trusted=yes] ${deb_repo} $deb_codename $deb_release" | tee /etc/apt/sources.list.d/mina.list \
  && apt-get update\
  && apt-get install --quiet --yes --no-install-recommends --allow-downgrades "mina-$network=$deb_version" \
  && apt-get install --quiet --yes --no-install-recommends --allow-downgrades "mina-batch-txn=$deb_version" \
  && rm -rf /var/lib/apt/lists/*

USER root
# prepare the key directories
RUN mkdir /keys && chmod 700 /keys
ENV MINA_PRIVKEY_PASS ""

ENTRYPOINT ["sleep", "infinity"]

CMD ["./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe"]
