ARG image=debian:bullseye-slim
FROM ${image}

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG deb_repo="http://packages.o1test.net"

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

# Dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        apt-transport-https \
        ca-certificates \
        dnsutils \
	apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

ADD "mina-zkapp-test-transaction_$deb_version.deb" mina-zkapp-test-transaction.deb

RUN apt-get install --allow-downgrades -y -f "./mina-zkapp-test-transaction.deb"

# Clean up
RUN rm -f mina-zkapp-test-transaction.deb