#################################################################################################
# The "production" Stage
# - sets up the final container with built binaries and a running postgresql archive node setup
#################################################################################################
FROM debian:stretch-slim AS production

ENV DEBIAN_FRONTEND noninteractive

# Dependencies
# stretch-slim configures apt to not store any cache, so no need to rm it
# TODO: make sure this is the minimum runtime deps
RUN apt-get -y update \
  && apt -y install \
    apt-transport-https \
    ca-certificates \
    dnsutils \
    dumb-init \
    libffi6 \
    libgmp10 \
    libgomp1 \
    libprocps6 \
    libjemalloc-dev \
    libssl1.1 \
    tzdata

# mina keypair package
RUN echo "deb [trusted=yes] http://packages.o1test.net stretch stable" > /etc/apt/sources.list.d/o1.list \
   && apt-get update \
   || sleep 10s && apt-get update \
   || sleep 10s && apt-get update \
   || sleep 10s && apt-get update \
   && apt-get install -y "mina-generate-keypair=1.3.1.2-25388a0"

WORKDIR /

ENTRYPOINT [ "mina-generate-keypair" ]
