FROM rust:latest

ADD /src/app/trace-tool /src

# Fetches + caches the cargo registry and our dependencies, as well as building
# them so later builds are substantially faster.

RUN cd /src ; cargo build

# Install nightly toolchain for Wasm build

RUN rustup toolchain install nightly-2021-11-16
RUN rustup component add rust-src --toolchain nightly-2021-11-16
