# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_release=unstable
ARG deb_codename=bullseye
ARG network=mainnet
ARG signature_kind=mainnet
ARG deb_repo="http://packages.o1test.net"
ARG deb_profile
ARG deb_suffix
ARG docker_repo="gcr.io/o1labs-192920"
ARG deb_artifact=mina-daemon

FROM ${docker_repo}/${deb_artifact}:${deb_version}-${deb_codename}-base

# if --build-arg deb_suffix is defined, add hypen at beginning.
ENV SUFFIX=${deb_suffix:+-${deb_suffix}}
# construct mina debian package name based on network and suffix.
# possible values:
# - mina-devnet
# - mina-devnet-lightnet etc.
ENV MINA_DEB=mina-${network}${SUFFIX}
ENV MINA_SIGNATURE_KIND=${signature_kind}

ENV DEBIAN_FRONTEND noninteractive

# Mina daemon package
# jemalloc is also installed automatically here to match the package dependencies for this $deb_codename
RUN echo "Building image with version $deb_version from repo $deb_release $deb_codename for network $network" \
  && echo "deb [trusted=yes] ${deb_repo} $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --no-install-recommends --quiet --yes --allow-downgrades "${MINA_DEB}=$deb_version" \
  && rm -rf /var/lib/apt/lists/*