FROM ocaml/opam2:debian-9-ocaml-4.07

# OS package dependancies
RUN sudo apt-get install --yes \
    cmake \
    libboost-dev \
    libboost-program-options-dev \
    libffi-dev \
    libgmp-dev \
    libgmp3-dev \
    libprocps-dev \
    librocksdb-dev \
    librocksdb4.5 \
    libsodium-dev \
    libssl-dev \
    m4 \
    pandoc \
    python \
    perl \
    pkg-config \
    python-jinja2 \
    zlib1g-dev

# Opam dependancies
RUN opam update -y && opam upgrade -y
RUN opam depext -i dune
RUN opam install \
    async \
    async_ssl \
    bignum \
    bitstring \
    camlp4 \
    cohttp \
    cohttp-async \
    core \
    ctypes \
    ctypes-foreign \
    extlib \
    js_of_ocaml \
    js_of_ocaml-ppx \
    menhir \
    merlin \
    num \
    ocamlformat \
    ocp-indent \
    orocksdb \
    ppx_deriving \
    ppx_deriving_yojson \
    rpc_parallel \
    utop \
    virtual_dom \
    yojson

# Source copy of ocaml-sodium (modified for static linking)
ADD ./src/external/ocaml-sodium /ocaml-sodium
RUN cd /ocaml-sodium && yes | opam pin add .


# nix for haskell for kademlia
# fixme: break in to it's own container
RUN sudo mkdir -p /nix
RUN sudo chown opam /nix
RUN sudo mkdir -p /etc/nix
RUN sudo bash  -c 'echo "build-users-group =" > /etc/nix/nix.conf'
ENV USER opam
RUN cd /home/opam && curl https://nixos.org/nix/install | sh

ADD ./src/app/kademlia-haskell/prefetch /prefetch
RUN sudo chown -R opam /prefetch
RUN cd /prefetch && . /home/opam/.nix-profile/etc/profile.d/nix.sh && nix-build prefetch.nix
