ARG image=europe-west3-docker.pkg.dev/o1labs-192920/euro-docker-repo/debian:bullseye-slim
FROM ${image}

ARG TARGETARCH

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_release=unstable
ARG deb_codename=bullseye
ARG network=mainnet
ARG deb_repo="http://packages.o1test.net"
ARG deb_profile
ARG deb_suffix
ARG apt_cache_url=""

ARG GCLOUD_VERSION=476.0.0

# if --build-arg deb_suffix is defined, add hypen at beginning.
ENV SUFFIX=${deb_suffix:+-${deb_suffix}}
# construct mina debian package name based on network and suffix.
# possible values:
# - mina-devnet
# - mina-devnet-lightnet etc.
ENV MINA_DEB=mina-${network}${SUFFIX}

ENV DEBIAN_FRONTEND noninteractive

# We do not install the below platform-specific dependencies,
# and instead assume that apt will install the proper deps based on the package definition.
# The packages are noted here just for clarity/documentation.
# Bullseye/Focal-only Deps:
#    libffi7
#    libprocps8
#    libjemalloc2
#    libssl

# Optional: configure APT caching proxy (bypass proxy for deb_repo)
RUN if [ -n "$apt_cache_url" ]; then \
  echo "Acquire::http::Proxy \"${apt_cache_url}\";" > /etc/apt/apt.conf.d/01proxy; \
  DEB_REPO_HOST=$(echo "$deb_repo" | sed -E 's|https?://([^:/]+).*|\1|'); \
  echo "Acquire::http::Proxy::${DEB_REPO_HOST} \"DIRECT\";" >> /etc/apt/apt.conf.d/01proxy; \
fi

# Install ca-certificates using HTTP
RUN apt-get update --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Switch to HTTPS
RUN if [ -f /etc/apt/sources.list ]; then \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list; \
else \
  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list.d/debian.sources; \
fi

# Dependencies
RUN apt-get update --quiet --yes \
  && apt-get upgrade --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends \
    apt-transport-https \
    curl \
    dnsutils \
    dumb-init \
    gettext \
    gnupg2 \
    jq \
    libgmp10 \
    libgomp1 \
    libpq-dev \
    procps \
    python3 \
    tzdata \
  && rm -rf /var/lib/apt/lists/*

# Install google-cloud-sdk for GCLOUD_UPLOAD feature
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN case "${TARGETARCH}" in \
        "amd64") GCLOUD_ARCH="x86_64" ;; \
        "arm64") GCLOUD_ARCH="arm" ;; \
        *) echo "Unsupported arch: ${TARGETARCH}"; exit 1 ;; \
    esac; \
    curl -sSfL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${GCLOUD_VERSION}-linux-${GCLOUD_ARCH}.tar.gz" | \
    tar -xz -C /opt/ && \
    /opt/google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin kubectl --quiet

ENV PATH="/opt/google-cloud-sdk/bin:${PATH}"

ENV USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Mina daemon package
# jemalloc is also installed automatically here to match the package dependencies for this $deb_codename
RUN echo "Building image with version $deb_version from repo $deb_release $deb_codename for network $network" \
  && echo "deb [trusted=yes] ${deb_repo} $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update --quiet --yes \
  && apt-get install --no-install-recommends --quiet --yes --allow-downgrades "${MINA_DEB}=$deb_version" \
  && apt-get install --no-install-recommends --quiet --yes --allow-downgrades "mina-create-legacy-genesis=3.2.0-f77c8c9" \
  && rm -rf /var/lib/apt/lists/*


# Move to a non-root UID in the future (specifically 50000, as it is memorable and safely within the bounds of most systems)
# for now stick to root for compatibility
ARG UID=0

# TODO: flesh out this feature + test
# Create a mina user to execute the daemon with
RUN mkdir /home/mina \
  && adduser --uid 50000 --disabled-password --gecos '' mina \
  && passwd -l mina \
  && chown -R mina:mina /home/mina

WORKDIR /home/mina
USER mina

## Reset workdir, USER, and ${UID} for root-owned version
WORKDIR /root/
USER 0

COPY --chown=${UID} scripts/healthcheck-utilities.sh /healthcheck/utilities.sh
COPY --chown=${UID} scripts/cron_job_dump_ledger.sh /cron_job_dump_ledger.sh
COPY --chown=${UID} scripts/daemon-entrypoint.sh /entrypoint.sh
# Solve this by marking scripts executable in git
COPY --chown=${UID} ./auxiliary_entrypoints /entrypoint.d

COPY --chown=${UID} puppeteer-context/* /
RUN chmod +x /mina_daemon_puppeteer.py /find_puppeteer.sh /start.sh /stop.sh

ENV MINA_TIME_OFFSET 0

ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint.sh"]
