FROM nixos/nix:latest

# Simple toolchain & build container that compiles and patches a kademlia binary for coda use

ARG PKGNAME=libp2p_helper

# Add OS tools
RUN apk add patchelf dpkg tar

# Update nixkgs
RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs \
    && nix-channel --update \
    && nix-env -iA cachix -f https://cachix.org/api/v1/install

# Copy source tree
ADD /src/app/libp2p_helper /src
WORKDIR /src

# Generate a unique signature for the source tree path
RUN find . -type f -print0  | xargs -0 sha1sum | sort | sha1sum | cut -f 1 -d ' ' > /tmp/sha1sig \
    && cat /tmp/sha1sig

# Build
RUN cachix use codaprotocol \
    && nix-build default.nix \
    && ls -l /src/result/bin

# Adjust elf headers (de-nix)
RUN patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 /src/result/bin/${PKGNAME}

# Deb staging
RUN mkdir -p /src/build/usr/local/bin \
    && cp /src/result/bin/${PKGNAME} /src/build//usr/local/bin/coda-${PKGNAME} \
    && DATE=$(date +%Y-%m-%d) \
    && sed -i "s/DATE/${DATE}/" /src/build/DEBIAN/control \
    && HASH=$(cat /tmp/sha1sig)\
    && sed -i "s/HASH/${HASH}/" /src/build/DEBIAN/control \
    && cat /src/build/DEBIAN/control

# Build and copy deb
RUN dpkg-deb --build /src/build \
    && cp /src/build.deb /src/coda-${PKGNAME}.deb \
    && ls -l /src/*.deb
