# Lifted directly from https://hub.docker.com/r/ocaml/opam2/
# https://github.com/ocaml/infrastructure/wiki/Containers
# Is doing some magic to bypass the bubblewrap init sandboxing

FROM ocaml/opam2:debian-9-ocaml-4.07
