# This dockerfile is part of a temporary hack for integration tests. Do not use
# this dockerfile in a production environment. See `coda_daemon_puppeteer.py`
# for more details.

ARG CODA_VERSION
FROM codaprotocol/coda-daemon:${CODA_VERSION}

ARG CODA_BRANCH

RUN echo '#!/bin/bash\n\
pgrep -f --newest "python3 /root/coda_daemon_puppeteer.py"'\
> find_puppeteer.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR2 $(./find_puppeteer.sh)\n\
while [ ! -f daemon-active ]; do sleep 1; done'\
> start.sh

RUN echo '#!/bin/bash\n\
kill -s SIGUSR1 $(./find_puppeteer.sh)\n\
while [ -f daemon-active ]; do sleep 1; done'\
> stop.sh

RUN chmod +x find_puppeteer.sh start.sh stop.sh

RUN curl -sL "https://raw.githubusercontent.com/MinaProtocol/mina/${CODA_BRANCH}/dockerfiles/coda_daemon_puppeteer.py" \
  -o /root/coda_daemon_puppeteer.py

ENTRYPOINT ["/usr/bin/dumb-init", "python3", "/root/coda_daemon_puppeteer.py"]
