ARG image=debian:bullseye-slim
FROM ${image}

# Run with `docker build --build-arg deb_version=<version>`
ARG deb_version
ARG deb_codename=bullseye
ARG deb_release=unstable
ARG deb_repo="http://packages.o1test.net"

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $deb_codename $deb_release $deb_version"

# Install ca-certificates using HTTP
RUN apt-get update --quiet --yes \
  && apt-get install --quiet --yes --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Switch to HTTPS
RUN sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list

# Dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install \
        procps \
        curl \
        jq \
        dumb-init \
        libssl1.1 \
        apt-transport-https \
        dnsutils \
	    apt-utils \
        man \
    && rm -rf /var/lib/apt/lists/*

# Snapp test transaction package
RUN echo "deb [trusted=yes] ${deb_repo} $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get -y update \
  || sleep 10s && apt-get -y update \
  || sleep 10s && apt-get -y update \
  || sleep 10s && apt-get -y update \
  && apt-get install -y "mina-zkapp-test-transaction=$deb_version"
