#build with: 
# docker build -t txn_burst_util -f Dockerfile_txn_burst .

#or directly run with:
# docker run -v <local keypath>:/keys --entrypoint ./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe txn_burst_util --num-txn-per-acct 10 --origin-sender-sk-path "/keys/<origin key path>" --origin-sender-sk-pw "some password" --returner-sk-path "/keys/<origin key path>" --returner-sk-pw "some password"

FROM gcr.io/o1labs-192920/mina-toolchain@sha256:77444cd510dc40efd8c62e5c1a53485a05f3e42d4f883d2cfe74158847763af2

USER opam

#install mina and the batch zkapp txn tool
RUN sudo apt-get -y update && sudo apt-get -y install man
RUN sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates
RUN sudo echo "deb [trusted=yes] http://packages.o1test.net $(lsb_release -cs) unstable" | sudo tee /etc/apt/sources.list.d/mina.list \
  && sudo apt-get update\
  && sudo apt-get install -y --allow-downgrades mina-berkeley=1.3.2beta2-fix-batch-zkapp-txn-ci-1d63942\
  && sudo apt-get install -y --allow-downgrades mina-batch-zkapp-test-txns=1.3.2beta2-fix-batch-zkapp-txn-ci-1d63942

USER root

ENTRYPOINT ["mina-batch-zkapp-test-txns"]
