(* Empty module.
   Linking against the library generated by this module overrides the default
   implementation, which links against the native rust bindings library.
   This is intended for use with JS code linked against the WASM bindings.
*)
