# General rustflags for all non-wasm32 targets
[target.'cfg(not(target_arch = "wasm32"))']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[profile.release.target.wasm32-unknown-unknown]
debug = true

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "src/lib/crypto/mina-rust-dependencies"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
#wasm-opt = ["-O4", "--detect-features", "--enable-mutable-globals" ]
#wasm-opt = ["-O4", "--enable-mutable-globals"]