#!/usr/bin/env bash

# NOTE: This script patches the genesis timestamp of a fork config so a new 
# network could be scheduled to genesis in some instant in the future.

set -eux -o pipefail

# ==================== Inputs to this script ====================
# The fork config we aim to patch on 
FORK_CONFIG_JSON=${FORK_CONFIG_JSON:=fork_config.json}
# The hashes file generated by runtime-genesis-ledger
LEDGER_HASHES_JSON=${LEDGER_HASHES_JSON:=ledger_hashes.json}
# The "base" config file, needed to know the genesis time of the prefork network
FORKING_FROM_CONFIG_JSON=${FORKING_FROM_CONFIG_JSON:=genesis_ledgers/mainnet.json}
# Genesis timestamp of the postfork network, defaults to 10mins in the future
GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP:=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "10 mins")}
# ===============================================================

# Pull the original genesis timestamp from the pre-fork config file
ORIGINAL_GENESIS_TIMESTAMP=$(jq -r '.genesis.genesis_state_timestamp' "$FORKING_FROM_CONFIG_JSON")
OFFSET=$(jq -r '.proof.fork.global_slot_since_genesis' "$FORKING_FROM_CONFIG_JSON")

if [[ "$OFFSET" == null ]]; then
  OFFSET=0
fi

DIFFERENCE_IN_SECONDS=$(($(date -d "$GENESIS_TIMESTAMP" "+%s") - $(date -d "$ORIGINAL_GENESIS_TIMESTAMP" "+%s")))
# Default: mainnet currently uses 180s per slot
SECONDS_PER_SLOT=${SECONDS_PER_SLOT:=180}
DIFFERENCE_IN_SLOTS=$(($DIFFERENCE_IN_SECONDS / $SECONDS_PER_SLOT))

# TODO modify, this won't work in a hardfork with Berkeley as basis
SLOT=$((DIFFERENCE_IN_SLOTS+OFFSET))

# jq expression below could be written with less code,
# but we aimed for maximum verbosity

jq -M \
  --arg genesis_timestamp "$GENESIS_TIMESTAMP" \
  --argjson slot "$SLOT" \
  --slurpfile hashes "$LEDGER_HASHES_JSON" \
  '
  {
    genesis: {
      genesis_state_timestamp: $genesis_timestamp
    },
    proof: {
      fork: {
        state_hash: .proof.fork.state_hash,
        blockchain_length: .proof.fork.blockchain_length,
        global_slot_since_genesis: $slot
      }
    },
    ledger: {
      add_genesis_winner: false,
      hash: $hashes[0].ledger.hash,
      s3_data_hash: $hashes[0].ledger.s3_data_hash
    },
    epoch_data: {
      staking: {
        seed: .epoch_data.staking.seed,
        hash: $hashes[0].epoch_data.staking.hash,
        s3_data_hash: $hashes[0].epoch_data.staking.s3_data_hash
      },
      next: {
        seed: .epoch_data.next.seed,
        hash: $hashes[0].epoch_data.next.hash,
        s3_data_hash: $hashes[0].epoch_data.next.s3_data_hash
      }
    }
  }
  ' "$FORK_CONFIG_JSON"
