#!/usr/bin/env bash

# NOTE: This script patches the genesis timestamp of a fork config so a new 
# network could be scheduled to genesis in some instant in the future.

set -eux -o pipefail

# ==================== Inputs to this script ====================
# The fork config we aim to patch on 
FORK_CONFIG_TO_PATCH=${FORK_CONFIG_JSON:=fork_config.json}
# The hashes file generated by runtime-genesis-ledger
POSTFORK_GENESIS_LEDGER_HASHES=${LEDGER_HASHES_JSON:=ledger_hashes.json}
# Genesis timestamp of the postfork network, defaults to 10mins in the future
POSTFORK_GENESIS_TIMESTAMP=${GENESIS_TIMESTAMP:=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "10 mins")}
# ===============================================================

# The fork slot is taken verbatim from the fork config's
# proof.fork.global_slot_since_genesis (the same authoritative source we already
# read state_hash and blockchain_length from). We deliberately do NOT recompute
# it from the wall-clock genesis window: that conversion needs a slot-time
# constant, and the legacy "180 s/slot" value is the Berkeley slot time -- Mesa
# runs at 90 s/slot, so a Mesa prefork came out off by 2x. See
# https://github.com/MinaProtocol/mina/issues/18980.

# jq expression below could be written with less code,
# but we aimed for maximum verbosity

jq -M \
  --arg genesis_timestamp "$POSTFORK_GENESIS_TIMESTAMP" \
  --slurpfile hashes "$POSTFORK_GENESIS_LEDGER_HASHES" \
  '
  {
    genesis: {
      genesis_state_timestamp: $genesis_timestamp
    },
    proof: {
      fork: {
        state_hash: .proof.fork.state_hash,
        blockchain_length: .proof.fork.blockchain_length,
        global_slot_since_genesis: .proof.fork.global_slot_since_genesis
      }
    },
    ledger: {
      add_genesis_winner: false,
      hash: $hashes[0].ledger.hash,
      s3_data_hash: $hashes[0].ledger.s3_data_hash
    },
    epoch_data: {
      staking: {
        seed: .epoch_data.staking.seed,
        hash: $hashes[0].epoch_data.staking.hash,
        s3_data_hash: $hashes[0].epoch_data.staking.s3_data_hash
      },
      next: {
        seed: .epoch_data.next.seed,
        hash: $hashes[0].epoch_data.next.hash,
        s3_data_hash: $hashes[0].epoch_data.next.s3_data_hash
      }
    }
  }
  ' "$FORK_CONFIG_TO_PATCH"
