#!/usr/bin/env bash

# NOTE: This script patches the genesis timestamp of a fork config so a new 
# network could be schedueld to genesis in some instant in the future.
# It differs from create_runtime_config.sh in that it's aimed at dealing with 
# output generated by `mina advanced generate-hard-fork-config`

set -eux -o pipefail

# ==================== Inputs to this script ====================
# The fork config we aim to patch on 
FORK_CONFIG_TO_PATCH=${FORK_CONFIG_TO_PATCH:?FORK_CONFIG_TO_PATCH is not provided}
# Prefork network slot time in seconds
PREFORK_SLOT_TIME_SEC=${PREFORK_SLOT_TIME_SEC:?PREFORK_SLOT_TIME_SEC is not provided}
# Delta in slots between the `slot_chain_end` of prefork network and 
# `global_slot_since_genesis` of postfork network
HARDFORK_GENESIS_SLOT_DELTA=${HARDFORK_GENESIS_SLOT_DELTA:?HARDFORK_GENESIS_SLOT_DELTA is not provided}
# ===============================================================

PREFORK_SLOT_CHAIN_END_TIMESTAMP=$(jq -r '.genesis.genesis_state_timestamp' "$FORK_CONFIG_TO_PATCH")
PREFORK_SLOT_CHAIN_END=$(jq -r '.proof.fork.global_slot_since_genesis' "$FORK_CONFIG_TO_PATCH")

HARDFORK_GENESIS_SEC_DELTA=$((PREFORK_SLOT_TIME_SEC * HARDFORK_GENESIS_SLOT_DELTA))
POSTFORK_GENESIS_TIMESTAMP=$(date -u -d "$PREFORK_SLOT_CHAIN_END_TIMESTAMP + $HARDFORK_GENESIS_SEC_DELTA seconds" +"%Y-%m-%dT%H:%M:%S.%6NZ")
POSTFORK_GENESIS_SLOT=$((PREFORK_SLOT_CHAIN_END + HARDFORK_GENESIS_SLOT_DELTA))

jq -M \
  --arg genesis_timestamp "$POSTFORK_GENESIS_TIMESTAMP" \
  --argjson slot "$POSTFORK_GENESIS_SLOT" \
  ' .genesis.genesis_state_timestamp = $genesis_timestamp
  | .proof.fork.global_slot_since_genesis = $slot
  ' \
  "$FORK_CONFIG_TO_PATCH"
