# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in citools.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "base64", "~> 0.3"

# Needed for RocksDB compatibility test
gem "rocksdb-ffi", "~> 0.2"

gem "rexml", "~> 3.4"
