{{- if .Values.mina.runtimeConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: plain-node-daemon-config
  labels:
    app: seed
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ .Values.mina.runtimeConfig | quote }}
{{- end }}
