(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Block_response.t : A BlockResponse includes a fully-populated block or a partially-populated block with a list of other transactions to fetch (other_transactions).
 *)

type t =
  { block: Block.t
  ; (* Some blockchains may require additional transactions to be fetched that weren't returned in the block response (ex: block only returns transaction hashes). For blockchains with a lot of transactions in each block, this can be very useful as consumers can concurrently fetch all transactions returned. *)
    other_transactions: Transaction_identifier.t list }
[@@deriving yojson {strict= false}, show]

(** A BlockResponse includes a fully-populated block or a partially-populated block with a list of other transactions to fetch (other_transactions). *)
let create (block : Block.t) : t = {block; other_transactions= []}
