(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Construction_parse_response.t : ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to `/construction/preprocess` and `/construction/payloads`.
 *)

type t =
  { operations: Operation.t list
  ; (* All signers of a particular transaction. If the transaction is unsigned, it should be empty. *)
    signers: string list
  ; metadata: Yojson.Safe.t option [@default None] }
[@@deriving yojson {strict= false}, show]

(** ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to `/construction/preprocess` and `/construction/payloads`. *)
let create (operations : Operation.t list) (signers : string list) : t =
  {operations; signers; metadata= None}
