(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Error.t : Instead of utilizing HTTP status codes to describe node errors (which often do not have a good analog), rich errors are returned using this object. Both the code and message fields can be individually used to correctly identify an error. Implementations MUST use unique values for both fields.
 *)

type t =
  { (* Code is a network-specific error code. If desired, this code can be equivalent to an HTTP status code. *)
    code: int32
  ; (* Message is a network-specific error message. The message MUST NOT change for a given code. In particular, this means that any contextual information should be included in the details field. *)
    message: string
  ; (* An error is retriable if the same request may succeed if submitted again. *)
    retriable: bool
  ; (* Often times it is useful to return context specific to the request that caused the error (i.e. a sample of the stack trace or impacted account) in addition to the standard error message. *)
    details: Yojson.Safe.t option [@default None] }
[@@deriving yojson {strict= false}, show]

(** Instead of utilizing HTTP status codes to describe node errors (which often do not have a good analog), rich errors are returned using this object. Both the code and message fields can be individually used to correctly identify an error. Implementations MUST use unique values for both fields. *)
let create (code : int32) (message : string) (retriable : bool) : t =
  {code; message; retriable; details= None}
