(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mempool_request.t : A MempoolRequest is utilized to retrieve all transaction identifiers in the mempool for a particular network_identifier.
 *)

type t = {network_identifier: Network_identifier.t}
[@@deriving yojson {strict= false}, show]

(** A MempoolRequest is utilized to retrieve all transaction identifiers in the mempool for a particular network_identifier. *)
let create (network_identifier : Network_identifier.t) : t =
  {network_identifier}
