(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Network_status_response.t : NetworkStatusResponse contains basic information about the node's view of a blockchain network. If a Rosetta implementation prunes historical state, it should populate the optional `oldest_block_identifier` field with the oldest block available to query. If this is not populated, it is assumed that the `genesis_block_identifier` is the oldest queryable block.
 *)

type t =
  { current_block_identifier: Block_identifier.t
  ; current_block_timestamp: Timestamp.t
  ; genesis_block_identifier: Block_identifier.t
  ; oldest_block_identifier: Block_identifier.t option [@default None]
  ; peers: Peer.t list }
[@@deriving yojson {strict= false}, show]

(** NetworkStatusResponse contains basic information about the node's view of a blockchain network. If a Rosetta implementation prunes historical state, it should populate the optional `oldest_block_identifier` field with the oldest block available to query. If this is not populated, it is assumed that the `genesis_block_identifier` is the oldest queryable block. *)
let create (current_block_identifier : Block_identifier.t)
    (current_block_timestamp : Timestamp.t)
    (genesis_block_identifier : Block_identifier.t) (peers : Peer.t list) : t =
  { current_block_identifier
  ; current_block_timestamp
  ; genesis_block_identifier
  ; oldest_block_identifier= None
  ; peers }
