(library
 (name runtime_config)
 (public_name mina_runtime_config)
 (libraries
  ;; opam libraries
  async
  async_kernel
  async_unix
  core_kernel
  bin_prot.shape
  base.caml
  base
  base64
  integers
  result
  sexplib0
  ;; local libraries
  currency
  mina_ledger
  mina_base
  mina_numbers
  snark_params
  pickles
  pickles_types
  with_hash
  signature_lib
  mina_compile_config)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_custom_printf
   ppx_sexp_conv
   ppx_let
   ppx_deriving_yojson
   ppx_fields_conv
   ppx_version
   ppx_compare
   ppx_here)))
