(library
 (name parallel_scan)
 (public_name parallel_scan)
 (inline_tests
  (flags -verbose -show-counts))
 (libraries
  ;; opam libraries
  core_kernel
  digestif
  ;; local libraries
  mina_stdlib
  ppx_version.runtime)
 (preprocess
  (pps ppx_jane ppx_version))
 (instrumentation
  (backend bisect_ppx))
 (synopsis "Parallel scan over an infinite stream (incremental map-reduce)"))
