from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Dict, List

from mln.errors import (
    ErrorCode,
    ManifestError,
    PlanError,
)
from mln.models import MaterializedManifest, ResolvedPlan


def derive_plan_root(raw_topology: dict, preset_name: str) -> str:
    """Derive the state root directory for plan persistence.

    If *state.root* is explicitly present in the raw topology, use it.
    Otherwise default to a repo-local ``.mina-local-network/<name>/`` directory.
    """
    state = raw_topology.get("state", {})
    if "root" in state:
        return os.path.expanduser(state["root"]).rstrip("/")

    # Default to repo-local directory keyed by topology name
    name = raw_topology.get("name", preset_name)
    return f".mina-local-network/{name}"


def plan_path(state_root: str) -> Path:
    """Return the canonical network-plan.json path under *state_root*."""
    return Path(state_root) / "network-plan.json"


def load_plan(path: Path) -> dict:
    """Load a persisted network-plan.json, failing clearly if absent."""
    if not path.exists():
        raise PlanError(
            ErrorCode.PLAN_NOT_FOUND,
            message=f"No network plan found at {path}\n"
            "Run 'plan topology <file-or-preset>' first to generate a plan.",
            path=str(path),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PlanError(
            ErrorCode.PLAN_PARSE_ERROR,
            message=f"Failed to parse network plan at {path}: {exc}",
            path=str(path),
        ) from exc


def resolve_plan_path(target: str) -> Path:
    """Resolve *target* to a ``network-plan.json`` path.

    * If *target* is a directory, look for ``<target>/network-plan.json``.
    * If *target* is an existing file (regardless of name), use it directly.
    * Otherwise assume *target* is a state-root directory name and look for
      ``<target>/network-plan.json`` (fail if missing).
    """
    p = Path(target)
    if p.is_dir():
        return plan_path(str(p))
    if p.is_file():
        return p
    # Interpret as a state-root directory name that doesn't exist yet
    return plan_path(str(p))


def plan_fingerprint(plan: ResolvedPlan) -> str:
    """Compute a SHA256 fingerprint of *plan* using canonical strict JSON.

    Uses ``sort_keys=True`` and minimal separators to avoid path/newline
    differences, producing a stable digest that matches the loaded plan
    regardless of how it was serialized to disk.
    """
    plan_dict = plan.model_dump(mode="json", exclude_none=True)
    canonical = json.dumps(plan_dict, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


FINGERPRINT_ALGORITHM = "sha256-canonical-json-v1"


def validate_manifest_matches_plan(
    plan: ResolvedPlan, manifest: MaterializedManifest
) -> None:
    """Validate that the manifest's plan fingerprint matches *plan*.

    Raises ``ManifestError`` if the fingerprint is missing or
    mismatched, with a clear instruction to re-materialize.
    """
    state_root = plan.state.root
    current_fp = plan_fingerprint(plan)
    stored_fp = manifest.plan_fingerprint
    stored_algo = manifest.plan_fingerprint_algorithm

    if stored_fp is None or stored_algo is None:
        raise ManifestError(
            ErrorCode.MANIFEST_MISMATCH,
            message="The materialized manifest does not contain a plan fingerprint.\n"
            "It may have been generated by an older version of the tool.\n\n"
            f"Run 'materialize {state_root} --force' to regenerate "
            "the manifest with a plan fingerprint.",
            path=state_root,
        )

    if stored_algo != FINGERPRINT_ALGORITHM:
        raise ManifestError(
            ErrorCode.MANIFEST_MISMATCH,
            message=f"Unexpected plan fingerprint algorithm: {stored_algo!r} "
            f"(expected {FINGERPRINT_ALGORITHM!r}).\n\n"
            f"Run 'materialize {state_root} --force' to regenerate "
            "the manifest with the current algorithm.",
            path=state_root,
        )

    if stored_fp != current_fp:
        raise ManifestError(
            ErrorCode.MANIFEST_MISMATCH,
            message="The materialized manifest was generated from a different plan "
            "than the current network-plan.json.\n"
            "This typically happens when:\n"
            "  - network-plan.json was changed after materialization\n"
            "  - 'spawn topology --overwrite' created a new plan but "
            "materialized-manifest.json is stale\n\n"
            f"Run 'materialize {state_root} --force' to re-materialize "
            "from the current plan, then spawn again.",
            path=state_root,
        )


def materialize_daemon_argv(
    argv: List[str], manifest: MaterializedManifest
) -> List[str]:
    """Replace unresolved pubkey tokens in argv with materialized key content.

    Currently supports:
    - ``<pubkey:snark_coordinator_account>`` → keys.snark_coordinator_account.pubkey_content

    Raises ManifestError if a token cannot be resolved or if any
    ``<pubkey:…>`` pattern remains after substitution.
    """
    keys = manifest.keys

    # --- resolve snark_coordinator_account pubkey ---
    sc = keys.get("snark_coordinator_account")
    if not sc:
        raise ManifestError(
            ErrorCode.KEY_MISSING,
            message="Missing keys.snark_coordinator_account in the materialized manifest.\n"
            "The topology requires a snark coordinator but no corresponding "
            "key was generated.  Re-run 'materialize' to regenerate keys.",
        )
    pubkey_content = sc.pubkey_content
    if not pubkey_content:
        raise ManifestError(
            ErrorCode.KEY_MISSING,
            message="keys.snark_coordinator_account.pubkey_content is empty in the "
            "materialized manifest.  The keypair may not have been generated "
            "correctly.  Re-run 'materialize --force' to regenerate keys.",
        )

    replacements: Dict[str, str] = {
        "<pubkey:snark_coordinator_account>": pubkey_content,
    }

    result: List[str] = []
    for arg in argv:
        result.append(replacements.get(arg, arg))

    # --- defensive: detect any residual unresolved tokens ---
    for arg in result:
        if arg.startswith("<pubkey:") and arg.endswith(">"):
            raise ManifestError(
                ErrorCode.KEY_MISSING,
                message=f"Unresolved token in daemon argv: {arg}\n"
                "The materialized manifest is missing key material for this token.\n"
                "Re-run 'materialize --force' to regenerate keys.",
            )

    return result
