from __future__ import annotations

import os
import re
from typing import Any, Dict, List, Optional, Tuple, Union

from mln.amounts import has_capability, parse_account_spec, parse_iso_duration
from mln.constants import (
    DEFAULT_CONSOLE_LOG_LEVELS,
    DEFAULT_FILE_LOG_LEVELS,
    DEFAULT_GENESIS_DELAY,
    DEFAULT_PROOF_LEVEL,
    DEFAULT_STATE_MODE,
    DEFAULT_STATE_ROOT,
    SEED_PEER_ID,
    SEED_PEER_KEY,
)
from mln.errors import (
    ErrorCode,
    TopologyError,
)
from mln.models import (
    BinariesConfig,
    DaemonRuntimeConfig,
    EchoWorkload,
    Endpoint,
    GenesisLedgerConfig,
    GenesisTimestamp,
    ItnMaxCostWorkload,
    LedgerConfig,
    LedgerPlan,
    LoggingConfig,
    NormalizedEchoWorkloadConfig,
    NormalizedItnMaxCostWorkloadConfig,
    NormalizedTopology,
    NormalizedValueTransferWorkloadConfig,
    NormalizedZkappWorkloadConfig,
    PlanState,
    ProofLedgerConfig,
    ResolvedNode,
    ResolvedPlan,
    ResolvedService,
    ResolvedWorker,
    ServiceKind,
    SnarkCoordinatorInfo,
    TierDefinition,
    ValueTransferWorkload,
    WorkloadConfig,
    WorkloadType,
    ZkappWorkload,
)
from mln.ports import PortAllocator
from mln.postgres import resolve_postgres_config


# ── normalize_topology helpers ─────────────────────────────────────────────


def _apply_logging_defaults(t: dict) -> None:
    """Apply grouped console/file logging defaults to *t* in place."""
    logging = t.setdefault("logging", {})
    logging.setdefault("console", {})
    logging.setdefault("file", {})
    console = logging["console"]
    file_log = logging["file"]
    for role, default_level in DEFAULT_CONSOLE_LOG_LEVELS.items():
        console.setdefault(role, default_level)
    for role, default_level in DEFAULT_FILE_LOG_LEVELS.items():
        file_log.setdefault(role, default_level)


def _apply_runtime_config_defaults(t: dict) -> None:
    """Apply runtime_config genesis/proof defaults and forbid reserved
    fields."""
    rc = t.setdefault("runtime_config", {})
    rc.setdefault("genesis", {})
    rc["genesis"].setdefault("slots_per_epoch", 48)
    rc["genesis"].setdefault("k", 10)
    rc["genesis"].setdefault("grace_period_slots", 3)
    rc.setdefault("proof", {})
    rc["proof"].setdefault("level", DEFAULT_PROOF_LEVEL)
    rc["proof"].setdefault("work_delay", 1)
    rc["proof"].setdefault("transaction_capacity", {"2_to_the": 2})
    rc.setdefault("daemon", {})

    if "ledger" in rc:
        raise TopologyError(
            ErrorCode.FORBIDDEN_FIELD,
            message="runtime_config.ledger is forbidden (generated by local-network).",
        )
    if "genesis_state_timestamp" in rc.get("genesis", {}):
        raise TopologyError(
            ErrorCode.FORBIDDEN_FIELD,
            message="runtime_config.genesis.genesis_state_timestamp is forbidden "
            "(generated by local-network).",
        )


def _apply_ledger_generation_defaults(t: dict) -> None:
    """Apply ledger_generation defaults for tiers and accounts.

    Consensus / proof values (proof_level, slots_per_epoch, k,
    grace_period_slots, work_delay, transaction_capacity_log2) are
    **not** duplicated here — runtime_config is the single source of
    truth for those fields.
    """
    lg = t.setdefault("ledger_generation", {})
    lg.setdefault("tiers", {})
    lg.setdefault("accounts", {})

    if "genesis_state_timestamp" in lg:
        raise TopologyError(
            ErrorCode.FORBIDDEN_FIELD,
            message="ledger_generation.genesis_state_timestamp is forbidden. "
            "Genesis timestamp belongs under state.genesis_timestamp.",
        )

    tier_defaults = {
        "whale": {"offline_balance": "11550000mina", "online_balance": "499mina"},
        "fish": {"offline_balance": "65500mina", "online_balance": "500mina"},
        "snark_coordinator": {"offline_balance": "5mina"},
    }
    for tier_name, defaults in tier_defaults.items():
        if tier_name in lg["tiers"]:
            for k, v in defaults.items():
                lg["tiers"][tier_name].setdefault(k, v)


def _apply_state_defaults(t: dict) -> None:
    """Apply state.mode and genesis_timestamp defaults."""
    t.setdefault("state", {})
    t["state"].setdefault("mode", DEFAULT_STATE_MODE)
    t["state"].setdefault("genesis_timestamp", {"delay": DEFAULT_GENESIS_DELAY})


def _apply_binaries_defaults(t: dict) -> None:
    """Apply binary path defaults."""
    t.setdefault("binaries", {})
    t["binaries"].setdefault("mina", "_build/default/src/app/cli/src/mina.exe")
    t["binaries"].setdefault("archive", "_build/default/src/app/archive/archive.exe")
    t["binaries"].setdefault("rosetta", "_build/default/src/app/rosetta/rosetta.exe")
    t["binaries"].setdefault(
        "zkapp",
        "_build/default/src/app/zkapp_test_transaction/zkapp_test_transaction.exe",
    )


def _apply_node_defaults(t: dict) -> None:
    """Apply per-node capability defaults and validation."""
    for _name, node in t.get("nodes", {}).items():
        caps = node.setdefault("capabilities", {})
        sc = caps.get("snark_coordinator")
        if sc is not None:
            sc.setdefault("work_selection", "seq")
            sc.setdefault("worker_pools", {})

        node.setdefault("demo_mode", False)

        if "itn_graphql" in caps:
            if not node.get("itn_keys"):
                raise TopologyError(
                    ErrorCode.MISSING_CAPABILITY,
                    message=f"Node '{_name}' has itn_graphql capability but no itn_keys field. "
                    "Set 'itn_keys' on the node to a valid key path or placeholder.",
                    entity=_name,
                )


def _apply_services_defaults(t: dict) -> None:
    """Apply per-service defaults (archive postgres, rosetta pool size)."""
    for svc_name, svc in t.get("services", {}).items():
        if svc_name == "archive" and "postgres" in svc:
            svc["postgres"].setdefault("host", "localhost")
            svc["postgres"].setdefault("port", 5432)
            svc["postgres"].setdefault("db", "archive")
        if svc_name == "rosetta":
            svc.setdefault("max_db_pool_size", 64)


def _apply_workload_defaults(t: dict) -> None:
    """Apply per-workload-type defaults using typed per-type configs.

    The raw authored workload dicts are normalized in place; per-type
    default filling uses Pydantic model defaults followed by
    ``model_dump`` back into the dict.  Unknown workload types are
    preserved unchanged with ``start`` defaulted to ``"immediate"``.
    """
    workloads: Dict[str, Any] = {}
    raw_workloads = t.get("workloads", {})
    if isinstance(raw_workloads, dict):
        for wl_name, wl_def in raw_workloads.items():
            wl = wl_def.copy()
            config = wl.setdefault("config", {})
            wl_type = wl.get("type")
            match wl_type:
                case "echo":
                    wl.setdefault("start", "immediate")
                    config.setdefault("success_exits_keep_network", True)
                case "value_transfer":
                    wl.setdefault("start", "after_sync")
                    config.setdefault("receiver", config.get("sender", ""))
                    config.setdefault("amount", "1")
                    config.setdefault("interval_seconds", 10)
                    config.setdefault("success_exits_keep_network", True)
                case "zkapp":
                    wl.setdefault("start", "after_sync")
                    config.setdefault("fee_payer_account", "whale-0")
                    config.setdefault("sender_account", "whale-1")
                    config.setdefault("transfer_amount", "1")
                    config.setdefault("receiver_amount", "1000")
                    config.setdefault("fee", "5")
                    config.setdefault("interval_seconds", 10)
                    config.setdefault("create_account", True)
                    config.setdefault("success_exits_keep_network", True)
                case "itn_max_cost":
                    wl.setdefault("start", "after_sync")
                    config.setdefault("fee_payer_account", "whale-0")
                    config.setdefault("num_zkapps_to_deploy", 2)
                    config.setdefault("max_cost_num_updates", 7)
                    config.setdefault("num_new_accounts", 0)
                    config.setdefault("account_queue_size", 0)
                    config.setdefault("memo_prefix", "maxcost")
                    config.setdefault("no_precondition", False)
                    config.setdefault("min_balance_change", "0")
                    config.setdefault("max_balance_change", "1000000000")
                    config.setdefault("min_new_zkapp_balance", "1000000000")
                    config.setdefault("max_new_zkapp_balance", "2000000000")
                    config.setdefault("init_balance", "5000000000")
                    config.setdefault("min_fee", "1000000000")
                    config.setdefault("max_fee", "2000000000")
                    config.setdefault("deployment_fee", "1000000000")
                    config.setdefault("success_exits_keep_network", True)
                    if "tps" not in config:
                        config["tps"] = None
                case _:
                    wl.setdefault("start", "immediate")
            workloads[wl_name] = wl
    t["workloads"] = workloads


def normalize_topology(raw: dict) -> dict:
    """Apply defaults and return a normalized topology dict.

    Delegates to typed helper functions for each normalization section.
    Returns a raw dict suitable for jsonschema validation.
    """
    t = raw.copy()

    # --- schema_version guard ---
    schema_version = t.get("schema_version")
    if schema_version != 1:
        raise TopologyError(
            ErrorCode.SCHEMA_VERSION_UNSUPPORTED,
            message=f"Unsupported topology schema_version {schema_version!r}. Only 1 is supported.",
        )

    _apply_logging_defaults(t)
    _apply_runtime_config_defaults(t)
    _apply_ledger_generation_defaults(t)
    _apply_state_defaults(t)
    _apply_binaries_defaults(t)
    _apply_node_defaults(t)
    _apply_services_defaults(t)
    _apply_workload_defaults(t)

    return t


def _expand_state_root(state: dict) -> str:
    """Expand ~ in state.root to the user's home directory."""
    raw = state.get("root", DEFAULT_STATE_ROOT)
    return os.path.expanduser(raw).rstrip("/")


def _get_log_levels(logging_cfg: LoggingConfig) -> Tuple[str, str, str, str]:
    """Extract daemon console/file and worker console/file log levels from grouped logging.

    Returns (node_console, node_file, worker_console, worker_file).
    """
    node_console = logging_cfg.console.get("node", DEFAULT_CONSOLE_LOG_LEVELS["node"])
    node_file = logging_cfg.file.get("node", DEFAULT_FILE_LOG_LEVELS["node"])
    worker_console = logging_cfg.console.get(
        "snark_worker", DEFAULT_CONSOLE_LOG_LEVELS["snark_worker"]
    )
    worker_file = logging_cfg.file.get(
        "snark_worker", DEFAULT_FILE_LOG_LEVELS["snark_worker"]
    )
    return node_console, node_file, worker_console, worker_file


def _derive_genesis_timestamp(state: dict) -> str:
    """Derive the genesis_timestamp in legacy format from state.genesis_timestamp.

    E.g. {'value': '2026-07-10T12:00:00Z'} -> '2026-07-10T12:00:00Z'
         {'delay': 'PT120S'} -> 'delay_sec:120'
    """
    gt = state.get("genesis_timestamp", {})
    if "value" in gt:
        return gt["value"]
    if "delay" in gt:
        secs = parse_iso_duration(gt["delay"])
        return f"delay_sec:{int(secs)}"
    # fallback
    return "delay_sec:120"


def resolve_topology(
    normalized: Union[dict, NormalizedTopology],
) -> ResolvedPlan:
    """Produce a typed ``ResolvedPlan`` from a normalized topology.

    Accepts a raw normalized dict (backward compat) or a typed
    ``NormalizedTopology`` model.  When a dict is passed it is
    validated into ``NormalizedTopology`` at the boundary.

    Returns a fully-typed ``ResolvedPlan`` with all sub-models
    (nodes, workers, services, workloads, ledger, state, binaries)
    constructed directly — no post-validation roundtrip needed.
    """
    # ── Coercion boundary: validate raw dict → typed model ──────────
    if isinstance(normalized, NormalizedTopology):
        nt = normalized
    else:
        nt = NormalizedTopology.model_validate(normalized)

    port_alloc = PortAllocator()
    state = nt.state
    state_root = _expand_state_root(state)
    node_log_level, node_file_log_level, worker_log_level, worker_file_log_level = (
        _get_log_levels(nt.logging)
    )
    proof_level = nt.runtime_config.proof.get("level", DEFAULT_PROOF_LEVEL)
    binaries = nt.binaries
    mina_exe = binaries.get("mina", "_build/default/src/app/cli/src/mina.exe")
    archive_exe = binaries.get("archive", "_build/default/src/app/archive/archive.exe")
    rosetta_exe = binaries.get("rosetta", "_build/default/src/app/rosetta/rosetta.exe")
    lg = nt.ledger_generation

    config_file = f"{state_root}/daemon.json"

    # Pre-allocate service ports so they are available during node resolution
    # (needed for -archive-address on daemon argv).
    services_def = nt.services
    prealloc_archive_port: Optional[int] = None
    if "archive" in services_def:
        prealloc_archive_port = port_alloc.allocate_single(
            pinned=services_def["archive"].get("port"), label="archive"
        )
    prealloc_rosetta_port: Optional[int] = None
    if "rosetta" in services_def:
        prealloc_rosetta_port = port_alloc.allocate_single(
            pinned=services_def["rosetta"].get("port"), label="rosetta"
        )

    # ------------------------------------------------------------------
    # Resolve nodes — Pass 1: allocate ports, identify seed
    # ------------------------------------------------------------------
    node_endpoints: Dict[str, Dict[str, int]] = {}
    seed_name: Optional[str] = None
    seed_external_port: Optional[int] = None
    multiple_seeds: List[str] = []

    node_defs = nt.nodes
    for node_name, node_def in node_defs.items():
        pinned = node_def.get("ports") or {}
        endpoint_names = ["client", "rest", "external", "metrics", "libp2p_metrics"]
        if has_capability(node_def, "itn_graphql"):
            endpoint_names.append("itn_graphql")

        port_map: Dict[str, int] = {}
        for ename in endpoint_names:
            pinned_port = pinned.get(ename)
            port_map[ename] = port_alloc.allocate_single(
                pinned=pinned_port, label=f"{node_name}.{ename}"
            )
        node_endpoints[node_name] = port_map

        if has_capability(node_def, "p2p_seed"):
            if seed_name is not None:
                multiple_seeds.append(node_name)
            else:
                seed_name = node_name
                seed_external_port = port_map["external"]

    if seed_name is None:
        raise TopologyError(
            ErrorCode.NO_SEED_NODE,
            message="Topology must have at least one node with p2p_seed capability",
        )
    if multiple_seeds:
        raise TopologyError(
            ErrorCode.MULTIPLE_SEEDS,
            message=f"Multiple seed nodes detected: {seed_name}, {', '.join(multiple_seeds)}. "
            "Only one p2p_seed node is supported.",
        )

    # Compute seed peer_id once so it is available for all non-seed nodes
    # regardless of dictionary iteration order.
    seed_peer_id = SEED_PEER_ID.format(external_port=seed_external_port)

    # ------------------------------------------------------------------
    # Resolve nodes — Pass 2: build argv / env
    # ------------------------------------------------------------------
    resolved_nodes: List[ResolvedNode] = []

    for node_name, node_def in node_defs.items():
        port_map = node_endpoints[node_name]

        client_port = port_map["client"]
        rest_port = port_map["rest"]
        external_port = port_map["external"]
        metrics_port = port_map["metrics"]
        libp2p_metrics_port = port_map["libp2p_metrics"]
        itn_graphql_port = port_map.get("itn_graphql")
        config_dir = f"{state_root}/nodes/{node_name}"

        caps = node_def.get("capabilities", {})

        # Env map
        node_env: Dict[str, str] = {}
        if has_capability(node_def, "itn_graphql"):
            node_env["ITN_FEATURES"] = "1"

        # Capabilities list (flattened convenience for resolved plan)
        capability_list = []
        if "p2p_seed" in caps:
            capability_list.append("p2p_seed")
        if "block_producer" in caps:
            capability_list.append("block_producer")
        if "snark_coordinator" in caps:
            capability_list.append("snark_coordinator")
        if "itn_graphql" in caps:
            capability_list.append("itn_graphql")

        # Build daemon argv
        daemon_argv = [mina_exe, "daemon"]

        # Core ports
        daemon_argv += [
            "--client-port",
            str(client_port),
            "--rest-port",
            str(rest_port),
            "--insecure-rest-server",
            "--external-port",
            str(external_port),
            "--metrics-port",
            str(metrics_port),
            "--libp2p-metrics-port",
            str(libp2p_metrics_port),
        ]

        # Archive integration — stream blocks to archive service
        if prealloc_archive_port is not None:
            daemon_argv += ["-archive-address", str(prealloc_archive_port)]

        # Config & logging (use node console/file values for daemon)
        daemon_argv += [
            "--config-file",
            config_file,
            "--log-level",
            node_log_level,
            "--file-log-level",
            node_file_log_level,
            "--precomputed-blocks-file",
            f"{config_dir}/precomputed_blocks.log",
            "--log-precomputed-blocks",
            "false",
            "--proof-level",
            proof_level,
        ]

        # Seed / peer args — seed_peer_id was computed in Pass 1
        if has_capability(node_def, "p2p_seed"):
            daemon_argv.append("--seed")
            daemon_argv += ["--libp2p-keypair", SEED_PEER_KEY]
            node_peer_id = seed_peer_id
        else:
            daemon_argv += ["--peer", seed_peer_id]
            node_peer_id = None

        # Block producer — from capabilities.block_producer.account
        bp_key_path: Optional[str] = None
        bp_cap = caps.get("block_producer")
        if bp_cap:
            bp_tier, bp_idx = parse_account_spec(bp_cap["account"])
            # Validate index against tier count
            tiers_def = lg.get("tiers", {})
            tier_def = tiers_def.get(bp_tier, {})
            tier_count = tier_def.get("count", 0)
            if bp_idx >= tier_count:
                raise TopologyError(
                    ErrorCode.NODE_CONFIG,
                    message=f"block_producer account {bp_cap['account']!r} index "
                    f"exceeds {bp_tier} tier count {tier_count}.",
                    entity=node_name,
                )
            key_path = (
                f"{state_root}/online_{bp_tier}_keys/online_{bp_tier}_account_{bp_idx}"
            )
            daemon_argv += ["--block-producer-key", key_path]
            bp_key_path = key_path

        # Snark coordinator
        sc = caps.get("snark_coordinator")
        if sc:
            coord_pubkey = sc.get("public_key", "")
            if not coord_pubkey:
                # Unresolved token — keys don't exist at plan time.
                # Materialize will capture the actual pubkey content and a
                # future spawn slice will substitute it.
                coord_pubkey = "<pubkey:snark_coordinator_account>"
            fee_raw = sc.get("fee", "0.001")
            daemon_argv += [
                "-snark-worker-fee",
                fee_raw,
                "-run-snark-coordinator",
                coord_pubkey,
                "-work-selection",
                sc.get("work_selection", "seq"),
            ]

        # Demo mode
        if node_def.get("demo_mode"):
            daemon_argv.append("--demo-mode")

        # ITN GraphQL — requires itn_keys on the node
        if has_capability(node_def, "itn_graphql") and itn_graphql_port is not None:
            daemon_argv += ["--itn-graphql-port", str(itn_graphql_port)]
            itn_keys_val = node_def.get("itn_keys", "")
            if not itn_keys_val:
                raise TopologyError(
                    ErrorCode.MISSING_CAPABILITY,
                    message=f"Node '{node_name}' has itn_graphql capability but no itn_keys field.",
                    entity=node_name,
                )
            daemon_argv += ["--itn-keys", itn_keys_val]

        # Extra args
        extra = node_def.get("extra_args") or []
        daemon_argv += extra

        # Config directory (always at the end, mirroring Bash)
        daemon_argv += ["--config-directory", config_dir]

        # Build resolved snark_coordinator info
        resolved_sc: Optional[SnarkCoordinatorInfo] = None
        if sc:
            # Validate fee_receiver against ledger accounts
            fee_recv = sc.get("fee_receiver")
            if fee_recv:
                named_accounts = lg.get("accounts", {})
                tier_pattern = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*-\d+$")
                if fee_recv not in named_accounts and not tier_pattern.match(fee_recv):
                    raise TopologyError(
                        ErrorCode.NODE_CONFIG,
                        message=f"snark_coordinator.fee_receiver {fee_recv!r} is "
                        f"not a named account in ledger_generation.accounts "
                        f"and does not match a tier account pattern (e.g. 'whale-0').",
                        entity=node_name,
                    )
            resolved_sc = SnarkCoordinatorInfo(
                fee=sc.get("fee"),
                fee_receiver=fee_recv,
                work_selection=sc.get("work_selection"),
                worker_pools=sc.get("worker_pools", {}),
            )

        resolved_nodes.append(
            ResolvedNode(
                name=node_name,
                endpoints={
                    ename: Endpoint(port=port, host="127.0.0.1")
                    for ename, port in port_map.items()
                },
                peer_id=node_peer_id,
                capabilities=capability_list,
                daemon_argv=daemon_argv,
                env=node_env,
                config_dir=config_dir,
                config_file=config_file,
                block_producer_key_path=bp_key_path,
                snark_coordinator=resolved_sc,
            )
        )

    # ------------------------------------------------------------------
    # Resolve external workers from snark_coordinator.worker_pools
    # ------------------------------------------------------------------
    resolved_workers: List[ResolvedWorker] = []
    node_defs = nt.nodes

    for node_name, node_def in node_defs.items():
        caps = node_def.get("capabilities", {})
        sc = caps.get("snark_coordinator")
        if not sc:
            continue

        worker_pools = sc.get("worker_pools", {})
        if not worker_pools:
            continue

        coordinator_port = node_endpoints.get(node_name, {}).get("client")
        if coordinator_port is None:
            continue
        coord_addr = f"127.0.0.1:{coordinator_port}"

        for pool_name, pool_def in worker_pools.items():
            count = pool_def.get("count", 0)
            if count <= 0:
                continue

            # Parse nap from ISO duration
            nap_raw = pool_def.get("nap", "PT1S")
            nap_sec = parse_iso_duration(nap_raw)

            for i in range(count):
                worker_config_dir = (
                    f"{state_root}/nodes/snark_workers/{node_name}_{pool_name}_{i}"
                )

                # Snark worker argv (use snark_worker console/file log levels)
                worker_argv = [
                    mina_exe,
                    "internal",
                    "snark-worker",
                    "--proof-level",
                    proof_level,
                    "--shutdown-on-disconnect",
                    "false",
                    "--log-level",
                    worker_log_level,
                    "--file-log-level",
                    worker_file_log_level,
                    "--daemon-address",
                    coord_addr,
                    "--config-directory",
                    worker_config_dir,
                ]

                resolved_workers.append(
                    ResolvedWorker(
                        name=f"{node_name}_{pool_name}_{i}",
                        coordinator_node=node_name,
                        coordinator_port=coordinator_port,
                        daemon_address=coord_addr,
                        worker_argv=worker_argv,
                        config_dir=worker_config_dir,
                        env={
                            "MINA_SNARK_WORKER_NAP_SEC": str(nap_sec),
                        },
                    )
                )

    # ------------------------------------------------------------------
    # Resolve services
    # ------------------------------------------------------------------
    resolved_services: List[ResolvedService] = []
    console = nt.logging.console

    # Archive
    if "archive" in services_def:
        arch = services_def["archive"]
        arch_binary = arch.get("binary", archive_exe)
        pg_uri = resolve_postgres_config(arch.get("postgres", {}))

        archive_log_level = console.get(
            "archive", DEFAULT_CONSOLE_LOG_LEVELS["archive"]
        )
        archive_config_dir = f"{state_root}/services/archive"
        archive_argv = [
            arch_binary,
            "run",
            "--config-file",
            config_file,
            "--log-level",
            archive_log_level,
            "--postgres-uri",
            pg_uri,
            "--server-port",
            str(prealloc_archive_port),
        ]
        resolved_services.append(
            ResolvedService(
                name="archive",
                kind=ServiceKind.ARCHIVE,
                binary=arch_binary,
                port=prealloc_archive_port,
                argv=archive_argv,
                postgres_uri=pg_uri,
                config_dir=archive_config_dir,
                env={},
            )
        )

    # Rosetta
    if "rosetta" in services_def:
        ros = services_def["rosetta"]
        ros_binary = ros.get("binary", rosetta_exe)
        max_pool_size = ros.get("max_db_pool_size", 64)

        # Rosetta requires archive (for postgres_uri) and daemon (for graphql_uri)
        if "archive" not in services_def:
            raise TopologyError(
                ErrorCode.SERVICE_MISSING_DEPENDENCY,
                message="The 'rosetta' service requires an 'archive' service in the "
                'topology to provide a Postgres URI.  Add "archive": {...} '
                "to the services section.",
            )

        # Postgres URI for Rosetta (reuse archive postgres definition)
        pg_uri = resolve_postgres_config(services_def["archive"].get("postgres", {}))

        # Resolve GraphQL URI: connect to seed's REST port correctly
        # Use full URL — do NOT copy the Bash bare-port bug.
        rest_port = None
        if seed_name and seed_name in node_endpoints:
            rest_port = node_endpoints[seed_name].get("rest")
        if not rest_port:
            raise TopologyError(
                ErrorCode.SERVICE_MISSING_DEPENDENCY,
                message="The 'rosetta' service requires a daemon node (GraphQL endpoint) "
                "to connect to.  Add at least one node to the topology.",
            )
        graphql_uri = f"http://127.0.0.1:{rest_port}/graphql"

        rosetta_log_level = console.get(
            "rosetta", DEFAULT_CONSOLE_LOG_LEVELS["rosetta"]
        )
        rosetta_config_dir = f"{state_root}/services/rosetta"
        rosetta_argv = [
            ros_binary,
            "--archive-uri",
            pg_uri,
            "--graphql-uri",
            graphql_uri,
            "--port",
            str(prealloc_rosetta_port),
            "--log-level",
            rosetta_log_level,
        ]
        resolved_services.append(
            ResolvedService(
                name="rosetta",
                kind=ServiceKind.ROSETTA,
                binary=ros_binary,
                port=prealloc_rosetta_port,
                argv=rosetta_argv,
                env={
                    "MINA_ROSETTA_MAX_DB_POOL_SIZE": str(max_pool_size),
                },
                postgres_uri=pg_uri,
                graphql_uri=graphql_uri,
                config_dir=rosetta_config_dir,
            )
        )

    # ------------------------------------------------------------------
    # Resolve ledger accounts — consensus/proof values come exclusively
    # from runtime_config; ledger_generation is only tiers/accounts.
    # ------------------------------------------------------------------
    genesis_ts = _derive_genesis_timestamp(state)
    tiers: Dict[str, TierDefinition] = {}
    for tier_name, tier_def in lg.get("tiers", {}).items():
        tiers[tier_name] = TierDefinition(**tier_def)
    rc_genesis = nt.runtime_config.genesis
    rc_proof = nt.runtime_config.proof
    rc_daemon = nt.runtime_config.daemon
    ledger_plan = LedgerPlan(
        tiers=tiers,
        accounts=lg.get("accounts", {}),
        genesis_state_timestamp=genesis_ts,
        config=LedgerConfig(
            genesis=GenesisLedgerConfig(
                slots_per_epoch=int(rc_genesis.get("slots_per_epoch", 48)),
                k=int(rc_genesis.get("k", 10)),
                grace_period_slots=int(rc_genesis.get("grace_period_slots", 3)),
                genesis_state_timestamp="<generated>",
            ),
            proof=ProofLedgerConfig(
                work_delay=int(rc_proof.get("work_delay", 1)),
                level=str(rc_proof.get("level", DEFAULT_PROOF_LEVEL)),
                transaction_capacity={
                    "2_to_the": int(
                        rc_proof.get("transaction_capacity", {}).get("2_to_the", 2)
                    ),
                },
                block_window_duration_ms=rc_proof.get("block_window_duration_ms"),
            ),
            daemon=DaemonRuntimeConfig(
                slot_tx_end=rc_daemon.get("slot_tx_end"),
                slot_chain_end=rc_daemon.get("slot_chain_end"),
                hard_fork_genesis_slot_delta=rc_daemon.get(
                    "hard_fork_genesis_slot_delta"
                ),
            ),
        ),
        key_dirs={
            "offline_whale": f"{state_root}/offline_whale_keys",
            "online_whale": f"{state_root}/online_whale_keys",
            "offline_fish": f"{state_root}/offline_fish_keys",
            "online_fish": f"{state_root}/online_fish_keys",
            "snark_coordinator": f"{state_root}/snark_coordinator_keys",
            "libp2p": f"{state_root}/libp2p_keys",
        },
        extra_accounts_file=lg.get("extra_accounts_file", ""),
    )

    # ------------------------------------------------------------------
    # Resolve workloads
    # ------------------------------------------------------------------
    # Derive the target daemon GraphQL URI (first daemon node's REST port)
    workload_graphql_uri: Optional[str] = None
    workload_itn_graphql_uri: Optional[str] = None
    if seed_name and seed_name in node_endpoints:
        rest_port = node_endpoints[seed_name].get("rest")
        if rest_port is not None:
            workload_graphql_uri = f"http://127.0.0.1:{rest_port}/graphql"
        itn_gql_port = node_endpoints[seed_name].get("itn_graphql")
        if itn_gql_port is not None:
            workload_itn_graphql_uri = f"http://127.0.0.1:{itn_gql_port}/graphql"

    # Compute auto TPS from runtime_config.proof.block_window_duration_ms
    block_window_ms: Optional[int] = nt.runtime_config.proof.get(
        "block_window_duration_ms"
    )
    if block_window_ms is None:
        # Fallback default matching single-node preset
        block_window_ms = 131400
    auto_tps: float = 2.0 / ((block_window_ms / 1000.0) / 0.75)

    resolved_workloads: List[WorkloadConfig] = []
    for wl_name, wl in nt.workloads.items():
        wl_type = WorkloadType(wl.type)
        wl_start = wl.start
        wl_config = wl.config
        entry: WorkloadConfig
        match wl_type:
            case WorkloadType.ECHO:
                cfg = NormalizedEchoWorkloadConfig.model_validate(wl_config)
                entry = EchoWorkload(
                    name=wl_name,
                    start=wl_start,
                    argv=cfg.argv,
                    env=cfg.env,
                    success_exits_keep_network=cfg.success_exits_keep_network,
                    graphql_uri=workload_graphql_uri,
                )
            case WorkloadType.VALUE_TRANSFER:
                cfg = NormalizedValueTransferWorkloadConfig.model_validate(wl_config)
                entry = ValueTransferWorkload(
                    name=wl_name,
                    start=wl_start,
                    sender=cfg.sender,
                    receiver=cfg.receiver,
                    amount=cfg.amount,
                    interval_seconds=cfg.interval_seconds,
                    count=cfg.count,
                    success_exits_keep_network=cfg.success_exits_keep_network,
                    graphql_uri=workload_graphql_uri,
                )
            case WorkloadType.ZKAPP:
                cfg = NormalizedZkappWorkloadConfig.model_validate(wl_config)
                entry = ZkappWorkload(
                    name=wl_name,
                    start=wl_start,
                    fee_payer_account=cfg.fee_payer_account,
                    sender_account=cfg.sender_account,
                    transfer_amount=cfg.transfer_amount,
                    receiver_amount=cfg.receiver_amount,
                    fee=cfg.fee,
                    interval_seconds=cfg.interval_seconds,
                    count=cfg.count,
                    create_account=cfg.create_account,
                    success_exits_keep_network=cfg.success_exits_keep_network,
                    graphql_uri=workload_graphql_uri,
                )
            case WorkloadType.ITN_MAX_COST:
                # tps auto-resolution — handles None, numbers, and str "auto"
                raw_tps = wl_config.get("tps")
                if raw_tps is None:
                    resolved_tps: Optional[float] = auto_tps
                elif isinstance(raw_tps, (int, float)):
                    resolved_tps = float(raw_tps)
                elif isinstance(raw_tps, str) and raw_tps == "auto":
                    resolved_tps = auto_tps
                elif isinstance(raw_tps, str):
                    resolved_tps = float(raw_tps)
                else:
                    resolved_tps = auto_tps
                cfg = NormalizedItnMaxCostWorkloadConfig.model_validate(wl_config)
                entry = ItnMaxCostWorkload(
                    name=wl_name,
                    start=wl_start,
                    fee_payer_account=cfg.fee_payer_account,
                    duration_min=cfg.duration_min,
                    tps=resolved_tps,
                    num_zkapps_to_deploy=cfg.num_zkapps_to_deploy,
                    max_cost_num_updates=cfg.max_cost_num_updates,
                    num_new_accounts=cfg.num_new_accounts,
                    account_queue_size=cfg.account_queue_size,
                    memo_prefix=cfg.memo_prefix,
                    no_precondition=cfg.no_precondition,
                    min_balance_change=cfg.min_balance_change,
                    max_balance_change=cfg.max_balance_change,
                    min_new_zkapp_balance=cfg.min_new_zkapp_balance,
                    max_new_zkapp_balance=cfg.max_new_zkapp_balance,
                    init_balance=cfg.init_balance,
                    min_fee=cfg.min_fee,
                    max_fee=cfg.max_fee,
                    deployment_fee=cfg.deployment_fee,
                    success_exits_keep_network=cfg.success_exits_keep_network,
                    graphql_uri=workload_graphql_uri,
                    itn_graphql_uri=workload_itn_graphql_uri,
                )
            case _:
                if wl_start:
                    # Unknown type — preserve as dict for forward compat
                    import warnings

                    warnings.warn(
                        f"Unknown workload type '{wl.type}' for workload '{wl_name}'; "
                        f"will not be included in the resolved plan.",
                        RuntimeWarning,
                    )
                continue
        resolved_workloads.append(entry)

    # ------------------------------------------------------------------
    # Build and return typed ResolvedPlan
    # ------------------------------------------------------------------
    gt = state.get("genesis_timestamp", {"delay": DEFAULT_GENESIS_DELAY})
    gt_kwargs: Dict[str, Any] = {
        "delay": gt.get("delay", DEFAULT_GENESIS_DELAY),
    }
    if "value" in gt:
        gt_kwargs["value"] = gt["value"]
    return ResolvedPlan(
        state=PlanState(
            root=state_root,
            mode=state.get("mode", DEFAULT_STATE_MODE),
            genesis_timestamp=GenesisTimestamp(**gt_kwargs),
            config_file=config_file,
            extra_files_root=state.get("extra_files_root", ""),
        ),
        binaries=BinariesConfig(**binaries),
        nodes=resolved_nodes,
        workers=resolved_workers,
        services=resolved_services,
        workloads=resolved_workloads,
        ledger=ledger_plan,
    )


def to_resolved_plan(plan_dict: dict) -> ResolvedPlan:
    """Validate and construct a typed ``ResolvedPlan`` from a plan dict.

    Accepts the plain dict produced by ``resolve_topology`` or read back
    from a persisted ``network-plan.json``.  Returns a fully validated
    ``ResolvedPlan`` model with typed node / worker / service sub-models.

    Callers that still consume ``dict`` can use ``plan.model_dump(mode="json")``
    for backward compatibility at old boundaries.

    Wraps Pydantic ``ValidationError`` into ``PlanError`` so that malformed
    persisted plans produce a structured error rather than a raw traceback.
    """
    from mln.errors import ErrorCode, PlanError

    try:
        return ResolvedPlan.model_validate(plan_dict)
    except Exception as exc:
        # Only wrap Pydantic validation failures; let other structural
        # errors (e.g. TypeError) bubble up as-is.
        try:
            from pydantic import ValidationError as _PydanticValidationError

            if isinstance(exc, _PydanticValidationError):
                raise PlanError(
                    ErrorCode.PLAN_PARSE_ERROR,
                    message=f"Persisted plan is malformed: {exc}",
                ) from exc
        except PlanError:
            raise
        except Exception:
            pass
        raise
