// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./kimchi_napi.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./kimchi_napi.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./kimchi_napi.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-win32-x64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./kimchi_napi.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./kimchi_napi.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./kimchi_napi.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./kimchi_napi.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      return require('@o1js/native-darwin-universal')
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./kimchi_napi.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./kimchi_napi.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./kimchi_napi.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./kimchi_napi.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./kimchi_napi.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-x64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./kimchi_napi.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-x64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./kimchi_napi.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-arm64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./kimchi_napi.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-arm64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./kimchi_napi.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-arm-musleabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./kimchi_napi.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-arm-gnueabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./kimchi_napi.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-loong64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./kimchi_napi.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-loong64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./kimchi_napi.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-riscv64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./kimchi_napi.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@o1js/native-linux-riscv64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./kimchi_napi.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./kimchi_napi.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./kimchi_napi.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-openharmony-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./kimchi_napi.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-openharmony-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./kimchi_napi.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@o1js/native-openharmony-arm')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./kimchi_napi.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('@o1js/native-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.WasmFpGateVector = nativeBinding.WasmFpGateVector
module.exports.NapiFpGateVector = nativeBinding.NapiFpGateVector
module.exports.WasmFpLookupCommitments = nativeBinding.WasmFpLookupCommitments
module.exports.NapiFpLookupCommitments = nativeBinding.NapiFpLookupCommitments
module.exports.WasmFpOpeningProof = nativeBinding.WasmFpOpeningProof
module.exports.NapiFpOpeningProof = nativeBinding.NapiFpOpeningProof
module.exports.WasmFpOracles = nativeBinding.WasmFpOracles
module.exports.NapiFpOracles = nativeBinding.NapiFpOracles
module.exports.WasmFpPolyComm = nativeBinding.WasmFpPolyComm
module.exports.NapiFpPolyComm = nativeBinding.NapiFpPolyComm
module.exports.WasmFpProverCommitments = nativeBinding.WasmFpProverCommitments
module.exports.NapiFpProverCommitments = nativeBinding.NapiFpProverCommitments
module.exports.WasmFpProverProof = nativeBinding.WasmFpProverProof
module.exports.NapiFpProverProof = nativeBinding.NapiFpProverProof
module.exports.WasmFpRandomOracles = nativeBinding.WasmFpRandomOracles
module.exports.NapiFpRandomOracles = nativeBinding.NapiFpRandomOracles
module.exports.WasmFpSrs = nativeBinding.WasmFpSrs
module.exports.NapiFpSrs = nativeBinding.NapiFpSrs
module.exports.WasmFqGateVector = nativeBinding.WasmFqGateVector
module.exports.NapiFqGateVector = nativeBinding.NapiFqGateVector
module.exports.WasmFqLookupCommitments = nativeBinding.WasmFqLookupCommitments
module.exports.NapiFqLookupCommitments = nativeBinding.NapiFqLookupCommitments
module.exports.WasmFqOpeningProof = nativeBinding.WasmFqOpeningProof
module.exports.NapiFqOpeningProof = nativeBinding.NapiFqOpeningProof
module.exports.WasmFqOracles = nativeBinding.WasmFqOracles
module.exports.NapiFqOracles = nativeBinding.NapiFqOracles
module.exports.WasmFqPolyComm = nativeBinding.WasmFqPolyComm
module.exports.NapiFqPolyComm = nativeBinding.NapiFqPolyComm
module.exports.WasmFqProverCommitments = nativeBinding.WasmFqProverCommitments
module.exports.NapiFqProverCommitments = nativeBinding.NapiFqProverCommitments
module.exports.WasmFqProverProof = nativeBinding.WasmFqProverProof
module.exports.NapiFqProverProof = nativeBinding.NapiFqProverProof
module.exports.WasmFqRandomOracles = nativeBinding.WasmFqRandomOracles
module.exports.NapiFqRandomOracles = nativeBinding.NapiFqRandomOracles
module.exports.WasmFqSrs = nativeBinding.WasmFqSrs
module.exports.NapiFqSrs = nativeBinding.NapiFqSrs
module.exports.WasmPastaFpLookupTable = nativeBinding.WasmPastaFpLookupTable
module.exports.NapiPastaFpLookupTable = nativeBinding.NapiPastaFpLookupTable
module.exports.WasmPastaFpPlonkIndex = nativeBinding.WasmPastaFpPlonkIndex
module.exports.WasmPastaFpRuntimeTableCfg = nativeBinding.WasmPastaFpRuntimeTableCfg
module.exports.NapiPastaFpRuntimeTableCfg = nativeBinding.NapiPastaFpRuntimeTableCfg
module.exports.WasmPastaFqLookupTable = nativeBinding.WasmPastaFqLookupTable
module.exports.NapiPastaFqLookupTable = nativeBinding.NapiPastaFqLookupTable
module.exports.WasmPastaFqPlonkIndex = nativeBinding.WasmPastaFqPlonkIndex
module.exports.WasmPastaFqRuntimeTableCfg = nativeBinding.WasmPastaFqRuntimeTableCfg
module.exports.NapiPastaFqRuntimeTableCfg = nativeBinding.NapiPastaFqRuntimeTableCfg
module.exports.WasmVecVecFp = nativeBinding.WasmVecVecFp
module.exports.NapiVecVecFp = nativeBinding.NapiVecVecFp
module.exports.WasmVecVecFq = nativeBinding.WasmVecVecFq
module.exports.NapiVecVecFq = nativeBinding.NapiVecVecFq
module.exports.ARCH_NAME = nativeBinding.ARCH_NAME
module.exports.BACKING = nativeBinding.BACKING
module.exports.caml_fp_srs_add_lagrange_basis = nativeBinding.caml_fp_srs_add_lagrange_basis
module.exports.caml_fp_srs_b_poly_commitment = nativeBinding.caml_fp_srs_b_poly_commitment
module.exports.caml_fp_srs_batch_accumulator_check = nativeBinding.caml_fp_srs_batch_accumulator_check
module.exports.caml_fp_srs_batch_accumulator_generate = nativeBinding.caml_fp_srs_batch_accumulator_generate
module.exports.caml_fp_srs_commit_evaluations = nativeBinding.caml_fp_srs_commit_evaluations
module.exports.caml_fp_srs_create = nativeBinding.caml_fp_srs_create
module.exports.caml_fp_srs_create_parallel = nativeBinding.caml_fp_srs_create_parallel
module.exports.caml_fp_srs_from_bytes = nativeBinding.caml_fp_srs_from_bytes
module.exports.caml_fp_srs_from_raw_bytes = nativeBinding.caml_fp_srs_from_raw_bytes
module.exports.caml_fp_srs_get = nativeBinding.caml_fp_srs_get
module.exports.caml_fp_srs_get_lagrange_basis = nativeBinding.caml_fp_srs_get_lagrange_basis
module.exports.caml_fp_srs_h = nativeBinding.caml_fp_srs_h
module.exports.caml_fp_srs_lagrange_commitment = nativeBinding.caml_fp_srs_lagrange_commitment
module.exports.caml_fp_srs_lagrange_commitments_whole_domain_ptr = nativeBinding.caml_fp_srs_lagrange_commitments_whole_domain_ptr
module.exports.caml_fp_srs_length = nativeBinding.caml_fp_srs_length
module.exports.caml_fp_srs_maybe_lagrange_commitment = nativeBinding.caml_fp_srs_maybe_lagrange_commitment
module.exports.caml_fp_srs_read = nativeBinding.caml_fp_srs_read
module.exports.caml_fp_srs_set = nativeBinding.caml_fp_srs_set
module.exports.caml_fp_srs_set_lagrange_basis = nativeBinding.caml_fp_srs_set_lagrange_basis
module.exports.caml_fp_srs_to_bytes = nativeBinding.caml_fp_srs_to_bytes
module.exports.caml_fp_srs_to_raw_bytes = nativeBinding.caml_fp_srs_to_raw_bytes
module.exports.caml_fp_srs_write = nativeBinding.caml_fp_srs_write
module.exports.caml_fq_srs_add_lagrange_basis = nativeBinding.caml_fq_srs_add_lagrange_basis
module.exports.caml_fq_srs_b_poly_commitment = nativeBinding.caml_fq_srs_b_poly_commitment
module.exports.caml_fq_srs_batch_accumulator_check = nativeBinding.caml_fq_srs_batch_accumulator_check
module.exports.caml_fq_srs_batch_accumulator_generate = nativeBinding.caml_fq_srs_batch_accumulator_generate
module.exports.caml_fq_srs_commit_evaluations = nativeBinding.caml_fq_srs_commit_evaluations
module.exports.caml_fq_srs_create = nativeBinding.caml_fq_srs_create
module.exports.caml_fq_srs_create_parallel = nativeBinding.caml_fq_srs_create_parallel
module.exports.caml_fq_srs_from_bytes = nativeBinding.caml_fq_srs_from_bytes
module.exports.caml_fq_srs_from_raw_bytes = nativeBinding.caml_fq_srs_from_raw_bytes
module.exports.caml_fq_srs_get = nativeBinding.caml_fq_srs_get
module.exports.caml_fq_srs_get_lagrange_basis = nativeBinding.caml_fq_srs_get_lagrange_basis
module.exports.caml_fq_srs_h = nativeBinding.caml_fq_srs_h
module.exports.caml_fq_srs_lagrange_commitment = nativeBinding.caml_fq_srs_lagrange_commitment
module.exports.caml_fq_srs_lagrange_commitments_whole_domain_ptr = nativeBinding.caml_fq_srs_lagrange_commitments_whole_domain_ptr
module.exports.caml_fq_srs_length = nativeBinding.caml_fq_srs_length
module.exports.caml_fq_srs_maybe_lagrange_commitment = nativeBinding.caml_fq_srs_maybe_lagrange_commitment
module.exports.caml_fq_srs_read = nativeBinding.caml_fq_srs_read
module.exports.caml_fq_srs_set = nativeBinding.caml_fq_srs_set
module.exports.caml_fq_srs_set_lagrange_basis = nativeBinding.caml_fq_srs_set_lagrange_basis
module.exports.caml_fq_srs_to_bytes = nativeBinding.caml_fq_srs_to_bytes
module.exports.caml_fq_srs_to_raw_bytes = nativeBinding.caml_fq_srs_to_raw_bytes
module.exports.caml_fq_srs_write = nativeBinding.caml_fq_srs_write
module.exports.caml_pallas_affine_one = nativeBinding.caml_pallas_affine_one
module.exports.caml_pasta_fp_plonk_circuit_serialize = nativeBinding.caml_pasta_fp_plonk_circuit_serialize
module.exports.caml_pasta_fp_plonk_gate_vector_add = nativeBinding.caml_pasta_fp_plonk_gate_vector_add
module.exports.caml_pasta_fp_plonk_gate_vector_create = nativeBinding.caml_pasta_fp_plonk_gate_vector_create
module.exports.caml_pasta_fp_plonk_gate_vector_digest = nativeBinding.caml_pasta_fp_plonk_gate_vector_digest
module.exports.caml_pasta_fp_plonk_gate_vector_from_bytes = nativeBinding.caml_pasta_fp_plonk_gate_vector_from_bytes
module.exports.caml_pasta_fp_plonk_gate_vector_get = nativeBinding.caml_pasta_fp_plonk_gate_vector_get
module.exports.caml_pasta_fp_plonk_gate_vector_len = nativeBinding.caml_pasta_fp_plonk_gate_vector_len
module.exports.caml_pasta_fp_plonk_gate_vector_to_bytes = nativeBinding.caml_pasta_fp_plonk_gate_vector_to_bytes
module.exports.caml_pasta_fp_plonk_gate_vector_wrap = nativeBinding.caml_pasta_fp_plonk_gate_vector_wrap
module.exports.caml_pasta_fp_plonk_index_create = nativeBinding.caml_pasta_fp_plonk_index_create
module.exports.caml_pasta_fp_plonk_index_decode = nativeBinding.caml_pasta_fp_plonk_index_decode
module.exports.caml_pasta_fp_plonk_index_domain_d1_size = nativeBinding.caml_pasta_fp_plonk_index_domain_d1_size
module.exports.caml_pasta_fp_plonk_index_domain_d4_size = nativeBinding.caml_pasta_fp_plonk_index_domain_d4_size
module.exports.caml_pasta_fp_plonk_index_encode = nativeBinding.caml_pasta_fp_plonk_index_encode
module.exports.caml_pasta_fp_plonk_index_max_degree = nativeBinding.caml_pasta_fp_plonk_index_max_degree
module.exports.caml_pasta_fp_plonk_index_public_inputs = nativeBinding.caml_pasta_fp_plonk_index_public_inputs
module.exports.caml_pasta_fp_plonk_index_read = nativeBinding.caml_pasta_fp_plonk_index_read
module.exports.caml_pasta_fp_plonk_index_write = nativeBinding.caml_pasta_fp_plonk_index_write
module.exports.caml_pasta_fp_plonk_proof_batch_verify = nativeBinding.caml_pasta_fp_plonk_proof_batch_verify
module.exports.caml_pasta_fp_plonk_proof_create = nativeBinding.caml_pasta_fp_plonk_proof_create
module.exports.caml_pasta_fp_plonk_proof_deep_copy = nativeBinding.caml_pasta_fp_plonk_proof_deep_copy
module.exports.caml_pasta_fp_plonk_proof_dummy = nativeBinding.caml_pasta_fp_plonk_proof_dummy
module.exports.caml_pasta_fp_plonk_proof_verify = nativeBinding.caml_pasta_fp_plonk_proof_verify
module.exports.caml_pasta_fp_plonk_verifier_index_create = nativeBinding.caml_pasta_fp_plonk_verifier_index_create
module.exports.caml_pasta_fp_plonk_verifier_index_deep_copy = nativeBinding.caml_pasta_fp_plonk_verifier_index_deep_copy
module.exports.caml_pasta_fp_plonk_verifier_index_deserialize = nativeBinding.caml_pasta_fp_plonk_verifier_index_deserialize
module.exports.caml_pasta_fp_plonk_verifier_index_dummy = nativeBinding.caml_pasta_fp_plonk_verifier_index_dummy
module.exports.caml_pasta_fp_plonk_verifier_index_read = nativeBinding.caml_pasta_fp_plonk_verifier_index_read
module.exports.caml_pasta_fp_plonk_verifier_index_serialize = nativeBinding.caml_pasta_fp_plonk_verifier_index_serialize
module.exports.caml_pasta_fp_plonk_verifier_index_shifts = nativeBinding.caml_pasta_fp_plonk_verifier_index_shifts
module.exports.caml_pasta_fp_plonk_verifier_index_write = nativeBinding.caml_pasta_fp_plonk_verifier_index_write
module.exports.caml_pasta_fp_poseidon_block_cipher = nativeBinding.caml_pasta_fp_poseidon_block_cipher
module.exports.caml_pasta_fq_plonk_circuit_serialize = nativeBinding.caml_pasta_fq_plonk_circuit_serialize
module.exports.caml_pasta_fq_plonk_gate_vector_add = nativeBinding.caml_pasta_fq_plonk_gate_vector_add
module.exports.caml_pasta_fq_plonk_gate_vector_create = nativeBinding.caml_pasta_fq_plonk_gate_vector_create
module.exports.caml_pasta_fq_plonk_gate_vector_digest = nativeBinding.caml_pasta_fq_plonk_gate_vector_digest
module.exports.caml_pasta_fq_plonk_gate_vector_from_bytes = nativeBinding.caml_pasta_fq_plonk_gate_vector_from_bytes
module.exports.caml_pasta_fq_plonk_gate_vector_get = nativeBinding.caml_pasta_fq_plonk_gate_vector_get
module.exports.caml_pasta_fq_plonk_gate_vector_len = nativeBinding.caml_pasta_fq_plonk_gate_vector_len
module.exports.caml_pasta_fq_plonk_gate_vector_to_bytes = nativeBinding.caml_pasta_fq_plonk_gate_vector_to_bytes
module.exports.caml_pasta_fq_plonk_gate_vector_wrap = nativeBinding.caml_pasta_fq_plonk_gate_vector_wrap
module.exports.caml_pasta_fq_plonk_index_create = nativeBinding.caml_pasta_fq_plonk_index_create
module.exports.caml_pasta_fq_plonk_index_decode = nativeBinding.caml_pasta_fq_plonk_index_decode
module.exports.caml_pasta_fq_plonk_index_domain_d1_size = nativeBinding.caml_pasta_fq_plonk_index_domain_d1_size
module.exports.caml_pasta_fq_plonk_index_domain_d4_size = nativeBinding.caml_pasta_fq_plonk_index_domain_d4_size
module.exports.caml_pasta_fq_plonk_index_domain_d8_size = nativeBinding.caml_pasta_fq_plonk_index_domain_d8_size
module.exports.caml_pasta_fq_plonk_index_encode = nativeBinding.caml_pasta_fq_plonk_index_encode
module.exports.caml_pasta_fq_plonk_index_max_degree = nativeBinding.caml_pasta_fq_plonk_index_max_degree
module.exports.caml_pasta_fq_plonk_index_public_inputs = nativeBinding.caml_pasta_fq_plonk_index_public_inputs
module.exports.caml_pasta_fq_plonk_index_read = nativeBinding.caml_pasta_fq_plonk_index_read
module.exports.caml_pasta_fq_plonk_index_write = nativeBinding.caml_pasta_fq_plonk_index_write
module.exports.caml_pasta_fq_plonk_proof_batch_verify = nativeBinding.caml_pasta_fq_plonk_proof_batch_verify
module.exports.caml_pasta_fq_plonk_proof_create = nativeBinding.caml_pasta_fq_plonk_proof_create
module.exports.caml_pasta_fq_plonk_proof_deep_copy = nativeBinding.caml_pasta_fq_plonk_proof_deep_copy
module.exports.caml_pasta_fq_plonk_proof_dummy = nativeBinding.caml_pasta_fq_plonk_proof_dummy
module.exports.caml_pasta_fq_plonk_proof_verify = nativeBinding.caml_pasta_fq_plonk_proof_verify
module.exports.caml_pasta_fq_plonk_verifier_index_create = nativeBinding.caml_pasta_fq_plonk_verifier_index_create
module.exports.caml_pasta_fq_plonk_verifier_index_deep_copy = nativeBinding.caml_pasta_fq_plonk_verifier_index_deep_copy
module.exports.caml_pasta_fq_plonk_verifier_index_deserialize = nativeBinding.caml_pasta_fq_plonk_verifier_index_deserialize
module.exports.caml_pasta_fq_plonk_verifier_index_dummy = nativeBinding.caml_pasta_fq_plonk_verifier_index_dummy
module.exports.caml_pasta_fq_plonk_verifier_index_read = nativeBinding.caml_pasta_fq_plonk_verifier_index_read
module.exports.caml_pasta_fq_plonk_verifier_index_serialize = nativeBinding.caml_pasta_fq_plonk_verifier_index_serialize
module.exports.caml_pasta_fq_plonk_verifier_index_shifts = nativeBinding.caml_pasta_fq_plonk_verifier_index_shifts
module.exports.caml_pasta_fq_plonk_verifier_index_write = nativeBinding.caml_pasta_fq_plonk_verifier_index_write
module.exports.caml_pasta_fq_poseidon_block_cipher = nativeBinding.caml_pasta_fq_poseidon_block_cipher
module.exports.caml_vesta_affine_one = nativeBinding.caml_vesta_affine_one
module.exports.camlPastaFpPlonkGateVectorFromBytesExternal = nativeBinding.camlPastaFpPlonkGateVectorFromBytesExternal
module.exports.camlPastaFqPlonkGateVectorFromBytesExternal = nativeBinding.camlPastaFqPlonkGateVectorFromBytesExternal
module.exports.camlRayonInitSingleThreaded = nativeBinding.camlRayonInitSingleThreaded
module.exports.camlRayonSpawnPool = nativeBinding.camlRayonSpawnPool
module.exports.camlRayonStartedThreads = nativeBinding.camlRayonStartedThreads
module.exports.fp_oracles_create = nativeBinding.fp_oracles_create
module.exports.fp_oracles_deep_copy = nativeBinding.fp_oracles_deep_copy
module.exports.fp_oracles_dummy = nativeBinding.fp_oracles_dummy
module.exports.fq_oracles_create = nativeBinding.fq_oracles_create
module.exports.fq_oracles_deep_copy = nativeBinding.fq_oracles_deep_copy
module.exports.fq_oracles_dummy = nativeBinding.fq_oracles_dummy
module.exports.getNativeCalls = nativeBinding.getNativeCalls
module.exports.OS_NAME = nativeBinding.OS_NAME
module.exports.pasta_fp_plonk_index_domain_d8_size = nativeBinding.pasta_fp_plonk_index_domain_d8_size
module.exports.prover_index_fp_deserialize = nativeBinding.prover_index_fp_deserialize
module.exports.prover_index_fp_serialize = nativeBinding.prover_index_fp_serialize
module.exports.prover_index_fq_deserialize = nativeBinding.prover_index_fq_deserialize
module.exports.prover_index_fq_serialize = nativeBinding.prover_index_fq_serialize
module.exports.prover_to_json = nativeBinding.prover_to_json
