/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 1024,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'kimchi_napi.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'kimchi_napi.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('@o1js/native-wasm32-wasi')
  } catch {
    throw new Error('Cannot find kimchi_napi.wasm32-wasi.wasm file, and @o1js/native-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.WasmFpGateVector = __napiModule.exports.WasmFpGateVector
module.exports.NapiFpGateVector = __napiModule.exports.NapiFpGateVector
module.exports.WasmFpLookupCommitments = __napiModule.exports.WasmFpLookupCommitments
module.exports.NapiFpLookupCommitments = __napiModule.exports.NapiFpLookupCommitments
module.exports.WasmFpOpeningProof = __napiModule.exports.WasmFpOpeningProof
module.exports.NapiFpOpeningProof = __napiModule.exports.NapiFpOpeningProof
module.exports.WasmFpOracles = __napiModule.exports.WasmFpOracles
module.exports.NapiFpOracles = __napiModule.exports.NapiFpOracles
module.exports.WasmFpPolyComm = __napiModule.exports.WasmFpPolyComm
module.exports.NapiFpPolyComm = __napiModule.exports.NapiFpPolyComm
module.exports.WasmFpProverCommitments = __napiModule.exports.WasmFpProverCommitments
module.exports.NapiFpProverCommitments = __napiModule.exports.NapiFpProverCommitments
module.exports.WasmFpProverProof = __napiModule.exports.WasmFpProverProof
module.exports.NapiFpProverProof = __napiModule.exports.NapiFpProverProof
module.exports.WasmFpRandomOracles = __napiModule.exports.WasmFpRandomOracles
module.exports.NapiFpRandomOracles = __napiModule.exports.NapiFpRandomOracles
module.exports.WasmFpSrs = __napiModule.exports.WasmFpSrs
module.exports.NapiFpSrs = __napiModule.exports.NapiFpSrs
module.exports.WasmFqGateVector = __napiModule.exports.WasmFqGateVector
module.exports.NapiFqGateVector = __napiModule.exports.NapiFqGateVector
module.exports.WasmFqLookupCommitments = __napiModule.exports.WasmFqLookupCommitments
module.exports.NapiFqLookupCommitments = __napiModule.exports.NapiFqLookupCommitments
module.exports.WasmFqOpeningProof = __napiModule.exports.WasmFqOpeningProof
module.exports.NapiFqOpeningProof = __napiModule.exports.NapiFqOpeningProof
module.exports.WasmFqOracles = __napiModule.exports.WasmFqOracles
module.exports.NapiFqOracles = __napiModule.exports.NapiFqOracles
module.exports.WasmFqPolyComm = __napiModule.exports.WasmFqPolyComm
module.exports.NapiFqPolyComm = __napiModule.exports.NapiFqPolyComm
module.exports.WasmFqProverCommitments = __napiModule.exports.WasmFqProverCommitments
module.exports.NapiFqProverCommitments = __napiModule.exports.NapiFqProverCommitments
module.exports.WasmFqProverProof = __napiModule.exports.WasmFqProverProof
module.exports.NapiFqProverProof = __napiModule.exports.NapiFqProverProof
module.exports.WasmFqRandomOracles = __napiModule.exports.WasmFqRandomOracles
module.exports.NapiFqRandomOracles = __napiModule.exports.NapiFqRandomOracles
module.exports.WasmFqSrs = __napiModule.exports.WasmFqSrs
module.exports.NapiFqSrs = __napiModule.exports.NapiFqSrs
module.exports.WasmPastaFpLookupTable = __napiModule.exports.WasmPastaFpLookupTable
module.exports.NapiPastaFpLookupTable = __napiModule.exports.NapiPastaFpLookupTable
module.exports.WasmPastaFpPlonkIndex = __napiModule.exports.WasmPastaFpPlonkIndex
module.exports.WasmPastaFpRuntimeTableCfg = __napiModule.exports.WasmPastaFpRuntimeTableCfg
module.exports.NapiPastaFpRuntimeTableCfg = __napiModule.exports.NapiPastaFpRuntimeTableCfg
module.exports.WasmPastaFqLookupTable = __napiModule.exports.WasmPastaFqLookupTable
module.exports.NapiPastaFqLookupTable = __napiModule.exports.NapiPastaFqLookupTable
module.exports.WasmPastaFqPlonkIndex = __napiModule.exports.WasmPastaFqPlonkIndex
module.exports.WasmPastaFqRuntimeTableCfg = __napiModule.exports.WasmPastaFqRuntimeTableCfg
module.exports.NapiPastaFqRuntimeTableCfg = __napiModule.exports.NapiPastaFqRuntimeTableCfg
module.exports.WasmVecVecFp = __napiModule.exports.WasmVecVecFp
module.exports.NapiVecVecFp = __napiModule.exports.NapiVecVecFp
module.exports.WasmVecVecFq = __napiModule.exports.WasmVecVecFq
module.exports.NapiVecVecFq = __napiModule.exports.NapiVecVecFq
module.exports.ARCH_NAME = __napiModule.exports.ARCH_NAME
module.exports.BACKING = __napiModule.exports.BACKING
module.exports.caml_fp_srs_add_lagrange_basis = __napiModule.exports.caml_fp_srs_add_lagrange_basis
module.exports.caml_fp_srs_b_poly_commitment = __napiModule.exports.caml_fp_srs_b_poly_commitment
module.exports.caml_fp_srs_batch_accumulator_check = __napiModule.exports.caml_fp_srs_batch_accumulator_check
module.exports.caml_fp_srs_batch_accumulator_generate = __napiModule.exports.caml_fp_srs_batch_accumulator_generate
module.exports.caml_fp_srs_commit_evaluations = __napiModule.exports.caml_fp_srs_commit_evaluations
module.exports.caml_fp_srs_create = __napiModule.exports.caml_fp_srs_create
module.exports.caml_fp_srs_create_parallel = __napiModule.exports.caml_fp_srs_create_parallel
module.exports.caml_fp_srs_from_bytes = __napiModule.exports.caml_fp_srs_from_bytes
module.exports.caml_fp_srs_get = __napiModule.exports.caml_fp_srs_get
module.exports.caml_fp_srs_get_lagrange_basis = __napiModule.exports.caml_fp_srs_get_lagrange_basis
module.exports.caml_fp_srs_h = __napiModule.exports.caml_fp_srs_h
module.exports.caml_fp_srs_lagrange_commitment = __napiModule.exports.caml_fp_srs_lagrange_commitment
module.exports.caml_fp_srs_lagrange_commitments_whole_domain_ptr = __napiModule.exports.caml_fp_srs_lagrange_commitments_whole_domain_ptr
module.exports.caml_fp_srs_maybe_lagrange_commitment = __napiModule.exports.caml_fp_srs_maybe_lagrange_commitment
module.exports.caml_fp_srs_read = __napiModule.exports.caml_fp_srs_read
module.exports.caml_fp_srs_set = __napiModule.exports.caml_fp_srs_set
module.exports.caml_fp_srs_set_lagrange_basis = __napiModule.exports.caml_fp_srs_set_lagrange_basis
module.exports.caml_fp_srs_to_bytes = __napiModule.exports.caml_fp_srs_to_bytes
module.exports.caml_fp_srs_write = __napiModule.exports.caml_fp_srs_write
module.exports.caml_fq_srs_add_lagrange_basis = __napiModule.exports.caml_fq_srs_add_lagrange_basis
module.exports.caml_fq_srs_b_poly_commitment = __napiModule.exports.caml_fq_srs_b_poly_commitment
module.exports.caml_fq_srs_batch_accumulator_check = __napiModule.exports.caml_fq_srs_batch_accumulator_check
module.exports.caml_fq_srs_batch_accumulator_generate = __napiModule.exports.caml_fq_srs_batch_accumulator_generate
module.exports.caml_fq_srs_commit_evaluations = __napiModule.exports.caml_fq_srs_commit_evaluations
module.exports.caml_fq_srs_create = __napiModule.exports.caml_fq_srs_create
module.exports.caml_fq_srs_create_parallel = __napiModule.exports.caml_fq_srs_create_parallel
module.exports.caml_fq_srs_from_bytes = __napiModule.exports.caml_fq_srs_from_bytes
module.exports.caml_fq_srs_get = __napiModule.exports.caml_fq_srs_get
module.exports.caml_fq_srs_get_lagrange_basis = __napiModule.exports.caml_fq_srs_get_lagrange_basis
module.exports.caml_fq_srs_h = __napiModule.exports.caml_fq_srs_h
module.exports.caml_fq_srs_lagrange_commitment = __napiModule.exports.caml_fq_srs_lagrange_commitment
module.exports.caml_fq_srs_lagrange_commitments_whole_domain_ptr = __napiModule.exports.caml_fq_srs_lagrange_commitments_whole_domain_ptr
module.exports.caml_fq_srs_maybe_lagrange_commitment = __napiModule.exports.caml_fq_srs_maybe_lagrange_commitment
module.exports.caml_fq_srs_read = __napiModule.exports.caml_fq_srs_read
module.exports.caml_fq_srs_set = __napiModule.exports.caml_fq_srs_set
module.exports.caml_fq_srs_set_lagrange_basis = __napiModule.exports.caml_fq_srs_set_lagrange_basis
module.exports.caml_fq_srs_to_bytes = __napiModule.exports.caml_fq_srs_to_bytes
module.exports.caml_fq_srs_write = __napiModule.exports.caml_fq_srs_write
module.exports.caml_pallas_affine_one = __napiModule.exports.caml_pallas_affine_one
module.exports.caml_pasta_fp_plonk_circuit_serialize = __napiModule.exports.caml_pasta_fp_plonk_circuit_serialize
module.exports.caml_pasta_fp_plonk_gate_vector_add = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_add
module.exports.caml_pasta_fp_plonk_gate_vector_create = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_create
module.exports.caml_pasta_fp_plonk_gate_vector_digest = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_digest
module.exports.caml_pasta_fp_plonk_gate_vector_from_bytes = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_from_bytes
module.exports.caml_pasta_fp_plonk_gate_vector_get = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_get
module.exports.caml_pasta_fp_plonk_gate_vector_len = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_len
module.exports.caml_pasta_fp_plonk_gate_vector_to_bytes = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_to_bytes
module.exports.caml_pasta_fp_plonk_gate_vector_wrap = __napiModule.exports.caml_pasta_fp_plonk_gate_vector_wrap
module.exports.caml_pasta_fp_plonk_index_create = __napiModule.exports.caml_pasta_fp_plonk_index_create
module.exports.caml_pasta_fp_plonk_index_decode = __napiModule.exports.caml_pasta_fp_plonk_index_decode
module.exports.caml_pasta_fp_plonk_index_domain_d1_size = __napiModule.exports.caml_pasta_fp_plonk_index_domain_d1_size
module.exports.caml_pasta_fp_plonk_index_domain_d4_size = __napiModule.exports.caml_pasta_fp_plonk_index_domain_d4_size
module.exports.caml_pasta_fp_plonk_index_encode = __napiModule.exports.caml_pasta_fp_plonk_index_encode
module.exports.caml_pasta_fp_plonk_index_max_degree = __napiModule.exports.caml_pasta_fp_plonk_index_max_degree
module.exports.caml_pasta_fp_plonk_index_public_inputs = __napiModule.exports.caml_pasta_fp_plonk_index_public_inputs
module.exports.caml_pasta_fp_plonk_index_read = __napiModule.exports.caml_pasta_fp_plonk_index_read
module.exports.caml_pasta_fp_plonk_index_write = __napiModule.exports.caml_pasta_fp_plonk_index_write
module.exports.caml_pasta_fp_plonk_proof_batch_verify = __napiModule.exports.caml_pasta_fp_plonk_proof_batch_verify
module.exports.caml_pasta_fp_plonk_proof_create = __napiModule.exports.caml_pasta_fp_plonk_proof_create
module.exports.caml_pasta_fp_plonk_proof_deep_copy = __napiModule.exports.caml_pasta_fp_plonk_proof_deep_copy
module.exports.caml_pasta_fp_plonk_proof_dummy = __napiModule.exports.caml_pasta_fp_plonk_proof_dummy
module.exports.caml_pasta_fp_plonk_proof_verify = __napiModule.exports.caml_pasta_fp_plonk_proof_verify
module.exports.caml_pasta_fp_plonk_verifier_index_create = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_create
module.exports.caml_pasta_fp_plonk_verifier_index_deep_copy = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_deep_copy
module.exports.caml_pasta_fp_plonk_verifier_index_deserialize = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_deserialize
module.exports.caml_pasta_fp_plonk_verifier_index_dummy = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_dummy
module.exports.caml_pasta_fp_plonk_verifier_index_read = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_read
module.exports.caml_pasta_fp_plonk_verifier_index_serialize = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_serialize
module.exports.caml_pasta_fp_plonk_verifier_index_shifts = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_shifts
module.exports.caml_pasta_fp_plonk_verifier_index_write = __napiModule.exports.caml_pasta_fp_plonk_verifier_index_write
module.exports.caml_pasta_fp_poseidon_block_cipher = __napiModule.exports.caml_pasta_fp_poseidon_block_cipher
module.exports.caml_pasta_fq_plonk_circuit_serialize = __napiModule.exports.caml_pasta_fq_plonk_circuit_serialize
module.exports.caml_pasta_fq_plonk_gate_vector_add = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_add
module.exports.caml_pasta_fq_plonk_gate_vector_create = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_create
module.exports.caml_pasta_fq_plonk_gate_vector_digest = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_digest
module.exports.caml_pasta_fq_plonk_gate_vector_from_bytes = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_from_bytes
module.exports.caml_pasta_fq_plonk_gate_vector_get = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_get
module.exports.caml_pasta_fq_plonk_gate_vector_len = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_len
module.exports.caml_pasta_fq_plonk_gate_vector_to_bytes = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_to_bytes
module.exports.caml_pasta_fq_plonk_gate_vector_wrap = __napiModule.exports.caml_pasta_fq_plonk_gate_vector_wrap
module.exports.caml_pasta_fq_plonk_index_create = __napiModule.exports.caml_pasta_fq_plonk_index_create
module.exports.caml_pasta_fq_plonk_index_decode = __napiModule.exports.caml_pasta_fq_plonk_index_decode
module.exports.caml_pasta_fq_plonk_index_domain_d1_size = __napiModule.exports.caml_pasta_fq_plonk_index_domain_d1_size
module.exports.caml_pasta_fq_plonk_index_domain_d4_size = __napiModule.exports.caml_pasta_fq_plonk_index_domain_d4_size
module.exports.caml_pasta_fq_plonk_index_domain_d8_size = __napiModule.exports.caml_pasta_fq_plonk_index_domain_d8_size
module.exports.caml_pasta_fq_plonk_index_encode = __napiModule.exports.caml_pasta_fq_plonk_index_encode
module.exports.caml_pasta_fq_plonk_index_max_degree = __napiModule.exports.caml_pasta_fq_plonk_index_max_degree
module.exports.caml_pasta_fq_plonk_index_public_inputs = __napiModule.exports.caml_pasta_fq_plonk_index_public_inputs
module.exports.caml_pasta_fq_plonk_index_read = __napiModule.exports.caml_pasta_fq_plonk_index_read
module.exports.caml_pasta_fq_plonk_index_write = __napiModule.exports.caml_pasta_fq_plonk_index_write
module.exports.caml_pasta_fq_plonk_proof_batch_verify = __napiModule.exports.caml_pasta_fq_plonk_proof_batch_verify
module.exports.caml_pasta_fq_plonk_proof_create = __napiModule.exports.caml_pasta_fq_plonk_proof_create
module.exports.caml_pasta_fq_plonk_proof_deep_copy = __napiModule.exports.caml_pasta_fq_plonk_proof_deep_copy
module.exports.caml_pasta_fq_plonk_proof_dummy = __napiModule.exports.caml_pasta_fq_plonk_proof_dummy
module.exports.caml_pasta_fq_plonk_proof_verify = __napiModule.exports.caml_pasta_fq_plonk_proof_verify
module.exports.caml_pasta_fq_plonk_verifier_index_create = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_create
module.exports.caml_pasta_fq_plonk_verifier_index_deep_copy = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_deep_copy
module.exports.caml_pasta_fq_plonk_verifier_index_deserialize = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_deserialize
module.exports.caml_pasta_fq_plonk_verifier_index_dummy = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_dummy
module.exports.caml_pasta_fq_plonk_verifier_index_read = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_read
module.exports.caml_pasta_fq_plonk_verifier_index_serialize = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_serialize
module.exports.caml_pasta_fq_plonk_verifier_index_shifts = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_shifts
module.exports.caml_pasta_fq_plonk_verifier_index_write = __napiModule.exports.caml_pasta_fq_plonk_verifier_index_write
module.exports.caml_pasta_fq_poseidon_block_cipher = __napiModule.exports.caml_pasta_fq_poseidon_block_cipher
module.exports.caml_vesta_affine_one = __napiModule.exports.caml_vesta_affine_one
module.exports.camlPastaFpPlonkGateVectorFromBytesExternal = __napiModule.exports.camlPastaFpPlonkGateVectorFromBytesExternal
module.exports.camlPastaFqPlonkGateVectorFromBytesExternal = __napiModule.exports.camlPastaFqPlonkGateVectorFromBytesExternal
module.exports.camlRayonInitSingleThreaded = __napiModule.exports.camlRayonInitSingleThreaded
module.exports.camlRayonSpawnPool = __napiModule.exports.camlRayonSpawnPool
module.exports.camlRayonStartedThreads = __napiModule.exports.camlRayonStartedThreads
module.exports.fp_oracles_create = __napiModule.exports.fp_oracles_create
module.exports.fp_oracles_deep_copy = __napiModule.exports.fp_oracles_deep_copy
module.exports.fp_oracles_dummy = __napiModule.exports.fp_oracles_dummy
module.exports.fq_oracles_create = __napiModule.exports.fq_oracles_create
module.exports.fq_oracles_deep_copy = __napiModule.exports.fq_oracles_deep_copy
module.exports.fq_oracles_dummy = __napiModule.exports.fq_oracles_dummy
module.exports.getNativeCalls = __napiModule.exports.getNativeCalls
module.exports.OS_NAME = __napiModule.exports.OS_NAME
module.exports.pasta_fp_plonk_index_domain_d8_size = __napiModule.exports.pasta_fp_plonk_index_domain_d8_size
module.exports.prover_index_fp_deserialize = __napiModule.exports.prover_index_fp_deserialize
module.exports.prover_index_fp_serialize = __napiModule.exports.prover_index_fp_serialize
module.exports.prover_index_fq_deserialize = __napiModule.exports.prover_index_fq_deserialize
module.exports.prover_index_fq_serialize = __napiModule.exports.prover_index_fq_serialize
module.exports.prover_to_json = __napiModule.exports.prover_to_json
