(library
 (public_name cache_dir.native)
 (name cache_dir_native)
 (libraries
  ;; opam libraries
  base.caml
  async_unix
  base
  core
  async
  async_ssl
  cohttp
  cohttp-async
  conduit-async
  uri
  core_kernel
  stdio
  async_kernel
  ;; local libraries
  key_cache
  logger)
 (instrumentation
  (backend bisect_ppx))
 (inline_tests
  (flags -verbose -show-counts))
 (preprocess
  (pps ppx_mina ppx_version ppx_here ppx_let ppx_custom_printf ppx_inline_test
    ppx_assert))
 (implements cache_dir))
