(* base_merkle_tree_intf.ml *)

(** base module type for masking and masked Merkle trees *)
module type S = sig
  include Merkle_ledger.Intf.Ledger.S

  (* NOTE:
     the reason we can't use Map.t is because it's generated by
     functors and it simply doesn't work if you try to pass modules that are
     versioned around due to the interaction with [ppx-version].
  *)
  type maps_fold_mask =
    { fold_accounts : (Location.t * account) list
    ; fold_token_owners : (token_id * account_id) list
    ; fold_hashes : (Location.Addr.t * hash) list
    ; fold_locations : (account_id * Location.t) list
    ; fold_non_existent_accounts : account_id_set
    }
end
