open Core_kernel

let output_file = Out_channel.create Sys.argv.(1)

let output_string str = Out_channel.output_string output_file str

let () =
  output_string
    {ocaml|
(* This file is generated by gen_scalars_tokens/gen_scalars_tokens.exe. *)

[@@@warning "-4"]

open Scalars

module Feature_flag = Kimchi_types

type challenge_term = Alpha | Beta | Gamma | JointCombiner

type constant_term =
  | EndoCoefficient
  | Mds of int * int
  | Literal of string

type polish_token =
  | Constant of constant_term
  | Challenge of challenge_term
  | Cell of Column.t * curr_or_next
  | Dup
  | Pow of int
  | Add
  | Mul
  | Sub
  | VanishesOnZeroKnowledgeAndPreviousRows
  | UnnormalizedLagrangeBasis of bool * int
  | Store
  | Load of int
  | SkipIf of Kimchi_types.feature_flag * int
  | SkipIfNot of Kimchi_types.feature_flag * int

module type S = sig
  val constant_term_tokens : polish_token array
end

module Tick : S = struct
  let constant_term_tokens : polish_token array =
|ocaml}

external fp_linearization_tokens : unit -> string * (string * string) array
  = "fp_linearization_token_strings"

let fp_constant_term, _fp_index_terms = fp_linearization_tokens ()

let () = output_string fp_constant_term

let () =
  output_string
    {ocaml|
end

module Tock : S = struct
  let constant_term_tokens : polish_token array =
|ocaml}

external fq_linearization_tokens : unit -> string * (string * string) array
  = "fq_linearization_token_strings"

let fq_constant_term, _fq_index_terms = fq_linearization_tokens ()

let () = output_string fq_constant_term

let () = output_string {ocaml|
end
|ocaml}
