apiVersion: v2
name: itn-orchestrator
description: A Helm chart for Mina Protocol's Itn orchestrator
type: application
version: 0.1.1
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - All references to the crypto currency now say Mina
dependencies:
  - name: common-utilities
    version: 0.0.9
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- itn
- orchestrator
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/itn-orchestrator

