(library
 (name mina_graphql_client_app_lib)
 (public_name mina_graphql_client_app.lib)
 (modules mina_graphql_client_app_lib)
 (libraries
  core_unix.command_unix
  ;; opam libraries
  async
  async_kernel
  async_unix
  core
  uri
  yojson
  ;; local libraries
  currency
  graphql_lib
  logger
  mina_base
  mina_graphql_client
  mina_numbers
  mina_transaction
  signature_lib
  sync_status)
 (instrumentation (backend bisect_ppx))
 (preprocess (pps ppx_version ppx_let ppx_mina)))

(executable
 (name mina_graphql_client_app)
 (package mina_graphql_client_app)
 (public_name mina-graphql-client)
 (modules mina_graphql_client_app)
 (libraries mina_graphql_client_app_lib)
 (instrumentation (backend bisect_ppx))
 (preprocess (pps ppx_version)))
