#build with: 
# cat /home/helenl1/work/mina/dockerfiles/Dockerfile-rosetta | docker build -t gcr.io/o1labs-192920/mina-rosetta-builder:latest --target builder --build-arg deb_codename=stretch --build-arg MINA_BRANCH=<this branch> -
# docker build -t txn_burst_util -f Dockerfile_txn_burst .

#run with:
# docker run --entrypoint ./_build/default/src/app/batch_generate_keys/batch_generate_keys.exe txn_burst_util gen-there-and-back-txns --num-accts 1 --num-txn-per-acct 10 --origin-sender-pk B62qmnkbvNpNvxJ9FkSkBy5W6VkquHbgN2MDHh1P8mRVX3FQ1eWtcxV

#or run with:
# docker run -v <demo key local path>:/home/opam/key/demo_key --entrypoint ./_build/default/src/app/batch_generate_keys/batch_generate_keys.exe txn_burst_util gen-there-and-back-txns --num-accts 1 --num-txn-per-acct 10 --origin-sender-sk-path "/home/opam/key/demo_key"


FROM gcr.io/o1labs-192920/mina-rosetta-builder

COPY ./batch_generate_keys.ml /

ENV DUNE_PROFILE devnet

RUN eval $(opam config env) \
  && git pull \
  && git checkout feature/generate-txns-create-many-accounts-2 \
  && dune build --profile=${DUNE_PROFILE} \
    src/app/generate_keypair/generate_keypair.exe \
    src/app/cli/src/mina.exe \
    src/app/archive/archive.exe \
    src/app/rosetta/rosetta.exe \
    src/app/runtime_genesis_ledger/runtime_genesis_ledger.exe \
    src/app/generate_keypair/generate_keypair.exe \
    src/app/rosetta/ocaml-signer/signer.exe \
  && rm -rf _build \
  && dune build src/app/batch_generate_keys/batch_generate_keys.exe

USER root

RUN mkdir /keys && chmod 700 /keys
ENV MINA_PRIVKEY_PASS ""

RUN mkdir /usr/share/man/man7 /usr/share/man/man1
RUN apt-get -y update && apt-get -y install man

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates postgresql-client-9.6 postgresql-9.6 postgresql-contrib-9.6

RUN apt upgrade && apt dist-upgrade

RUN echo "deb [trusted=yes] http://packages.o1test.net release main" | sudo tee /etc/apt/sources.list.d/mina.list \
  && apt-get update \
  && apt-get install -y curl unzip mina-testnet-postake-medium-curves=1.0.5-68200c7

ENTRYPOINT ["./_build/default/src/app/batch_generate_keys/batch_generate_keys.exe"]