(executable
 (name dump_side_loaded_main)
 (flags
  (:standard -warn-error +a)
  -open
  Core_kernel
  -open
  Pickles)
 (preprocess
  (pps ppx_jane))
 (libraries
  ; Opam libraries
  core_kernel
  ; Mina libraries
  ; mina_base links crypto_params, which sets the URS info from
  ; Cache_dir.cache; the fake implementation's is empty.
  cache_dir.fake
  mina_base
  pickles
  pickles.backend
  pickles_types
  promise
  snarky.backendless))
