#build with: 
# cat /home/helenl1/work/mina/dockerfiles/Dockerfile-rosetta | docker build -t gcr.io/o1labs-192920/mina-rosetta-builder:latest --target builder --build-arg deb_codename=stretch --build-arg MINA_BRANCH=<this branch> -
# docker build -t txn_burst_util -f Dockerfile_txn_burst .

#or run with:
# docker run -v <local keypath>:/keys --entrypoint ./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe txn_burst_util --num-txn-per-acct 10 --origin-sender-sk-path "/keys/<origin key path>" --origin-sender-sk-pw "some password" --returner-sk-path "/keys/<origin key path>" --returner-sk-pw "some password"

FROM minaprotocol/mina-toolchain:1.3.1beta1-compatible-9839d34-bullseye

USER opam

#install mina
RUN sudo apt-get -y update && sudo apt-get -y install man
RUN sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates
RUN sudo echo "deb [trusted=yes] http://packages.o1test.net $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/mina.list \
  && sudo apt-get update\
  && sudo apt-get install -y curl unzip mina-mainnet=1.3.0-9b0369c

# compile txn burst tool
# COPY ./batch_txn_tool.ml /
ENV PATH "$PATH:/usr/lib/go/bin:$HOME/.cargo/bin"
RUN eval $(opam config env) \
  && git pull \
  && git checkout new_gossipqa_COMP \
  && git submodule update --init --recursive \
  # && mv /batch_txn_tool.ml src/app/batch_txn_tool \
  # && dune build --profile=${DUNE_PROFILE} \
  #   src/app/generate_keypair/generate_keypair.exe \
  #   src/app/cli/src/mina.exe \
  #   src/app/archive/archive.exe \
  #   src/app/rosetta/rosetta.exe \
  #   src/app/runtime_genesis_ledger/runtime_genesis_ledger.exe \
  #   src/app/generate_keypair/generate_keypair.exe \
  #   src/app/rosetta/ocaml-signer/signer.exe \
  # && rm -rf _build \
  && dune build src/app/batch_txn_tool/batch_txn_tool.exe

USER root
# prepare the key directories
RUN mkdir /keys && chmod 700 /keys
  # && mkdir /keys/whale-key/ && chmod 700 /keys/whale-key/ \
  # && mkdir /keys/fish-key/ && chmod 700 /keys/fish-key/
ENV MINA_PRIVKEY_PASS ""

ENTRYPOINT ["./_build/default/src/app/batch_txn_tool/batch_txn_tool.exe"]
