(library
 (name snark_profiler_lib)
 (public_name snark_profiler_lib)
 (libraries
  ;;opam libraries
  integers
  astring
  sexplib0
  result
  async_kernel
  async_unix
  core_kernel
  core
  base
  async
  base.caml
  base.base_internalhash_types
  ;;local libraries
  currency
  genesis_constants
  mina_transaction
  mina_ledger
  mina_base
  mina_state
  signature_lib
  mina_numbers
  with_hash
  transaction_snark
  transaction_snark_tests
  transaction_protocol_state
  sgn
  mina_compile_config
  mina_transaction_logic
  verifier
  pickles_types
  snark_params
  zkapp_command_builder
  test_genesis_ledger)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps
   ppx_mina
   ppx_version
   ppx_base
   ppx_assert
   ppx_bench
   ppx_bin_prot
   ppx_custom_printf
   ppx_fields_conv
   ppx_fixed_literal
   ppx_here
   ppx_inline_test
   ppx_let
   ppx_module_timer
   ppx_optional
   ppx_pipebang
   ppx_sexp_message
   ppx_sexp_value
   ppx_string
   ppx_typerep_conv
   ppx_variants_conv)))
