testnetName: "mainnet-backup"

archive:
  replicas: 1
  hostPort: "10998"
  image: "gcr.io/o1labs-192920/mina-archive:1.3.1.2-25388a0-bullseye"
  postgresHost:  '{{ .Release.Name }}-postgresql'
  postgresUri: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ tpl .Values.archive.postgresHost . }}:{{ .Values.archive.ports.postgres }}/{{ .Values.postgresql.auth.database }}
  ports:
    server: "3086"
    postgres: "5432"
    metrics: "10002"
  enableLocalDaemon: false
  enablePostgresDB: true
  enableDumpCronjob: true
  initFromDump: true

postgresql:
  primary:
    name: "archive_balances_migrated"
    persistence:
      enabled: true
      size: "100Gi"
      storageClass: "ssd-retain"
    initdb:
      user: "mina"
      password: "zu9rooquah3sie3ooquee6ohxoow9eivae1ahyeibaPeegaiCeish0beek6hooph"
  auth:
    username: "mina"
    password: "zu9rooquah3sie3ooquee6ohxoow9eivae1ahyeibaPeegaiCeish0beek6hooph"
    database: "archive_balances_migrated"
    enablePostgresUser: false

nodeSelector:
  preemptible: false

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 5
  initialDelaySeconds: 30
